import Link from "next/link";
import { ArrowRight, Boxes, ClipboardList, PackagePlus, Scale, ShoppingBasket } from "lucide-react";
import { Card } from "@/components/ui/card";
import { money } from "@/lib/format";
import { requireAppContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";

type Balance = { quantity_kg: number; weighted_average_cost: number; inventory_value: number };
type Material = { id: string; name: string; description: string | null; raw_material_inventory_balances: Balance[] | Balance | null };

export default async function MaterialsPage() {
  const context = await requireAppContext(); const supabase = await createClient();
  const { data: materialData } = await supabase.from("raw_materials").select("id,name,description,raw_material_inventory_balances(quantity_kg,weighted_average_cost,inventory_value)").eq("farm_id", context.farm.id).eq("is_active", true).order("name");
  const materials = (materialData ?? []) as unknown as Material[];
  const totalKg = materials.reduce((total, material) => total + Number(balanceFor(material)?.quantity_kg ?? 0), 0);
  const totalValue = materials.reduce((total, material) => total + Number(balanceFor(material)?.inventory_value ?? 0), 0);

  return <section aria-labelledby="materials-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-stone-200/90 pb-6"><div className="max-w-xl"><p className="text-sm font-semibold tracking-[0.08em] text-emerald-800">Feed operations</p><h1 id="materials-heading" className="mt-2 text-4xl font-bold tracking-[-0.04em] text-stone-900 sm:text-5xl">Materials</h1><p className="mt-3 leading-7 text-stone-600">Keep raw ingredients separate from finished feed so every batch starts with a clear, valued material balance.</p></div><div className="flex flex-wrap gap-2"><Link href="/feed/materials/new" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white shadow-[0_12px_24px_-18px_rgba(6,78,59,0.9)] hover:-translate-y-px hover:bg-emerald-800"><PackagePlus size={18}/>Add material</Link><Link href="/feed/materials/purchase" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900 hover:border-emerald-300 hover:bg-emerald-100"><ShoppingBasket size={18}/>Add material purchase</Link></div></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Summary icon={Boxes} label="Materials tracked" value={materials.length.toLocaleString()} detail="Active raw materials"/><Summary icon={Scale} label="Material on hand" value={`${totalKg.toLocaleString()} kg`} detail="Across all material lines"/><Summary icon={ClipboardList} label="Material value" value={money(totalValue, context.farm.currency)} detail="Weighted-average valuation"/></section>
    <div className="mt-7 flex flex-wrap gap-2"><Link href="/feed/materials/opening" className="rounded-xl border border-stone-200 bg-white px-3 py-2 text-sm font-semibold text-stone-700 hover:border-emerald-300 hover:bg-emerald-50">Set opening stock</Link><Link href="/feed/setup" className="rounded-xl border border-stone-200 bg-white px-3 py-2 text-sm font-semibold text-stone-700 hover:border-emerald-300 hover:bg-emerald-50">Configure Feed Setup</Link></div>
    <section className="mt-7"><div className="mb-4"><h2 className="text-xl font-bold tracking-[-0.02em]">Material inventory</h2><p className="mt-1 text-sm text-stone-500">Select a material to review its inventory history and ledger.</p></div><div className="grid gap-4 lg:grid-cols-2">{materials.map((material) => { const balance = balanceFor(material); return <Link key={material.id} href={`/feed/materials/${material.id}`} className="group block focus-visible:rounded-[1.35rem]"><Card className="p-5 transition duration-200 group-hover:-translate-y-0.5 group-hover:border-emerald-300 group-hover:shadow-[0_20px_38px_-30px_rgba(6,78,59,0.6)] sm:p-6"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><ShoppingBasket size={20}/></span><div><h3 className="font-bold text-stone-900">{material.name}</h3><p className="mt-1 text-sm text-stone-500">{material.description || "Raw material"}</p></div></div><ArrowRight className="text-stone-400 transition-transform group-hover:translate-x-0.5 group-hover:text-emerald-700" size={18}/></div><div className="mt-6 grid grid-cols-3 gap-3"><Metric label="Available" value={`${Number(balance?.quantity_kg ?? 0).toLocaleString()} kg`}/><Metric label="Avg cost/kg" value={money(balance?.weighted_average_cost ?? 0, context.farm.currency)}/><Metric label="Stock value" value={money(balance?.inventory_value ?? 0, context.farm.currency)}/></div></Card></Link>; })}{!materials.length && <Card className="p-10 text-center sm:p-14"><ShoppingBasket className="mx-auto text-emerald-700" size={28}/><p className="mt-4 text-lg font-bold">No raw materials have been added yet</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-stone-500">Add the ingredients your farm uses to make feed, then record their opening stock or purchase transactions.</p><Link href="/feed/materials/new" className="mt-6 inline-flex rounded-lg bg-emerald-700 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-800">Add material</Link></Card>}</div></section></section>;
}

function balanceFor(material: Material) { return Array.isArray(material.raw_material_inventory_balances) ? material.raw_material_inventory_balances[0] : material.raw_material_inventory_balances; }
function Summary({ icon: Icon, label, value, detail }: { icon: typeof Boxes; label: string; value: string; detail: string }) { return <Card className="p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><Icon size={19}/></span><p className="text-sm font-semibold text-stone-500">{label}</p></div><p className="data-number mt-5 text-2xl font-bold tracking-[-0.035em] text-stone-900">{value}</p><p className="mt-2 text-sm text-stone-500">{detail}</p></Card>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold tracking-[0.06em] text-stone-500">{label}</p><p className="data-number mt-2 text-sm font-bold text-stone-900">{value}</p></div>; }
