import Link from "next/link";
import { CalendarRange, Egg, Plus, TrendingUp, Wheat } from "lucide-react";
import { requireAppContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { formatFarmDate } from "@/lib/farm-date";
import { Card } from "@/components/ui/card";
import { Pagination, pageWindow } from "@/components/ui/pagination";

export const metadata = { title: "Daily Production" };

export default async function ProductionPage({ searchParams }: { searchParams: Promise<{ flock?: string; from?: string; to?: string; page?: string }> }) {
  const context = await requireAppContext(); const params = await searchParams; const supabase = await createClient(); const window = pageWindow(params.page);
  let query = supabase.from("v_daily_production_metrics").select("*").eq("farm_id", context.farm.id).order("production_date", { ascending: false });
  if (params.flock) query = query.eq("flock_id", params.flock); if (params.from) query = query.gte("production_date", params.from); if (params.to) query = query.lte("production_date", params.to); query = query.range(window.from, window.to);
  const [{ data: rows }, { data: flocks }] = await Promise.all([query, supabase.from("flocks").select("id,flock_name").eq("farm_id", context.farm.id).order("flock_name")]);
  const records = rows ?? []; const names = new Map(flocks?.map((flock) => [flock.id, flock.flock_name]));
  const eggs = records.reduce((total, record) => total + Number(record.eggs_collected ?? 0), 0); const good = records.reduce((total, record) => total + Number(record.good_eggs ?? 0), 0); const feed = records.reduce((total, record) => total + Number(record.feed_consumed_kg ?? 0), 0);

  return <section aria-labelledby="production-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-stone-200/90 pb-6"><div className="max-w-xl"><p className="text-sm font-semibold tracking-[0.08em] text-emerald-800">Farm operations</p><h1 id="production-heading" className="mt-2 text-4xl font-bold tracking-[-0.04em] text-stone-900 sm:text-5xl">Daily production</h1><p className="mt-3 leading-7 text-stone-600">Review your recorded eggs, bird performance, feed use, and losses by flock and date.</p></div><Link href="/production/new" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white shadow-[0_12px_24px_-18px_rgba(6,78,59,0.9)] hover:-translate-y-px hover:bg-emerald-800"><Plus size={18}/>Record production</Link></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={Egg} label="Eggs collected" value={eggs.toLocaleString()} detail="Records on this page"/><Metric icon={TrendingUp} label="Saleable eggs" value={good.toLocaleString()} detail="Good eggs recorded"/><Metric icon={Wheat} label="Feed consumed" value={`${feed.toFixed(1)} kg`} detail="Recorded production days"/></section>
    <form className="mt-7 grid gap-3 rounded-[1.35rem] border border-stone-200/90 bg-white/90 p-4 shadow-[0_18px_42px_-34px_rgba(25,65,45,0.48)] sm:grid-cols-4" aria-label="Filter production records"><label className="text-sm font-semibold text-stone-700"><span className="sr-only">Flock</span><select name="flock" defaultValue={params.flock ?? ""} className="mt-1 min-h-11 w-full rounded-xl border border-stone-200 bg-stone-50 px-3"><option value="">All flocks</option>{flocks?.map((flock) => <option key={flock.id} value={flock.id}>{flock.flock_name}</option>)}</select></label><label className="text-sm font-semibold text-stone-700">From<input name="from" defaultValue={params.from} type="date" className="mt-1 min-h-11 w-full rounded-xl border border-stone-200 bg-stone-50 px-3"/></label><label className="text-sm font-semibold text-stone-700">To<input name="to" defaultValue={params.to} type="date" className="mt-1 min-h-11 w-full rounded-xl border border-stone-200 bg-stone-50 px-3"/></label><button className="mt-auto min-h-11 rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-stone-700 hover:border-emerald-300 hover:bg-emerald-50">Apply filters</button></form>
    <Card className="mt-7 overflow-hidden"><div className="flex items-center justify-between border-b border-stone-200 px-5 py-5 sm:px-6"><div><h2 className="font-bold tracking-[-0.02em]">Production records</h2><p className="mt-1 text-sm text-stone-500">Select a record for the complete daily entry.</p></div><CalendarRange className="text-emerald-700" size={20}/></div><div className="hidden grid-cols-[1.1fr_1.5fr_repeat(7,1fr)] gap-3 border-b border-stone-100 bg-stone-50/80 px-6 py-3 text-xs font-bold tracking-[0.05em] text-stone-500 xl:grid">{["Date","Flock","Eggs","Good","Cracked","Live birds","Hen-Day","Feed kg","Losses"].map((heading) => <span key={heading}>{heading}</span>)}</div>{records.map((record) => <Link key={record.production_id} href={`/production/${record.production_id}`} className="grid gap-3 border-b border-stone-100 p-5 transition hover:bg-emerald-50/40 xl:grid-cols-[1.1fr_1.5fr_repeat(7,1fr)] xl:items-center xl:px-6"><div><span className="text-xs font-semibold text-stone-500 xl:hidden">Date · </span>{formatFarmDate(record.production_date)}</div><div className="font-bold text-stone-900">{names.get(record.flock_id)}</div>{[["Eggs",record.eggs_collected],["Good",record.good_eggs],["Cracked",record.cracked_eggs],["Live birds",record.live_birds],["Hen-Day",record.hen_day_percentage == null ? "—" : `${record.hen_day_percentage}%`],["Feed",`${record.feed_consumed_kg} kg`],["Losses",Number(record.deaths ?? 0) + Number(record.culls ?? 0)]].map(([label, value]) => <div key={String(label)} className="data-number text-sm"><span className="font-semibold text-stone-500 xl:hidden">{label} · </span>{value}</div>)}</Link>)}{!records.length && <div className="p-10 text-center sm:p-14"><Egg className="mx-auto text-emerald-700" size={28}/><p className="mt-4 text-lg font-bold">No production records match these filters</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-stone-500">Record the day&apos;s production to see egg output, flock performance, feed consumption, and losses together.</p><Link href="/production/new" className="mt-6 inline-flex rounded-lg text-sm font-semibold text-emerald-800 underline decoration-emerald-300 underline-offset-4">Record production</Link></div>}</Card><Pagination page={window.page} hasMore={records.length === 50} base="/production" params={params}/></section>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Egg; label: string; value: string; detail: string }) { return <Card className="p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><Icon size={19}/></span><p className="text-sm font-semibold text-stone-500">{label}</p></div><p className="data-number mt-5 text-2xl font-bold tracking-[-0.035em] text-stone-900">{value}</p><p className="mt-2 text-sm text-stone-500">{detail}</p></Card>; }
