import Link from "next/link";
import { HandCoins, Plus, ReceiptText, Tags } from "lucide-react";
import { money } from "@/lib/format";
import { requireRole } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { Card } from "@/components/ui/card";
import { Pagination, pageWindow } from "@/components/ui/pagination";

export const metadata = { title: "Expenses" };

export default async function Expenses({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await requireRole(["admin", "manager"]); const supabase = await createClient(); const params = await searchParams; const window = pageWindow(params.page); let query = supabase.from("v_expense_payables").select("*").eq("farm_id", context.farm.id).order("expense_date", { ascending: false }); if (params.status) query = query.eq("payment_status", params.status); if (params.source) query = query.eq("source_type", params.source); if (params.from) query = query.gte("expense_date", params.from); if (params.to) query = query.lte("expense_date", params.to); query = query.range(window.from, window.to); const { data } = await query; const expenses = data ?? []; const total = expenses.reduce((value, expense) => value + Number(expense.amount ?? 0), 0); const outstanding = expenses.reduce((value, expense) => value + Number(expense.outstanding_balance ?? 0), 0);
  return <section aria-labelledby="expenses-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-stone-200/90 pb-6"><div className="max-w-xl"><p className="text-sm font-semibold tracking-[0.08em] text-emerald-800">Finance</p><h1 id="expenses-heading" className="mt-2 text-4xl font-bold tracking-[-0.04em] text-stone-900 sm:text-5xl">Expenses</h1><p className="mt-3 leading-7 text-stone-600">Track farm operating costs separately from their payment balances, so your records stay financially accurate.</p></div><Link href="/expenses/new" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white shadow-[0_12px_24px_-18px_rgba(6,78,59,0.9)] hover:-translate-y-px hover:bg-emerald-800"><Plus size={18}/>New expense</Link></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={ReceiptText} label="Expense value" value={money(total, context.farm.currency)} detail="Records on this page"/><Metric icon={HandCoins} label="Outstanding" value={money(outstanding, context.farm.currency)} detail="Still to be paid"/><Metric icon={Tags} label="Expense records" value={expenses.length.toLocaleString()} detail="Matching current filters"/></section>
    <form className="mt-7 grid gap-3 rounded-[1.35rem] border border-stone-200/90 bg-white/90 p-4 shadow-[0_18px_42px_-34px_rgba(25,65,45,0.48)] sm:grid-cols-4"><label className="text-sm font-semibold text-stone-700">From<input name="from" defaultValue={params.from} type="date" className="mt-1 min-h-11 w-full rounded-xl border border-stone-200 bg-stone-50 px-3"/></label><label className="text-sm font-semibold text-stone-700">To<input name="to" defaultValue={params.to} type="date" className="mt-1 min-h-11 w-full rounded-xl border border-stone-200 bg-stone-50 px-3"/></label><label className="text-sm font-semibold text-stone-700">Payment state<select name="status" defaultValue={params.status ?? ""} className="mt-1 min-h-11 w-full rounded-xl border border-stone-200 bg-stone-50 px-3"><option value="">All payment states</option><option>unpaid</option><option>partial</option><option>paid</option></select></label><label className="text-sm font-semibold text-stone-700">Source<select name="source" defaultValue={params.source ?? ""} className="mt-1 min-h-11 w-full rounded-xl border border-stone-200 bg-stone-50 px-3"><option value="">All sources</option><option value="manual">Manual</option><option value="health_record">Health</option><option value="daily_production">Production</option></select></label><button className="min-h-11 rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-stone-700 hover:border-emerald-300 hover:bg-emerald-50 sm:col-span-4">Apply filters</button></form>
    <div className="mt-7 space-y-3">{expenses.map((expense) => <Link key={expense.expense_id} href={`/expenses/${expense.expense_id}`} className="block focus-visible:rounded-[1.35rem]"><Card className="grid gap-4 p-5 transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-[0_20px_38px_-30px_rgba(6,78,59,0.6)] sm:grid-cols-[.85fr_1.4fr_1fr_1fr_1fr] sm:items-center sm:p-6"><div><p className="text-xs font-semibold tracking-[0.06em] text-stone-500">{expense.expense_date}</p><p className="mt-2 font-bold text-stone-900">{expense.expense_number}</p></div><div><p className="font-bold text-stone-900">{expense.category_name}</p><p className="mt-1 text-sm text-stone-500">{expense.description}</p></div><Value label="Payee" value={expense.payee_name || "Not specified"}/><Value label="Amount" value={money(expense.amount, context.farm.currency)}/><div className="sm:text-right"><p className="text-xs font-semibold tracking-[0.06em] text-stone-500">Payment</p><p className="mt-2"><Status value={expense.payment_status}/></p><p className="data-number mt-2 text-sm font-semibold text-stone-700">Due {money(expense.outstanding_balance, context.farm.currency)}</p></div></Card></Link>)}{!expenses.length && <Card className="p-10 text-center sm:p-14"><ReceiptText className="mx-auto text-emerald-700" size={28}/><p className="mt-4 text-lg font-bold">No expenses match these filters</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-stone-500">Add an operating expense to track its cost and, where relevant, its separate payment balance.</p><Link href="/expenses/new" className="mt-6 inline-flex rounded-lg text-sm font-semibold text-emerald-800 underline decoration-emerald-300 underline-offset-4">New expense</Link></Card>}</div><Pagination page={window.page} hasMore={expenses.length === 50} base="/expenses" params={params}/><Link href="/expenses/categories" className="mt-5 inline-flex text-sm font-semibold text-emerald-800 underline decoration-emerald-300 underline-offset-4">Manage expense categories</Link></section>;
}
function Metric({ icon: Icon, label, value, detail }: { icon: typeof ReceiptText; label: string; value: string; detail: string }) { return <Card className="p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><Icon size={19}/></span><p className="text-sm font-semibold text-stone-500">{label}</p></div><p className="data-number mt-5 text-2xl font-bold tracking-[-0.035em] text-stone-900">{value}</p><p className="mt-2 text-sm text-stone-500">{detail}</p></Card>; }
function Value({ label, value }: { label: string; value: string }) { return <div><p className="text-xs font-semibold tracking-[0.06em] text-stone-500">{label}</p><p className="data-number mt-2 text-sm font-bold text-stone-900">{value}</p></div>; }
function Status({ value }: { value: string }) { const tone = value === "paid" ? "bg-emerald-50 text-emerald-800" : value === "partial" ? "bg-amber-50 text-amber-800" : "bg-stone-100 text-stone-700"; return <span className={`inline-flex rounded-lg px-2.5 py-1 text-xs font-bold capitalize ${tone}`}>{value}</span>; }
