import Link from "next/link";
import { CalendarClock, HandCoins, PackagePlus } from "lucide-react";
import { requireRole } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { money } from "@/lib/format";
import { Card } from "@/components/ui/card";
import { MaterialPurchasePaymentForm } from "@/components/forms/material-purchase-payment-form";
import { farmToday } from "@/lib/farm-date";

export default async function Payables({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const context = await requireRole(["admin", "manager"]); const params = await searchParams; const supabase = await createClient(); let request = supabase.from("v_supplier_payables").select("*").eq("farm_id", context.farm.id).gt("outstanding_balance", 0).order("payment_due_date", { ascending: true, nullsFirst: false }); if (params.status) request = request.eq("supplier_due_status", params.status); const { data } = await request; const payables = data ?? []; const outstanding = payables.reduce((total, payable) => total + Number(payable.outstanding_balance ?? 0), 0); const urgent = payables.filter((payable) => payable.supplier_due_status === "overdue" || payable.supplier_due_status === "due_today").length;
  return <section aria-labelledby="payables-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-stone-200/90 pb-6"><div className="max-w-xl"><p className="text-sm font-semibold tracking-[0.08em] text-emerald-800">Finance</p><h1 id="payables-heading" className="mt-2 text-4xl font-bold tracking-[-0.04em] text-stone-900 sm:text-5xl">Supplier payables</h1><p className="mt-3 leading-7 text-stone-600">See outstanding supplier obligations, due dates, and the balance still payable for each purchase.</p></div><Link href="/feed/purchases/new" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white shadow-[0_12px_24px_-18px_rgba(6,78,59,0.9)] hover:-translate-y-px hover:bg-emerald-800"><PackagePlus size={18}/>Add purchase</Link></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><Metric icon={HandCoins} label="Outstanding" value={money(outstanding, context.farm.currency)} detail="Across current supplier balances"/><Metric icon={CalendarClock} label="Needs attention" value={urgent.toLocaleString()} detail={urgent === 1 ? "Due or overdue payable" : "Due or overdue payables"} urgent={urgent > 0}/><Metric icon={PackagePlus} label="Open payables" value={payables.length.toLocaleString()} detail="Purchases with an unpaid balance"/></section>
    <form className="mt-7 flex flex-wrap items-end gap-3 rounded-[1.35rem] border border-stone-200/90 bg-white/90 p-4 shadow-[0_18px_42px_-34px_rgba(25,65,45,0.48)]"><label className="text-sm font-semibold text-stone-700">Status<select name="status" defaultValue={params.status ?? ""} className="mt-1 block min-h-11 rounded-xl border border-stone-200 bg-stone-50 px-3"><option value="">All outstanding</option>{["overdue","due_today","upcoming","unscheduled"].map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></label><button className="min-h-11 rounded-xl border border-stone-200 bg-white px-4 text-sm font-semibold text-stone-700 hover:border-emerald-300 hover:bg-emerald-50">Apply filter</button></form>
    <div className="mt-7 space-y-3">{payables.map((payable) => <Card key={`${payable.source_type}-${payable.id}`} className="grid gap-4 p-5 transition hover:border-emerald-300 sm:grid-cols-[1.3fr_repeat(4,1fr)] sm:items-center sm:p-6"><div><p className="font-bold text-stone-900">{payable.supplier_name ?? "No supplier"}</p><p className="mt-1 text-sm text-stone-500">{payable.purchase_number} · {payable.source_type === "raw_material" ? "Raw materials" : "Finished feed"}</p>{payable.source_type === "raw_material" ? <MaterialPurchasePaymentForm purchaseId={payable.id} maxAmount={Number(payable.outstanding_balance)} today={farmToday(context.farm.timezone)}/> : null}</div><PayableValue label="Original" value={money(payable.total_cost, context.farm.currency)}/><PayableValue label="Outstanding" value={money(payable.outstanding_balance, context.farm.currency)} emphasis/><PayableValue label="Due date" value={payable.payment_due_date ?? "Unscheduled"}/><div><p className="text-xs font-semibold tracking-[0.06em] text-stone-500">Status</p><p className="mt-2"><Status value={payable.supplier_due_status}/></p></div></Card>)}{!payables.length && <Card className="p-10 text-center sm:p-14"><HandCoins className="mx-auto text-emerald-700" size={28}/><p className="mt-4 text-lg font-bold">No supplier payables match this filter</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-stone-500">Supplier balances appear here after a credit purchase is recorded.</p></Card>}</div></section>;
}
function Metric({ icon: Icon, label, value, detail, urgent = false }: { icon: typeof HandCoins; label: string; value: string; detail: string; urgent?: boolean }) { return <Card className="p-5"><div className="flex items-center justify-between"><span className={`grid size-10 place-items-center rounded-xl ${urgent ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-800"}`}><Icon size={19}/></span><p className="text-sm font-semibold text-stone-500">{label}</p></div><p className="data-number mt-5 text-2xl font-bold tracking-[-0.035em] text-stone-900">{value}</p><p className="mt-2 text-sm text-stone-500">{detail}</p></Card>; }
function PayableValue({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) { return <div><p className="text-xs font-semibold tracking-[0.06em] text-stone-500">{label}</p><p className={`data-number mt-2 text-sm font-bold ${emphasis ? "text-emerald-800" : "text-stone-900"}`}>{value}</p></div>; }
function Status({ value }: { value: string }) { const tone = value === "overdue" ? "bg-red-50 text-red-800" : value === "due_today" ? "bg-amber-50 text-amber-800" : value === "upcoming" ? "bg-blue-50 text-blue-800" : "bg-stone-100 text-stone-700"; return <span className={`inline-flex rounded-lg px-2.5 py-1 text-xs font-bold ${tone}`}>{value.replaceAll("_", " ")}</span>; }
