import Link from "next/link";
import { requireAppContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { farmToday, formatFarmDate } from "@/lib/farm-date";
import { Card } from "@/components/ui/card";
import { money } from "@/lib/format";

export const metadata = { title: "Rearing reports" };
type Params = { batch?: string; from?: string; to?: string; asOf?: string; status?: string; view?: string };
type Daily = { report_date:string;opening_birds:number;inbound_birds:number;deaths:number;transfers_out:number;other_outbound:number;closing_birds:number;daily_record_status:string;observations:string|null;feed_consumed_kg:number;feed_cost:number|null;feed_products:{product:string;quantity_kg:number;cost:number|null}[];completed_health_activities:number;scheduled_health_activities:number;attributable_cost:number|null };
type Reconciliation = { category:string;expected_value:number|null;actual_value:number|null;difference:number|null;reconciliation_status:string;source_references:unknown };
type Lifecycle = { as_of_date:string;initial_birds:number;deaths:number;transferred_birds:number;remaining_birds:number;survival_rate:number|null;feed_consumed_kg:number;feed_cost:number|null;historical_cost:number|null;transferred_cost:number|null;remaining_cost:number|null;cost_per_remaining_bird:number|null;cost_complete:boolean };
const validDate=(value:string|undefined)=>!!value&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`));

export default async function RearingReports({searchParams}:{searchParams:Promise<Params>}){
  const context=await requireAppContext(),params=await searchParams,supabase=await createClient(),today=farmToday(context.farm.timezone);
  const to=validDate(params.to)?params.to!:today,from=validDate(params.from)?params.from!:new Date(Date.parse(`${to}T00:00:00Z`)-6*86400000).toISOString().slice(0,10),asOf=validDate(params.asOf)?params.asOf!:today,status=params.status??"";
  const {data:batches}=await supabase.from("rearing_batches").select("id,batch_code,arrival_date").eq("farm_id",context.farm.id).order("arrival_date",{ascending:false}).limit(100);
  const batchId=params.batch&&batches?.some(b=>b.id===params.batch)?params.batch:batches?.[0]?.id;
  const selectedBatch=batches?.find(b=>b.id===batchId),lifecycleNotYetArrived=!!selectedBatch&&asOf<selectedBatch.arrival_date;
  const lifecycleQuery=batchId&&!lifecycleNotYetArrived?supabase.rpc("get_rearing_lifecycle_as_of",{target_batch:batchId,target_date:asOf}):Promise.resolve({data:null,error:null});
  const [{data:daily,error:dailyError},{data:checks,error:checkError},{data:costChecks,error:costCheckError},{data:lifecycleData,error:lifecycleError}] = batchId ? await Promise.all([
    supabase.rpc("get_rearing_daily_report",{target_batch:batchId,target_from:from,target_to:to}),
    supabase.rpc("get_rearing_reconciliation",{target_batch:batchId}),
    supabase.rpc("get_rearing_cost_source_status",{target_batch:batchId}),
    lifecycleQuery,
  ]) : [{data:[],error:null},{data:[],error:null},{data:[],error:null},{data:[],error:null}];
  const rows=(daily??[]) as Daily[],recon=(checks??[]) as Reconciliation[],financial=context.membership.role!=="worker";
  const opening=rows[0]?.opening_birds??0,closing=rows.at(-1)?.closing_birds??0;
  const total=(field:"deaths"|"transfers_out"|"feed_consumed_kg"|"completed_health_activities")=>rows.reduce((sum,row)=>sum+Number(row[field]??0),0);
  const costTotal=rows.some(r=>r.attributable_cost!==null)?rows.reduce((sum,r)=>sum+Number(r.attributable_cost??0),0):null;
  const countLabel=`${rows.filter(r=>r.daily_record_status==="submitted").length} of ${rows.length} daily records submitted`;
  const weeks=new Map<string,Daily[]>();for(const row of rows){const date=new Date(`${row.report_date}T00:00:00Z`),day=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-day);const key=date.toISOString().slice(0,10);weeks.set(key,[...(weeks.get(key)??[]),row]);}
  const lifecycle=(lifecycleData?.[0]??null) as Lifecycle|null;
  const qs=new URLSearchParams({batch:batchId??"",from,to,asOf,status});
  return <div className="pb-8">
    <Link href="/rearing" className="text-sm font-semibold text-emerald-800">← Back to rearing</Link>
    <header className="mt-4 border-b border-stone-200 pb-5"><p className="text-sm font-semibold text-emerald-800">DOC &amp; pullet management</p><h1 className="mt-1 text-3xl font-bold">Rearing reports</h1><p className="mt-2 max-w-3xl text-stone-600">Daily and weekly activity reconciled from the batch population, feed, health, and cost sources. Missing daily records are shown as missing, not as zero activity.</p></header>
    <form className="mt-5 grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-6" method="get">
      <label className="text-sm font-medium">Batch<select name="batch" defaultValue={batchId??""} className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 bg-white px-3">{batches?.map(b=><option key={b.id} value={b.id}>{b.batch_code}</option>)}</select></label>
      <label className="text-sm font-medium">From<input name="from" type="date" defaultValue={from} className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3"/></label>
      <label className="text-sm font-medium">To<input name="to" type="date" defaultValue={to} className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3"/></label>
      <label className="text-sm font-medium">Lifecycle as of<input name="asOf" type="date" defaultValue={asOf} className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3"/></label>
      <label className="text-sm font-medium">Portfolio status<select name="status" defaultValue={status} className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 bg-white px-3"><option value="">All statuses</option>{["active","partially_transferred","transferred","closed","depleted"].map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label>
      <button className="mt-auto min-h-11 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white">Run report</button>
    </form>
    {!batchId?<Card className="mt-5 p-8 text-center"><h2 className="font-semibold">No rearing batches yet</h2><p className="mt-2 text-sm text-stone-600">Create a batch before running its operational report.</p></Card>:<>
      <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Selected period totals">
        <Kpi label="Opening birds" value={opening.toLocaleString()}/><Kpi label="Deaths in period" value={total("deaths").toLocaleString()}/><Kpi label="Transfers out" value={total("transfers_out").toLocaleString()}/><Kpi label="Closing birds" value={closing.toLocaleString()}/><Kpi label="Actual feed consumed" value={`${total("feed_consumed_kg").toFixed(3)} kg`}/>
      </section>
      <section className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Health activities completed" value={total("completed_health_activities").toLocaleString()}/><Kpi label="Daily completeness" value={countLabel}/>{financial&&<Kpi label="Attributable new cost in period" value={costTotal===null?"Unavailable":money(costTotal,context.farm.currency)}/>}<Kpi label="Period" value={`${formatFarmDate(from)} – ${formatFarmDate(to)}`}/></section>
      {(dailyError||checkError||costCheckError||lifecycleError)&&<Card className="mt-5 border-red-200 bg-red-50 p-4 text-sm text-red-900">The report could not load all ledger data. Try again; no totals should be treated as reconciled.</Card>}
      {lifecycleNotYetArrived&&<Card className="mt-5 border-sky-200 bg-sky-50 p-5"><h2 className="font-semibold text-sky-950">Batch not yet arrived</h2><p className="mt-1 text-sm text-sky-900">{selectedBatch?.batch_code} had not arrived by {formatFarmDate(asOf)}. Lifecycle population, feed, and cost are not applicable for this cutoff; no zero balances are inferred. The selected-period activity report above is still evaluated separately.</p></Card>}
      {lifecycle&&<Card className="mt-5 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Batch lifecycle snapshot</h2><p className="mt-1 text-sm text-stone-500">Population and cost use the same effective-date cutoff: {formatFarmDate(lifecycle.as_of_date)}. Transfers are not mortality.</p></div><Link className="text-sm font-semibold text-emerald-800" href={`/reports/export?type=rearing_lifecycle&batch=${batchId}&from=${asOf}&to=${asOf}`}>Export lifecycle CSV ↗</Link></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Initial chicks" value={Number(lifecycle.initial_birds).toLocaleString()}/><Kpi label="Cumulative rearing deaths" value={Number(lifecycle.deaths).toLocaleString()}/><Kpi label="Transferred to layers" value={Number(lifecycle.transferred_birds).toLocaleString()}/><Kpi label="Remaining in rearing" value={Number(lifecycle.remaining_birds).toLocaleString()}/><Kpi label="Rearing survival" value={lifecycle.survival_rate===null?"Unavailable":`${Number(lifecycle.survival_rate).toFixed(2)}%`}/><Kpi label="Lifetime feed through cutoff" value={`${Number(lifecycle.feed_consumed_kg).toFixed(3)} kg`}/>{financial&&<><Kpi label="Historical accumulated cost" value={lifecycle.historical_cost===null||!lifecycle.cost_complete?"Incomplete source":money(Number(lifecycle.historical_cost),context.farm.currency)}/><Kpi label="Transferred / remaining cost" value={lifecycle.transferred_cost===null||lifecycle.remaining_cost===null?"—":`${money(Number(lifecycle.transferred_cost),context.farm.currency)} / ${money(Number(lifecycle.remaining_cost),context.farm.currency)}`}/><Kpi label="Cost per remaining bird" value={lifecycle.cost_per_remaining_bird===null?"Not available":money(Number(lifecycle.cost_per_remaining_bird),context.farm.currency)}/></>}</div>{financial&&!lifecycle.cost_complete&&<p className="mt-3 text-sm text-amber-800">Cost source data is incomplete as of this date; the displayed cost is not verified.</p>}</Card>}
      <Card className="mt-5 overflow-hidden"><div className="border-b border-stone-100 p-5"><h2 className="font-semibold">Daily activity</h2><p className="mt-1 text-sm text-stone-500">Population equation: opening + inbound − deaths − transfers − other outbound = closing. Weekly totals are the sum of these displayed daily rows.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr>{["Date","Record","Opening","In","Deaths","Transfers","Other out","Closing","Feed kg","Health","Notes"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-stone-100">{rows.map(r=><tr key={r.report_date}><td className="whitespace-nowrap px-3 py-3">{formatFarmDate(r.report_date)}</td><td className="px-3 py-3"><span className={r.daily_record_status==="submitted"?"text-emerald-800":"text-amber-800"}>{r.daily_record_status==="submitted"?"Submitted":"Missing"}</span></td><td className="px-3 py-3">{Number(r.opening_birds).toLocaleString()}</td><td className="px-3 py-3">{Number(r.inbound_birds).toLocaleString()}</td><td className="px-3 py-3">{Number(r.deaths).toLocaleString()}</td><td className="px-3 py-3">{Number(r.transfers_out).toLocaleString()}</td><td className="px-3 py-3">{Number(r.other_outbound).toLocaleString()}</td><td className="px-3 py-3 font-semibold">{Number(r.closing_birds).toLocaleString()}</td><td className="px-3 py-3">{Number(r.feed_consumed_kg).toFixed(3)}</td><td className="px-3 py-3">{Number(r.completed_health_activities)} complete{Number(r.scheduled_health_activities)>0?` · ${r.scheduled_health_activities} scheduled`:""}</td><td className="max-w-48 truncate px-3 py-3" title={r.observations??undefined}>{r.observations||"—"}</td></tr>)}{!rows.length&&<tr><td colSpan={11} className="px-5 py-8 text-center text-stone-500">No daily report rows for this period.</td></tr>}</tbody></table></div><div className="border-t border-stone-100 px-5 py-3 text-sm text-stone-600">{rows.length?`Period reconciliation: ${opening.toLocaleString()} opening + ${rows.reduce((n,r)=>n+Number(r.inbound_birds),0).toLocaleString()} inbound − ${total("deaths").toLocaleString()} deaths − ${total("transfers_out").toLocaleString()} transfers − ${rows.reduce((n,r)=>n+Number(r.other_outbound),0).toLocaleString()} other out = ${closing.toLocaleString()} closing.`:"Choose a date range to see daily activity."}</div></Card>
      <Card className="mt-5 overflow-hidden"><div className="border-b border-stone-100 p-5"><h2 className="font-semibold">Weekly rollup</h2><p className="mt-1 text-sm text-stone-500">Weeks start Monday; partial weeks are labelled by their Monday date. Totals roll up the daily rows above.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr>{["Week of","Opening","Deaths","Transfers","Closing","Feed consumed","Daily records"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-stone-100">{Array.from(weeks.entries()).map(([week,items])=><tr key={week}><td className="px-4 py-3">{formatFarmDate(week)}</td><td className="px-4 py-3">{Number(items[0]?.opening_birds??0).toLocaleString()}</td><td className="px-4 py-3">{items.reduce((n,r)=>n+Number(r.deaths),0).toLocaleString()}</td><td className="px-4 py-3">{items.reduce((n,r)=>n+Number(r.transfers_out),0).toLocaleString()}</td><td className="px-4 py-3 font-semibold">{Number(items.at(-1)?.closing_birds??0).toLocaleString()}</td><td className="px-4 py-3">{items.reduce((n,r)=>n+Number(r.feed_consumed_kg),0).toFixed(3)} kg</td><td className="px-4 py-3">{items.filter(r=>r.daily_record_status==="submitted").length}/{items.length}</td></tr>)}</tbody></table></div></Card>
      <Card className="mt-5 overflow-hidden"><div className="border-b border-stone-100 p-5"><h2 className="font-semibold">Source reconciliation</h2><p className="mt-1 text-sm text-stone-500">Read-only checks against the authoritative batch, feed, and transfer records. No balancing entries are created.</p></div><div className="divide-y divide-stone-100">{recon.map(row=><div key={row.category} className="grid gap-1 px-5 py-4 sm:grid-cols-[1fr_auto_auto_auto]"><b className="capitalize">{row.category.replaceAll("_"," ")}</b><span className="text-sm text-stone-600">Expected {row.expected_value===null?"—":Number(row.expected_value).toLocaleString()}</span><span className="text-sm text-stone-600">Actual {row.actual_value===null?"—":Number(row.actual_value).toLocaleString()}</span><Status value={row.reconciliation_status}/></div>)}{(costChecks??[]).map((row:{category:string;reconciliation_status:string})=><div key={`source-${row.category}`} className="grid gap-1 px-5 py-4 sm:grid-cols-[1fr_auto]"><b className="capitalize">{row.category.replaceAll("_"," ")} source</b><Status value={row.reconciliation_status}/></div>)}{!recon.length&&<p className="p-5 text-sm text-stone-500">No reconciliation results are available.</p>}</div></Card>
      <Card className="mt-5 p-5"><h2 className="font-semibold">Download rearing reports</h2><p className="mt-1 text-sm text-stone-500">Exports use the selected farm, batch, date range, status, and role permissions; financial columns are omitted for Workers.</p><div className="mt-3 flex flex-wrap gap-2">{[["Rearing portfolio","rearing_portfolio"],["Daily summary","rearing_daily"],["Weekly summary","rearing_weekly"],["Mortality history","rearing_mortality"],["Feed consumption","rearing_feed"],["Health history","rearing_health"],["Batch cost breakdown","rearing_cost"],["Transfer history","rearing_transfers"],["Batch lifecycle snapshot","rearing_lifecycle"],["Reconciliation","rearing_reconciliation"]].map(([label,type])=><Link key={type} className="min-h-10 rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm font-semibold text-emerald-800 hover:bg-emerald-50" href={`/reports/export?type=${type}&${qs}`}>Export {label} ↗</Link>)}</div></Card>
      <div className="mt-4 flex flex-wrap gap-3"><Link className="min-h-10 rounded-lg border border-stone-300 bg-white px-4 py-2 text-sm font-semibold text-emerald-800" href={`/rearing/${batchId}`}>Open batch lifecycle ↗</Link></div>
    </>}
  </div>;
}
function Kpi({label,value}:{label:string;value:string}){return <Card className="p-4"><p className="text-xs font-semibold text-stone-500">{label}</p><p className="mt-2 text-xl font-bold text-stone-900">{value}</p></Card>}
function Status({value}:{value:string}){const styles=value==="RECONCILED"?"bg-emerald-50 text-emerald-800":value==="DISCREPANCY"?"bg-red-50 text-red-800":value==="INSUFFICIENT SOURCE DATA"?"bg-amber-50 text-amber-800":"bg-stone-100 text-stone-600";return <span className={`w-fit rounded-full px-2.5 py-1 text-xs font-semibold ${styles}`}>{value}</span>}
