import{NextRequest,NextResponse}from"next/server";import{getCurrentAppContext}from"@/lib/auth/context";import{createClient}from"@/lib/supabase/server";
const safe=(v:unknown)=>{let s=String(v??"");if(/^[=+\-@]/.test(s))s="'"+s;return`"${s.replaceAll('"','""')}"`};
export async function GET(req:NextRequest){const c=await getCurrentAppContext();if(!c)return new NextResponse("Unauthorized",{status:401});const q=req.nextUrl.searchParams,type=q.get("type")??"",from=q.get("from")??"",to=q.get("to")??"";if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)return new NextResponse("Invalid date range",{status:400});const financial=c.membership.role!=="worker";if(["sales","collections","expenses","cash-flow","profitability"].includes(type)&&!financial)return new NextResponse("Forbidden",{status:403});const s=await createClient();let headers:string[]=[],rows:unknown[][]=[];
if(type==="production"){const{data}=await s.from("v_production_by_grade").select("production_date,production_record_id,grade_code,grade_name,quantity_eggs").eq("farm_id",c.farm.id).gte("production_date",from).lte("production_date",to);headers=["Date","Production Record","Grade Code","Egg Grade","Good Eggs"];rows=(data??[]).map(Object.values)}
else if(type==="sales"){const{data}=await s.from("v_sales_by_grade").select("sale_date,sale_id,grade_code,grade_name,item_type,quantity,eggs_per_unit,total_eggs,price_per_unit,line_total").eq("farm_id",c.farm.id).gte("sale_date",from).lte("sale_date",to);headers=["Sale Date","Sale ID","Grade Code","Egg Grade","Unit","Quantity","Eggs Per Unit","Total Eggs","Unit Price Snapshot","Revenue"];rows=(data??[]).map(Object.values)}
else if(type==="collections"){const{data}=await s.from("v_credit_collections").select("customer_name,sale_number,sale_date,credit_days,payment_due_date,outstanding_balance,collection_status").eq("farm_id",c.farm.id).gte("sale_date",from).lte("sale_date",to);headers=["Customer","Sale Number","Sale Date","Credit Days","Payment Due Date","Outstanding","Collection Status"];rows=(data??[]).map(Object.values)}
else if(type==="eggs"){const{data}=await s.from("v_egg_inventory_ledger_by_grade").select("movement_date,grade_code,grade_name,movement_type,direction,quantity_eggs,source_type").eq("farm_id",c.farm.id).gte("movement_date",from).lte("movement_date",to);headers=["Date","Grade Code","Egg Grade","Movement","Direction","Eggs","Source"];rows=(data??[]).map(Object.values)}
else if(type==="expenses"){const{data}=await s.from("v_expense_payables").select("expense_date,expense_number,category_name,description,source_type,amount,total_paid,outstanding_balance,payment_status").eq("farm_id",c.farm.id).gte("expense_date",from).lte("expense_date",to);headers=["Date","Expense Number","Category","Description","Source","Amount","Paid","Outstanding","Status"];rows=(data??[]).map(Object.values)}
else if(type==="feed"){const{data}=await s.from("feed_inventory_movements").select("movement_date,feed_type_id,movement_type,direction,quantity_kg,unit_cost_snapshot,total_cost_snapshot").eq("farm_id",c.farm.id).gte("movement_date",from).lte("movement_date",to);headers=["Date","Feed Type ID","Movement","Direction","Quantity KG","Unit Cost","Total Cost"];rows=(data??[]).map(Object.values)}
else if(type==="health"){const select=financial?"record_date,flock_id,health_type,product_name,reason,cost,next_due_date":"record_date,flock_id,health_type,product_name,reason,next_due_date",{data}=await s.from("health_records").select(select).eq("farm_id",c.farm.id).eq("status","active").gte("record_date",from).lte("record_date",to);headers=financial?["Date","Flock ID","Type","Product","Reason","Cost","Next Due"]:["Date","Flock ID","Type","Product","Reason","Next Due"];rows=(data??[]).map(Object.values)}
else if(type==="cash-flow"){const{data}=await s.from("v_cash_ledger").select("transaction_date,description,source_type,payment_method,direction,amount,reference").eq("farm_id",c.farm.id).gte("transaction_date",from).lte("transaction_date",to);headers=["Date","Description","Source","Method","Direction","Amount","Reference"];rows=(data??[]).map(Object.values)}
else if(type==="profitability"){const{data}=await s.rpc("get_profitability_summary",{start_date:from,end_date:to});headers=["Revenue","Feed Consumption Cost","Feed Wastage Cost","Other Operating Expenses","Operating Profit","Margin %"];rows=(data??[]).map(Object.values)}else return new NextResponse("Unknown report",{status:404});
const csv="\uFEFF"+[headers,...rows].map(r=>r.map(safe).join(",")).join("\r\n");return new NextResponse(csv,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="${type}-${from}-to-${to}.csv"`}})}
