import{NextRequest,NextResponse}from"next/server";import{getCurrentAppContext}from"@/lib/auth/context";import{createClient}from"@/lib/supabase/server";
const safe=(v:unknown)=>{let s=String(v??"");if(/^[=+\-@]/.test(s))s="'"+s;return`"${s.replaceAll('"','""')}"`};
type PageResult<T>={data:T[]|null;error:{message:string}|null};
async function readAllPages<T>(fetchPage:(start:number,end:number)=>PromiseLike<PageResult<T>>){const result:T[]=[];for(let start=0;;start+=1000){const page=await fetchPage(start,start+999);if(page.error)throw new Error(page.error.message);result.push(...(page.data??[]));if((page.data??[]).length<1000)break;}return result;}
export async function GET(req:NextRequest){const c=await getCurrentAppContext();if(!c)return new NextResponse("Unauthorized",{status:401});const q=req.nextUrl.searchParams,type=q.get("type")??"",from=q.get("from")??"",to=q.get("to")??"";if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)return new NextResponse("Invalid date range",{status:400});const financial=c.membership.role!=="worker";if(["sales","bird-sales","collections","expenses","cash-flow","profitability"].includes(type)&&!financial)return new NextResponse("Forbidden",{status:403});const s=await createClient();let headers:string[]=[],rows:unknown[][]=[];
if(type==="production"){const{data}=await s.from("v_production_by_grade").select("production_date,production_record_id,grade_code,grade_name,quantity_eggs").eq("farm_id",c.farm.id).gte("production_date",from).lte("production_date",to);headers=["Date","Production Record","Grade Code","Egg Grade","Good Eggs"];rows=(data??[]).map(Object.values)}
else if(type==="sales"){const{data}=await s.from("v_sales_by_grade").select("sale_date,sale_id,grade_code,grade_name,item_type,quantity,eggs_per_unit,total_eggs,price_per_unit,line_total").eq("farm_id",c.farm.id).gte("sale_date",from).lte("sale_date",to);headers=["Sale Date","Sale ID","Grade Code","Egg Grade","Unit","Quantity","Eggs Per Unit","Total Eggs","Unit Price Snapshot","Revenue"];rows=(data??[]).map(Object.values)}
else if(type==="bird-sales"){const[{data},{data:receivables}]=await Promise.all([s.from("bird_sale_details").select("sale_id,quantity,price_per_bird,line_total,category,flocks(flock_name),sales!inner(sale_number,sale_date,status,customers(name))").eq("farm_id",c.farm.id).eq("sales.status","completed").gte("sales.sale_date",from).lte("sales.sale_date",to),s.from("v_sales_receivables").select("sale_id,total_paid,outstanding_balance,payment_due_date,payment_status").eq("farm_id",c.farm.id).gte("sale_date",from).lte("sale_date",to)]);const bySale=new Map((receivables??[]).map(r=>[r.sale_id,r]));headers=["Sale Date","Sale Number","Customer","Flock","Category","Birds Sold","Price Per Bird","Revenue","Amount Paid","Outstanding","Due Date","Payment Status"];rows=(data??[]).map(x=>{const sale=Array.isArray(x.sales)?x.sales[0]:x.sales,customer=Array.isArray(sale?.customers)?sale.customers[0]:sale?.customers,flock=Array.isArray(x.flocks)?x.flocks[0]:x.flocks,receivable=bySale.get(x.sale_id);return[sale?.sale_date,sale?.sale_number,customer?.name??"Walk-in",flock?.flock_name,x.category,x.quantity,x.price_per_bird,x.line_total,receivable?.total_paid??0,receivable?.outstanding_balance??0,receivable?.payment_due_date??"",receivable?.payment_status??""]})}
else if(type==="collections"){const{data}=await s.from("v_credit_collections").select("customer_name,sale_number,sale_date,credit_days,payment_due_date,outstanding_balance,collection_status").eq("farm_id",c.farm.id).gte("sale_date",from).lte("sale_date",to);headers=["Customer","Sale Number","Sale Date","Credit Days","Payment Due Date","Outstanding","Collection Status"];rows=(data??[]).map(Object.values)}
else if(type==="eggs"){const{data}=await s.from("v_egg_inventory_ledger_by_grade").select("movement_date,grade_code,grade_name,movement_type,direction,quantity_eggs,source_type").eq("farm_id",c.farm.id).gte("movement_date",from).lte("movement_date",to);headers=["Date","Grade Code","Egg Grade","Movement","Direction","Eggs","Source"];rows=(data??[]).map(Object.values)}
else if(type==="expenses"){const{data}=await s.from("v_expense_payables").select("expense_date,expense_number,category_name,description,source_type,amount,total_paid,outstanding_balance,payment_status").eq("farm_id",c.farm.id).gte("expense_date",from).lte("expense_date",to);headers=["Date","Expense Number","Category","Description","Source","Amount","Paid","Outstanding","Status"];rows=(data??[]).map(Object.values)}
else if(type==="feed"){const{data}=await s.from("feed_inventory_movements").select("movement_date,feed_type_id,movement_type,direction,quantity_kg,unit_cost_snapshot,total_cost_snapshot").eq("farm_id",c.farm.id).gte("movement_date",from).lte("movement_date",to);headers=["Date","Feed Type ID","Movement","Direction","Quantity KG","Unit Cost","Total Cost"];rows=(data??[]).map(Object.values)}
else if(type==="health"){const select=financial?"record_date,flock_id,health_type,product_name,reason,cost,next_due_date":"record_date,flock_id,health_type,product_name,reason,next_due_date",{data}=await s.from("health_records").select(select).eq("farm_id",c.farm.id).eq("status","active").gte("record_date",from).lte("record_date",to);headers=financial?["Date","Flock ID","Type","Product","Reason","Cost","Next Due"]:["Date","Flock ID","Type","Product","Reason","Next Due"];rows=(data??[]).map(Object.values)}
else if(type==="cash-flow"){const{data}=await s.from("v_cash_ledger").select("transaction_date,description,source_type,payment_method,direction,amount,reference").eq("farm_id",c.farm.id).gte("transaction_date",from).lte("transaction_date",to);headers=["Date","Description","Source","Method","Direction","Amount","Reference"];rows=(data??[]).map(Object.values)}
else if(type==="profitability"){const{data}=await s.rpc("get_profitability_summary",{start_date:from,end_date:to});headers=["Revenue","Feed Consumption Cost","Feed Wastage Cost","Other Operating Expenses","Operating Profit","Margin %"];rows=(data??[]).map(Object.values)}
else if(type==="rearing_daily"||type==="rearing_reconciliation"){
  const batch=q.get("batch")??"";
  if(!/^[0-9a-f-]{36}$/i.test(batch))return new NextResponse("A valid rearing batch is required",{status:400});
  if(type==="rearing_daily"){
    const{data,error}=await s.rpc("get_rearing_daily_report",{target_batch:batch,target_from:from,target_to:to});
    if(error)return new NextResponse("Unable to generate rearing report",{status:400});
    type DailyExport={report_date:string;opening_birds:number;inbound_birds:number;deaths:number;transfers_out:number;other_outbound:number;closing_birds:number;daily_record_status:string;observations:string|null;feed_consumed_kg:number;feed_cost:number|null;feed_products:unknown;completed_health_activities:number;scheduled_health_activities:number;attributable_cost:number|null};
    headers=financial?["Date","Opening Birds","Inbound","Deaths","Transfers Out","Other Outbound","Closing Birds","Daily Record","Observations","Feed KG","Feed Cost","Feed Products","Health Completed","Health Scheduled","Attributable Cost"]:["Date","Opening Birds","Inbound","Deaths","Transfers Out","Other Outbound","Closing Birds","Daily Record","Observations","Feed KG","Feed Products","Health Completed","Health Scheduled"];
    rows=((data??[]) as DailyExport[]).map(x=>financial?[x.report_date,x.opening_birds,x.inbound_birds,x.deaths,x.transfers_out,x.other_outbound,x.closing_birds,x.daily_record_status,x.observations,x.feed_consumed_kg,x.feed_cost,JSON.stringify(x.feed_products),x.completed_health_activities,x.scheduled_health_activities,x.attributable_cost]:[x.report_date,x.opening_birds,x.inbound_birds,x.deaths,x.transfers_out,x.other_outbound,x.closing_birds,x.daily_record_status,x.observations,x.feed_consumed_kg,JSON.stringify(x.feed_products),x.completed_health_activities,x.scheduled_health_activities]);
  }else{
    const{data,error}=await s.rpc("get_rearing_reconciliation",{target_batch:batch});
    if(error)return new NextResponse("Unable to generate rearing reconciliation",{status:400});
    type ReconciliationExport={category:string;expected_value:number|null;actual_value:number|null;difference:number|null;reconciliation_status:string;source_references:unknown};
    headers=["Category","Expected","Actual","Difference","Status","Source References"];
    rows=((data??[]) as ReconciliationExport[]).map(x=>[x.category,x.expected_value,x.actual_value,x.difference,x.reconciliation_status,JSON.stringify(x.source_references)]);
  }
}
else if(type.startsWith("rearing_")){
  const batch=q.get("batch")??"",status=q.get("status")??"";
  const date=/^\d{4}-\d{2}-\d{2}$/;
  const fail=(message:string)=>new NextResponse(message,{status:400});
  try{
    if(type==="rearing_portfolio"){
      const asOf=q.get("asOf")??to;if(!date.test(asOf)||asOf>to)return fail("Choose a portfolio as-of date on or before the report end date");
      const batches=await readAllPages<{id:string;batch_code:string;breed_or_strain:string;arrival_date:string;hatch_date:string|null;initial_quantity:number;stage:string;status:string;created_by:string}>((start,end)=>s.from("rearing_batches").select("id,batch_code,breed_or_strain,arrival_date,hatch_date,initial_quantity,stage,status,created_by").eq("farm_id",c.farm.id).order("arrival_date").order("id").range(start,end));
      const selected=batches.filter(b=>!status||b.status===status);
      headers=financial?["Batch","Breed / Strain","Arrival Date","As Of","Age Basis","Age Days","Initial Chicks","Current Rearing Birds","Cumulative Deaths","Transferred Birds","Rearing Survival %","Feed KG","Historical Cost","Transferred Cost","Remaining Cost","Stage","Status"]:["Batch","Breed / Strain","Arrival Date","As Of","Age Basis","Age Days","Initial Chicks","Current Rearing Birds","Cumulative Deaths","Transferred Birds","Rearing Survival %","Feed KG","Stage","Status"];
      for(const b of selected){if(b.arrival_date>asOf)continue;const{data:snapshot,error}=await s.rpc("get_rearing_lifecycle_as_of",{target_batch:b.id,target_date:asOf});if(error)throw new Error("Unable to load portfolio source records");const x=(snapshot??[])[0] as Record<string,unknown>|undefined;if(!x)continue;const ageBasis=b.hatch_date??b.arrival_date,ageDays=Math.floor((Date.parse(`${asOf}T00:00:00Z`)-Date.parse(`${ageBasis}T00:00:00Z`))/86400000),common=[b.batch_code,b.breed_or_strain,b.arrival_date,asOf,b.hatch_date?"Age from hatch":"Days since arrival",ageDays,x.initial_birds,x.remaining_birds,x.deaths,x.transferred_birds,x.survival_rate,x.feed_consumed_kg];rows.push(financial?[...common,x.historical_cost,x.transferred_cost,x.remaining_cost,b.stage,b.status]:[...common,b.stage,b.status]);}
    }else{
      if(!/^[0-9a-f-]{36}$/i.test(batch))return fail("A valid rearing batch is required");
      const{data:batchRow,error:batchError}=await s.from("rearing_batches").select("id,batch_code,farm_id,arrival_date").eq("id",batch).eq("farm_id",c.farm.id).maybeSingle();
      if(batchError||!batchRow)return new NextResponse("Rearing batch not found",{status:404});
      if(type==="rearing_lifecycle"||type==="rearing_cost"){
        const asOf=q.get("asOf")??from;if(!date.test(asOf)||asOf>to)return fail("Choose a lifecycle as-of date on or before the report end date");if(asOf<batchRow.arrival_date)return fail(`Batch ${batchRow.batch_code} had not arrived by ${asOf}; no lifecycle snapshot is available for that date.`);
        const{data,error}=await s.rpc("get_rearing_lifecycle_as_of",{target_batch:batch,target_date:asOf});if(error)return fail("Unable to generate lifecycle snapshot");
        const x=(data??[])[0] as Record<string,unknown>|undefined;if(!x)return fail("Lifecycle snapshot unavailable");
        if(type==="rearing_lifecycle"){headers=["Batch","As Of","Initial Birds","Deaths","Transferred Birds","Remaining Birds","Survival %","Feed KG","Cost Complete"];if(financial)headers.push("Feed Cost","Acquisition Cost","Health Cost","Other Direct Cost","Historical Cost","Transferred Cost","Remaining Cost","Cost Per Remaining Bird");rows=[[batchRow.batch_code,asOf,x.initial_birds,x.deaths,x.transferred_birds,x.remaining_birds,x.survival_rate,x.feed_consumed_kg,x.cost_complete,...(financial?[x.feed_cost,x.acquisition_cost,x.health_cost,x.other_direct_cost,x.historical_cost,x.transferred_cost,x.remaining_cost,x.cost_per_remaining_bird]:[])]];}
        else{headers=["Cost Category","Amount","As Of","Cost Source Status"];if(financial){for(const[label,key]of [["DOC Acquisition","acquisition_cost"],["Feed Consumed","feed_cost"],["Health","health_cost"],["Other Direct","other_direct_cost"],["Historical Accumulated","historical_cost"],["Transferred","transferred_cost"],["Remaining","remaining_cost"]])rows.push([label,x[key],asOf,x.cost_complete?"complete":"incomplete"]);}}
      }else if(type==="rearing_weekly"){
        if(!date.test(from)||!date.test(to)||to<from||Date.parse(`${to}T00:00:00Z`)-Date.parse(`${from}T00:00:00Z`)>365*86400000)return fail("Choose a valid range up to 366 days");
        const{data:reportData,error:reportError}=await s.rpc("get_rearing_daily_report",{target_batch:batch,target_from:from,target_to:to});if(reportError)return fail("Unable to generate rearing activity report");
        type DailyRow={report_date:string;opening_birds:number;inbound_birds:number;deaths:number;transfers_out:number;other_outbound:number;closing_birds:number;daily_record_status:string;observations:string|null;feed_consumed_kg:number;feed_cost:number|null;feed_products:unknown;completed_health_activities:number;scheduled_health_activities:number;attributable_cost:number|null};const data=(reportData??[]) as DailyRow[];
        headers=financial?["Week Of (Monday)","Opening Birds","Deaths","Transfers Out","Other Outbound","Closing Birds","Feed KG","Health Completed","Daily Records","Daily Records Submitted","New Cost"]:["Week Of (Monday)","Opening Birds","Deaths","Transfers Out","Other Outbound","Closing Birds","Feed KG","Health Completed","Daily Records","Daily Records Submitted"];const weeks=new Map<string,DailyRow[]>();for(const row of data){const d=new Date(`${row.report_date}T00:00:00Z`),offset=(d.getUTCDay()+6)%7;d.setUTCDate(d.getUTCDate()-offset);const key=d.toISOString().slice(0,10);weeks.set(key,[...(weeks.get(key)??[]),row]);}rows=Array.from(weeks,([week,items])=>{const totals={deaths:0,transfers:0,outbound:0,feed:0,health:0,cost:0,submitted:0};for(const i of items){totals.deaths+=Number(i.deaths);totals.transfers+=Number(i.transfers_out);totals.outbound+=Number(i.other_outbound);totals.feed+=Number(i.feed_consumed_kg);totals.health+=Number(i.completed_health_activities);totals.cost+=Number(i.attributable_cost??0);if(i.daily_record_status==="submitted")totals.submitted++;}return financial?[week,items[0]?.opening_birds??0,totals.deaths,totals.transfers,totals.outbound,items.at(-1)?.closing_birds??0,totals.feed,totals.health,items.length,totals.submitted,totals.cost]:[week,items[0]?.opening_birds??0,totals.deaths,totals.transfers,totals.outbound,items.at(-1)?.closing_birds??0,totals.feed,totals.health,items.length,totals.submitted];});
      }else if(type==="rearing_mortality"){
        const data=await readAllPages<{movement_date:string;movement_type:string;direction:string;quantity:number;notes:string|null;created_at:string;created_by:string}>((start,end)=>s.from("rearing_movements").select("movement_date,movement_type,direction,quantity,notes,created_at,created_by").eq("farm_id",c.farm.id).eq("rearing_batch_id",batch).in("movement_type",["death","reversal"]).gte("movement_date",from).lte("movement_date",to).order("movement_date").range(start,end));headers=["Date","Movement","Direction","Birds","Notes","Recorded At","Recorded By"];rows=data.map(x=>Object.values(x));
      }else if(type==="rearing_feed"){
        const feed=await readAllPages<{id:string;feed_type_id:string;movement_id:string;consumption_date:string;quantity_kg:number;active:boolean;created_by:string}>((start,end)=>s.from("rearing_feed_consumptions").select("id,feed_type_id,movement_id,consumption_date,quantity_kg,active,created_by").eq("farm_id",c.farm.id).eq("rearing_batch_id",batch).gte("consumption_date",from).lte("consumption_date",to).order("consumption_date").range(start,end));const ids=[...new Set(feed.map(x=>x.feed_type_id))],moves=[...new Set(feed.map(x=>x.movement_id))];const[{data:products,error:productError},{data:ledger,error:ledgerError}]=await Promise.all([ids.length?s.from("feed_types").select("id,name").eq("farm_id",c.farm.id).in("id",ids):Promise.resolve({data:[],error:null}),financial&&moves.length?s.from("feed_inventory_movements").select("id,unit_cost_snapshot,total_cost_snapshot").eq("farm_id",c.farm.id).in("id",moves):Promise.resolve({data:[],error:null})]);if(productError||ledgerError)throw new Error("Unable to load feed source details");const productMap=new Map((products??[]).map(x=>[x.id,x.name])),costMap=new Map((ledger??[]).map(x=>[x.id,x]));headers=financial?["Date","Feed Product","Quantity KG","Unit Cost Snapshot","Total Cost Snapshot","Active","Recorded By"]:["Date","Feed Product","Quantity KG","Active","Recorded By"];rows=feed.map(x=>financial?[x.consumption_date,productMap.get(x.feed_type_id)??x.feed_type_id,x.quantity_kg,costMap.get(x.movement_id)?.unit_cost_snapshot,costMap.get(x.movement_id)?.total_cost_snapshot,x.active,x.created_by]:[x.consumption_date,productMap.get(x.feed_type_id)??x.feed_type_id,x.quantity_kg,x.active,x.created_by]);
      }else if(type==="rearing_health"){
        let data:Record<string,unknown>[]=[];if(financial){data=await readAllPages<Record<string,unknown>>((start,end)=>s.from("health_records").select("record_date,health_type,product_name,quantity,quantity_unit,dose,reason,notes,cost,next_due_date,created_by").eq("farm_id",c.farm.id).eq("rearing_batch_id",batch).eq("status","active").gte("record_date",from).lte("record_date",to).order("record_date").range(start,end));headers=["Date","Activity","Product","Quantity","Unit","Dose","Reason","Notes","Cost","Next Due","Recorded By"];}else{data=await readAllPages<Record<string,unknown>>((start,end)=>s.from("health_records").select("record_date,health_type,product_name,quantity,quantity_unit,dose,reason,notes,next_due_date").eq("farm_id",c.farm.id).eq("rearing_batch_id",batch).eq("status","active").gte("record_date",from).lte("record_date",to).order("record_date").range(start,end));headers=["Date","Activity","Product","Quantity","Unit","Dose","Reason","Notes","Next Due"];}rows=data.map(Object.values);
      }else if(type==="rearing_transfers"){
        const{data,error}=await s.rpc("get_rearing_transfer_history",{target_batch:batch});if(error)return fail("Unable to generate transfer history");type TransferRow={id:string;transfer_date:string;quantity:number;destination_flock_name:string;status:string;total_cost_transferred:number|null;unit_cost_snapshot:number|null;created_by:string;created_at:string};const dataRows=((data??[]) as TransferRow[]).filter(x=>x.transfer_date>=from&&x.transfer_date<=to);headers=financial?["Transfer Reference","Date","Destination Flock","Birds","Status","Unit Cost Snapshot","Transferred Cost","Recorded By","Recorded At"]:["Transfer Reference","Date","Destination Flock","Birds","Status","Recorded By","Recorded At"];rows=dataRows.map(x=>financial?[x.id,x.transfer_date,x.destination_flock_name,x.quantity,x.status,x.unit_cost_snapshot,x.total_cost_transferred,x.created_by,x.created_at]:[x.id,x.transfer_date,x.destination_flock_name,x.quantity,x.status,x.created_by,x.created_at]);
      }else return new NextResponse("Unknown rearing report",{status:404});
    }
  }catch{return fail("Unable to generate rearing export from authorized source records");}
}
else return new NextResponse("Unknown report",{status:404});
const csv="\uFEFF"+[headers,...rows].map(r=>r.map(safe).join(",")).join("\r\n");return new NextResponse(csv,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="${type}-${from}-to-${to}.csv"`}})}
