import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { Card } from "@/components/ui/card";

type FarmSummary = { farm_id: string; farm_name: string; owner_name: string; owner_email: string; account_status: string; onboarding_percentage: number; plan_name: string | null; user_count: number; created_at: string };

export default async function PlatformFarms({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; onboarding?: string }> }) {
  const query = await searchParams, supabase = await createClient();
  const { data } = await supabase.rpc("platform_get_farm_summaries", { target_search: query.q?.trim() || null, target_account_status: query.status || null, target_plan_id: null, target_onboarding_status: query.onboarding || null });
  const farms = (data ?? []) as FarmSummary[];
  return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Customer farms</h1><p className="mt-2 text-stone-600">Account-level information only. Farm operational data remains private.</p></div><Link href="/platform/farms/new" className="inline-flex min-h-11 items-center rounded-xl bg-emerald-800 px-4 font-semibold text-white">Create farm</Link></div><form className="mt-6 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-3"><label className="text-sm font-medium">Search<input name="q" defaultValue={query.q} className="mt-2 min-h-11 w-full rounded-xl border px-3" placeholder="Farm, owner, email, phone" /></label><label className="text-sm font-medium">Account status<select name="status" defaultValue={query.status ?? ""} className="mt-2 min-h-11 w-full rounded-xl border bg-white px-3"><option value="">All statuses</option>{["invited","onboarding","active","suspended","closed"].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><div className="flex items-end"><button className="min-h-11 rounded-xl border px-4 text-sm font-semibold">Apply filters</button></div></form><Card className="mt-6 overflow-hidden"><div className="hidden grid-cols-[1.5fr_1.2fr_1fr_1fr_.7fr] gap-3 border-b bg-stone-50 p-4 text-xs font-semibold uppercase tracking-wide text-stone-500 md:grid"><span>Farm</span><span>Owner</span><span>Status</span><span>Plan</span><span>Users</span></div>{farms.map((farm) => <Link key={farm.farm_id} href={`/platform/farms/${farm.farm_id}`} className="grid gap-2 border-b p-4 hover:bg-lime-50 md:grid-cols-[1.5fr_1.2fr_1fr_1fr_.7fr] md:items-center md:gap-3"><div><p className="font-semibold">{farm.farm_name}</p><p className="text-sm text-stone-500">{new Date(farm.created_at).toLocaleDateString()}</p></div><div><p className="text-sm">{farm.owner_name}</p><p className="text-sm text-stone-500">{farm.owner_email}</p></div><span className="capitalize text-sm">{farm.account_status} · {farm.onboarding_percentage}%</span><span className="text-sm">{farm.plan_name ?? "—"}</span><span className="text-sm">{farm.user_count}</span></Link>)}{!farms.length && <div className="p-8 text-sm text-stone-600">No customer farms match these filters.</div>}</Card></div>;
}
