import Link from "next/link";
import { Card } from "@/components/ui/card";
import { InvitationActions, MemberActions } from "@/components/forms/user-management";
import { requireRole } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
export const metadata={title:"Users"};
export default async function UsersPage(){const c=await requireRole(["admin"]),s=await createClient();const[{data:members},{data:invites}]=await Promise.all([s.from("farm_members").select("id,role,active,user_id,profiles!farm_members_user_id_fkey(full_name,email)").eq("farm_id",c.farm.id).order("created_at"),s.from("farm_invitations").select("id,email,role,status,last_sent_at,created_at").eq("farm_id",c.farm.id).order("created_at",{ascending:false})]);return <div><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Farm users</h1><p className="mt-2 text-stone-600">Manage access to {c.farm.name}.</p></div><Link href="/settings/users/invite" className="inline-flex min-h-11 items-center rounded-lg bg-emerald-700 px-4 font-semibold text-white">Invite User</Link></div>
<h2 className="mt-8 text-xl font-semibold">Active members</h2><div className="mt-3 space-y-3">{members?.map(m=>{const p=Array.isArray(m.profiles)?m.profiles[0]:m.profiles;return <Card key={m.id} className="grid gap-4 p-5 lg:grid-cols-[1.5fr_1fr_2fr] lg:items-center"><div><p className="font-semibold">{p?.full_name||"Name not provided"}</p><p className="text-sm text-stone-600">{p?.email}</p><p className="mt-1 text-sm">Status: {m.active?"Active":"Inactive"}</p></div><span className="capitalize">{m.role}</span><MemberActions id={m.id} role={m.role} active={m.active}/></Card>})}{(members?.length??0)<=1&&<Card className="p-6 text-center text-stone-600">No additional farm users have been added yet. Invite managers or workers to help manage the farm.</Card>}</div>
<h2 className="mt-8 text-xl font-semibold">Invitations</h2><div className="mt-3 space-y-3">{invites?.map(i=><Card key={i.id} className="grid gap-4 p-5 lg:grid-cols-[1.5fr_1fr_1fr_1.5fr] lg:items-center"><div><p className="font-medium">{i.email}</p><p className="text-xs text-stone-500">Sent {new Date(i.last_sent_at).toISOString().slice(0,10)}</p></div><span className="capitalize">{i.role}</span><span>{i.status==="pending"?"Invitation Pending":i.status==="accepted"?"Accepted":"Invitation Revoked"}</span>{i.status==="pending"?<InvitationActions id={i.id}/>:<span/>}</Card>)}{!invites?.length&&<Card className="p-6 text-center text-stone-500">No invitations yet.</Card>}</div></div>}
