/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { BookOpenCheck, FlaskConical, Plus, Settings2 } from "lucide-react";
import { FeedRecipeForm } from "@/components/forms/raw-material-forms";
import { Card } from "@/components/ui/card";
import { requireAppContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";

export default async function FeedSetup() {
  const context = await requireAppContext(); const supabase = await createClient();
  const [{ data: feedData }, { data: materialData }, { data: recipeData }] = await Promise.all([supabase.from("feed_types").select("id,name").eq("farm_id", context.farm.id).eq("active", true).order("name"), supabase.from("raw_materials").select("id,name").eq("farm_id", context.farm.id).eq("is_active", true).order("name"), supabase.from("feed_recipes").select("id,effective_from,effective_to,status,feed_types(name)").eq("farm_id", context.farm.id).order("effective_from", { ascending: false })]);
  const feeds = feedData ?? [], materials = materialData ?? [], recipes = recipeData ?? [];
  return <section aria-labelledby="setup-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-stone-200/90 pb-6"><div className="max-w-xl"><p className="text-sm font-semibold tracking-[0.08em] text-emerald-800">Feed operations</p><h1 id="setup-heading" className="mt-2 text-4xl font-bold tracking-[-0.04em] text-stone-900 sm:text-5xl">Feed Setup</h1><p className="mt-3 leading-7 text-stone-600">Define a 100kg material recipe for each finished feed type. Recipes are effective-dated so historical batches remain traceable.</p></div><Link href="/feed/make" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900 hover:border-emerald-300 hover:bg-emerald-100"><FlaskConical size={18}/>Make feed</Link></header>
    <section className="mt-6 grid gap-4 sm:grid-cols-3"><SetupMetric icon={BookOpenCheck} label="Active feed types" value={feeds.length.toLocaleString()} detail="Available for formulation"/><SetupMetric icon={Settings2} label="Raw materials" value={materials.length.toLocaleString()} detail="Available recipe ingredients"/><SetupMetric icon={FlaskConical} label="Recipe versions" value={recipes.length.toLocaleString()} detail="Historical formulations retained"/></section>
    <section className="mt-8 grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold tracking-[-0.02em]">Recipe history</h2><p className="mt-1 text-sm text-stone-500">Previously configured feed formulations.</p></div><BookOpenCheck className="text-emerald-700" size={20}/></div><div className="mt-5 space-y-3">{recipes.map((recipe: any) => <div key={recipe.id} className="rounded-xl border border-stone-100 bg-stone-50/70 p-4"><div className="flex justify-between gap-3"><p className="font-bold text-stone-900">{recipe.feed_types?.name}</p><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-800">{recipe.status}</span></div><p className="mt-2 text-sm text-stone-500">Effective {recipe.effective_from}{recipe.effective_to ? ` to ${recipe.effective_to}` : " onward"}</p></div>)}{!recipes.length && <div className="rounded-xl border border-dashed border-stone-200 p-5 text-center"><p className="font-semibold">No Feed Setup has been configured</p><p className="mt-2 text-sm text-stone-500">Start with the feed your farm makes most often.</p></div>}</div></Card>
      <Card className="p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><Plus size={20}/></span><div><h2 className="text-xl font-bold tracking-[-0.02em]">Create Feed Setup</h2><p className="mt-1 text-sm text-stone-500">Build one valid formula on a 100kg basis.</p></div></div>{(!feeds.length || !materials.length) ? <div className="mt-6 rounded-xl bg-stone-50 p-5"><p className="font-semibold">You need finished feed types and raw materials first.</p><p className="mt-2 text-sm text-stone-500">Add the building blocks, then return to set up your feed formulation.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/feed/types/new" className="text-sm font-semibold text-emerald-800 underline decoration-emerald-300 underline-offset-4">Add feed type</Link><Link href="/feed/materials/new" className="text-sm font-semibold text-emerald-800 underline decoration-emerald-300 underline-offset-4">Add raw material</Link></div></div> : <div className="mt-6"><FeedRecipeForm feeds={feeds} materials={materials} today={new Date().toISOString().slice(0, 10)}/></div>}</Card></section></section>;
}

function SetupMetric({ icon: Icon, label, value, detail }: { icon: typeof BookOpenCheck; label: string; value: string; detail: string }) { return <Card className="p-5"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><Icon size={19}/></span><p className="text-sm font-semibold text-stone-500">{label}</p></div><p className="data-number mt-5 text-2xl font-bold tracking-[-0.035em] text-stone-900">{value}</p><p className="mt-2 text-sm text-stone-500">{detail}</p></Card>; }
