"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3, Bird, CircleDollarSign, Egg, HeartPulse, LayoutDashboard, Menu, NotebookPen, Receipt, Settings, ShoppingCart, UserRound, Users, X, LogOut, Wheat } from "lucide-react";
import { logoutAction } from "@/app/actions/auth";
import { cn } from "@/lib/utils";
import type { AppContext } from "@/types/domain";

export function AppShell({ context, children }: { context: AppContext; children: React.ReactNode }) {
  const [open, setOpen] = useState(false); const pathname = usePathname(); const admin = context.membership.role === "admin";
  const commercial = context.membership.role !== "worker";
  const links = [{ href: "/dashboard", label: "Dashboard", icon: LayoutDashboard }, { href: "/production", label: "Daily Production", icon: NotebookPen }, { href: "/flocks", label: "Flocks", icon: Bird }, { href: "/eggs", label: "Eggs", icon: Egg }, {href:"/feed",label:"Feed",icon:Wheat},{href:"/health",label:"Health",icon:HeartPulse}, ...(commercial ? [{ href: "/sales", label: "Sales", icon: ShoppingCart }, { href: "/customers", label: "Customers", icon: UserRound },{href:"/expenses",label:"Expenses",icon:Receipt},{href:"/cash-flow",label:"Cash flow",icon:CircleDollarSign}] : []), {href:"/reports",label:"Reports",icon:BarChart3}, ...(admin ? [{ href: "/settings", label: "Settings", icon: Settings }, { href: "/settings/users", label: "Users", icon: Users }] : [])];
  const nav = <><div className="flex h-16 items-center gap-3 px-5"><div className="grid size-9 place-items-center rounded-xl bg-emerald-700 font-bold text-white">P</div><div><p className="text-xs text-stone-500">Poultry Farm</p><p className="max-w-40 truncate font-semibold text-stone-900">{context.farm.name}</p></div></div><nav className="flex-1 space-y-1 overflow-y-auto p-3" aria-label="Main navigation">{links.map(({ href, label, icon: Icon }) => <Link key={href} onClick={() => setOpen(false)} href={href} className={cn("flex min-h-11 items-center gap-3 rounded-lg px-3 text-sm font-medium", pathname === href || pathname.startsWith(`${href}/`) ? "bg-emerald-50 text-emerald-800" : "text-stone-600 hover:bg-stone-100")}><Icon size={19} />{label}</Link>)}</nav><form action={logoutAction} className="border-t border-stone-200 p-3"><button className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-sm font-medium text-stone-600 hover:bg-stone-100"><LogOut size={19} />Sign out</button></form></>;
  return <div className="min-h-screen bg-stone-50"><aside className="fixed inset-y-0 left-0 hidden w-64 flex-col border-r border-stone-200 bg-white lg:flex">{nav}</aside>{open && <div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close menu" className="absolute inset-0 bg-stone-950/30" onClick={() => setOpen(false)} /><aside className="relative flex h-full w-72 flex-col bg-white shadow-xl"><button aria-label="Close menu" onClick={() => setOpen(false)} className="absolute right-3 top-3 grid size-10 place-items-center rounded-lg hover:bg-stone-100"><X /></button>{nav}</aside></div>}<div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-stone-200 bg-white/95 px-4 backdrop-blur sm:px-6"><button onClick={() => setOpen(true)} aria-label="Open navigation" className="grid size-11 place-items-center rounded-lg hover:bg-stone-100 lg:hidden"><Menu /></button><div className="ml-auto text-right"><p className="text-sm font-semibold text-stone-900">{context.profile?.full_name || context.user.email}</p><p className="text-xs capitalize text-stone-500">{context.membership.role}</p></div></header><main className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8">{children}</main></div></div>;
}
