import Link from "next/link";
import { Plus, Search } from "lucide-react";
import { requireAppContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { farmToday } from "@/lib/farm-date";
import { Card } from "@/components/ui/card";
import { ChickenIcon } from "@/components/ui/chicken-icon";
import { Pagination, pageWindow } from "@/components/ui/pagination";

export const metadata = { title: "Rearing batches" };
type SearchParams = { q?: string; stage?: string; status?: string; page?: string };
const stages: Record<string,string> = { brooding:"Brooding", growing:"Growing", ready_for_transfer:"Ready for Transfer" };
function ageLabel(from: string, today: string, hasHatchDate: boolean) {
  const days = Math.max(0, Math.floor((Date.parse(`${today}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / 86400000));
  return hasHatchDate ? `${days} days · ${Math.floor(days / 7)} wk ${days % 7} d` : `${days} days since arrival`;
}

export default async function RearingPage({ searchParams }: { searchParams: Promise<SearchParams> }) {
  const context = await requireAppContext(), params = await searchParams, window = pageWindow(params.page), supabase = await createClient(), today = farmToday(context.farm.timezone), filterStatus = params.status ?? "active";
  let query = supabase.from("v_rearing_population").select("*").eq("farm_id",context.farm.id).order("arrival_date",{ascending:false}).order("batch_id").range(window.from,window.to);
  const term = params.q?.replace(/[^a-zA-Z0-9 _-]/g,"").trim().slice(0,60);
  if (term) query = query.or(`batch_code.ilike.%${term}%,breed_or_strain.ilike.%${term}%`);
  if (params.stage && stages[params.stage]) query = query.eq("stage",params.stage);
  if (filterStatus === "active") query = query.in("status",["active","partially_transferred"]);
  else if (filterStatus === "partially_transferred" || filterStatus === "transferred" || filterStatus === "closed") query = query.eq("status",filterStatus);
  const [{data:rows},{data:summary}] = await Promise.all([query,supabase.from("v_rearing_portfolio_summary").select("*").eq("farm_id",context.farm.id).maybeSingle()]);
  const rowIds=(rows??[]).map(row=>row.batch_id);
  const {data:transferRows}=rowIds.length?await supabase.from("rearing_movements").select("rearing_batch_id,movement_type,quantity").eq("farm_id",context.farm.id).in("rearing_batch_id",rowIds).in("movement_type",["transfer_out","transfer_reversal"]):{data:[]};
  const transferCounts=new Map<string,number>();for(const movement of transferRows??[])transferCounts.set(movement.rearing_batch_id,(transferCounts.get(movement.rearing_batch_id)??0)+(movement.movement_type==="transfer_out"?1:-1)*Number(movement.quantity));
  const canManage = context.membership.role !== "worker";
  return <section aria-labelledby="rearing-title">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-stone-200 pb-6"><div><p className="text-sm font-semibold tracking-wide text-emerald-800">Farm operations · DOC &amp; pullets</p><h1 id="rearing-title" className="mt-2 text-4xl font-bold tracking-tight text-stone-950">Rearing</h1><p className="mt-2 max-w-2xl text-stone-600">Track each chick batch through brooding and pullet development. Rearing birds are separate from layer flocks.</p></div><div className="flex flex-wrap gap-2"><Link href="/rearing/reports" className="inline-flex min-h-11 items-center justify-center rounded-xl border border-stone-300 bg-white px-4 text-sm font-semibold text-emerald-800">Reports &amp; reconciliation</Link>{canManage&&<Link href="/rearing/new" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white"><Plus size={18}/>Create batch</Link>}</div></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Rearing summary">{[["Active batches",summary?.active_batches??0],["Initial chicks",summary?.initial_chicks??0],["Current rearing birds",summary?.current_birds??0],["Cumulative mortality",summary?.cumulative_deaths??0],["Ready for transfer",summary?.ready_for_transfer??0]].map(([label,value])=><Card key={String(label)} className="p-4 sm:p-5"><p className="text-sm text-stone-500">{label}</p><p className="data-number mt-2 text-2xl font-bold text-stone-900">{Number(value).toLocaleString()}</p></Card>)}</section>
    <form className="mt-6 grid gap-3 rounded-2xl border border-stone-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_auto]" role="search"><label className="text-sm font-semibold">Search batches<InputSearch name="q" defaultValue={params.q} placeholder="Batch code or breed"/></label><label className="text-sm font-semibold">Stage<select name="stage" defaultValue={params.stage??""} className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 bg-white px-3"><option value="">All stages</option>{Object.entries(stages).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="text-sm font-semibold">Status<select name="status" defaultValue={filterStatus} className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 bg-white px-3"><option value="active">Active</option><option value="partially_transferred">Partially transferred</option><option value="transferred">Transferred</option><option value="closed">Closed</option><option value="all">All batches</option></select></label><button className="mt-auto inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-stone-300 px-4 text-sm font-semibold text-stone-700 hover:bg-stone-50"><Search size={16}/>Filter</button></form>
    <div className="mt-5 grid gap-3">{rows?.map((batch)=>{const initial=Number(batch.initial_quantity),current=Number(batch.current_birds),deaths=Number(batch.cumulative_deaths),transferred=transferCounts.get(batch.batch_id)??0,survived=current+transferred,survival=initial?Math.min(100,survived/initial*100):0,date=batch.hatch_date??batch.arrival_date;return <Link key={batch.batch_id} href={`/rearing/${batch.batch_id}`} className="group"><Card className="grid gap-4 p-5 transition group-hover:border-emerald-300 group-hover:shadow-md sm:grid-cols-[minmax(12rem,1.5fr)_repeat(5,minmax(7rem,1fr))] sm:items-center"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-lime-100"><ChickenIcon size={42}/></span><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-800">{stages[batch.stage]??batch.stage} · {batch.status}</p><h2 className="mt-1 truncate text-lg font-bold">{batch.batch_code}</h2><p className="text-sm text-stone-500">{batch.breed_or_strain}</p></div></div><Metric label="Age" value={ageLabel(date,today,!!batch.hatch_date)}/><Metric label="Initial chicks" value={initial.toLocaleString()}/><Metric label="Current birds" value={current.toLocaleString()} strong/><Metric label="Transferred" value={transferred.toLocaleString()}/><Metric label="Deaths · rearing survival" value={`${deaths.toLocaleString()} · ${survival.toFixed(1)}%`}/></Card></Link>})}</div>
    {!rows?.length&&<Card className="mt-5 p-8 text-center sm:p-12"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-lime-100"><ChickenIcon size={48}/></span><h2 className="mt-4 text-lg font-bold">{term||params.stage||params.status==="closed"?"No batches match these filters":"No rearing batches yet"}</h2><p className="mx-auto mt-2 max-w-md text-sm text-stone-600">{term||params.stage||params.status==="closed"?"Try changing the search or filters.":"Create your first DOC batch to begin tracking chicks."}</p>{canManage&&<Link href="/rearing/new" className="mt-5 inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white"><Plus size={17}/>Create your first batch</Link>}</Card>}
    <Pagination page={window.page} hasMore={(rows?.length??0)===50} base="/rearing" params={params}/>
    <p className="mt-5 text-xs leading-5 text-stone-500">Age uses elapsed calendar days from the hatch date when known; otherwise it shows days since arrival. One week is seven elapsed days. “Ready for Transfer” is an operational designation only.</p>
  </section>;
}
function Metric({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div><p className="text-xs font-semibold text-stone-500">{label}</p><p className={`mt-1 text-sm font-bold ${strong?"text-emerald-800":"text-stone-800"}`}>{value}</p></div>}
function InputSearch(props: React.InputHTMLAttributes<HTMLInputElement>){return <input {...props} className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 bg-white px-3 text-sm outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100"/>}
