/* eslint-disable @next/next/no-html-link-for-pages */
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { money } from "@/lib/format";
import { createClient } from "@/lib/supabase/server";

type Payment = { id: string; subscription_id: string; amount: number | string; currency: string; payment_method: string; payment_reference: string | null; paid_at: string; status: string };
type Subscription = { subscription_id: string; farm_name: string; plan_name: string };
export default async function PlatformPayments() { const supabase = await createClient(); const [{ data: paymentsData }, { data: subscriptionsData }] = await Promise.all([supabase.from("subscription_payments").select("id,subscription_id,amount,currency,payment_method,payment_reference,paid_at,status").order("paid_at", { ascending: false }), supabase.rpc("platform_get_subscription_summaries")]); const subscriptions = new Map(((subscriptionsData ?? []) as Subscription[]).map((subscription) => [subscription.subscription_id, subscription])); const payments = (paymentsData ?? []) as Payment[]; return <div><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-emerald-800">Platform finance</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Subscription payments</h1><p className="mt-2 text-stone-600">Money received by HabFarms. These records never affect a customer farm’s cash flow or profitability.</p></div><a href="/api/platform/export/payments" className="inline-flex min-h-11 items-center rounded-xl border px-4 text-sm font-semibold">Export CSV</a></div><Card className="mt-7 overflow-hidden"><div className="hidden grid-cols-[.8fr_1.2fr_1fr_.8fr_1fr] gap-4 border-b bg-stone-50 px-5 py-4 text-xs font-semibold uppercase tracking-wide text-stone-500 md:grid"><span>Date</span><span>Farm</span><span>Amount</span><span>Method</span><span>Reference / status</span></div>{payments.map((payment) => { const subscription = subscriptions.get(payment.subscription_id); return <Link key={payment.id} href={`/platform/subscriptions/${payment.subscription_id}`} className="grid gap-2 border-b px-5 py-4 transition hover:bg-lime-50 md:grid-cols-[.8fr_1.2fr_1fr_.8fr_1fr] md:items-center md:gap-4"><p className="text-sm">{payment.paid_at}</p><div><p className="font-semibold">{subscription?.farm_name ?? "Customer farm"}</p><p className="text-sm text-stone-500">{subscription?.plan_name ?? "Subscription"}</p></div><p className="font-semibold">{money(payment.amount, payment.currency)}</p><p className="capitalize text-sm">{payment.payment_method.replace("_", " ")}</p><div><p className="text-sm">{payment.payment_reference || "—"}</p><p className={`text-xs font-semibold capitalize ${payment.status === "voided" ? "text-red-700" : "text-emerald-800"}`}>{payment.status}</p></div></Link>; })}{!payments.length && <p className="p-8 text-sm text-stone-600">No subscription payments have been recorded.</p>}</Card></div>; }
