import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, Bird } from "lucide-react";
import { requireAppContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { farmToday, formatFarmDate } from "@/lib/farm-date";
import { money } from "@/lib/format";
import { Card } from "@/components/ui/card";
import { BirdMovementForm } from "@/components/forms/bird-movement-form";
import { HenDayTargetForm } from "@/components/forms/hen-day-target-form";

export default async function FlockDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params, context = await requireAppContext(), supabase = await createClient(), today = farmToday(context.farm.timezone);
  const [{ data: flock }, { data: status }, { data: movements }, { data: latest }, { data: targets }, { data: performance }, { data: origins }] = await Promise.all([
    supabase.from("flocks").select("*").eq("id", id).eq("farm_id", context.farm.id).maybeSingle(),
    supabase.from("v_current_flock_status").select("*").eq("flock_id", id).eq("farm_id", context.farm.id).maybeSingle(),
    supabase.from("bird_movements").select("id,movement_date,movement_type,quantity,direction,notes").eq("farm_id", context.farm.id).eq("flock_id", id).order("movement_date", { ascending: false }).limit(8),
    supabase.from("v_daily_production_metrics").select("production_date,eggs_collected,hen_day_percentage").eq("farm_id", context.farm.id).eq("flock_id", id).order("production_date", { ascending: false }).limit(1).maybeSingle(),
    supabase.from("flock_hen_day_targets").select("*").eq("farm_id", context.farm.id).eq("flock_id", id).order("effective_from", { ascending: false }),
    supabase.rpc("get_hen_day_target_summary", { start_date: today, end_date: today, target_flock: id }),
    supabase.rpc("get_flock_rearing_lineage", { target_flock: id }),
  ]);
  if (!flock || !status) notFound();
  const manage = context.membership.role !== "worker", financial = context.membership.role !== "worker";
  const current = targets?.find(x => x.effective_to === null), target = Array.isArray(performance) ? performance[0] : performance;
  return <div className="pb-8">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-medium capitalize text-emerald-700">{flock.status} flock</p><h1 className="mt-1 text-3xl font-bold">{flock.flock_name}</h1><p className="mt-2 text-stone-500">{flock.batch_reference || "No batch reference"}</p></div><div className="flex gap-2">{flock.status === "active" && <Link href={`/production/new?flock=${id}`} className="rounded-lg bg-emerald-700 px-4 py-3 text-sm font-semibold text-white">Record production</Link>}{manage && <Link href={`/flocks/${id}/edit`} className="rounded-lg border border-stone-300 bg-white px-4 py-3 text-sm font-semibold">Edit flock</Link>}</div></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-4">{[["Current live", status.current_live_birds], ["Initial birds", flock.initial_birds], ["Started", formatFarmDate(flock.start_date)], ["House / pen", flock.house_pen || "—"]].map(([label, value]) => <Card key={String(label)} className="p-5"><p className="text-xs text-stone-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></Card>)}</div>
    <div className="mt-7 grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="text-lg font-semibold">Latest production</h2>{latest ? <div className="mt-5 grid grid-cols-3 gap-3"><div><p className="text-xs text-stone-500">Date</p><p className="mt-1 font-medium">{formatFarmDate(latest.production_date)}</p></div><div><p className="text-xs text-stone-500">Eggs</p><p className="mt-1 font-medium">{latest.eggs_collected}</p></div><div><p className="text-xs text-stone-500">Hen-Day</p><p className="mt-1 font-medium">{latest.hen_day_percentage ?? "—"}%</p></div></div> : <p className="mt-4 text-sm text-stone-500">No production recorded.</p>}</Card>
      <Card className="p-6"><h2 className="text-lg font-semibold">Production target</h2><p className="mt-1 text-sm text-stone-500">{current ? `${current.target_percentage}% from ${formatFarmDate(current.effective_from)}` : "No Hen-Day target is configured."}</p>{target?.target_hen_day_percentage != null && <p className={`mt-4 rounded-xl p-3 text-sm ${target.status === "below_target" ? "bg-amber-50 text-amber-900" : "bg-emerald-50 text-emerald-900"}`}>Today: {Number(target.actual_hen_day_percentage).toFixed(2)}% actual vs {Number(target.target_hen_day_percentage).toFixed(2)}% target · {Number(target.variance_points).toFixed(2)} pts</p>}{manage && <HenDayTargetForm flockId={id} today={today}/>}</Card>
      {manage && <Card className="p-6"><h2 className="text-lg font-semibold">Add bird movement</h2><p className="mt-1 text-sm text-stone-500">Every population change is recorded in the ledger.</p><div className="mt-5"><BirdMovementForm flockId={id} today={today} currentLiveBirds={status.current_live_birds}/></div></Card>}
    </div>
    <Card className="mt-7 overflow-hidden"><div className="border-b border-stone-200 p-5"><h2 className="font-semibold">Origins & rearing history</h2><p className="mt-1 text-sm text-stone-500">Internally reared birds remain linked to their original DOC batch. Directly acquired birds are not relabelled.</p></div>{origins?.map((origin:{transfer_id:string;source_batch_id:string;batch_code:string;transfer_date:string;quantity:number;transferred_cost:number|null;status:string})=><div key={origin.transfer_id} className="flex flex-wrap items-center justify-between gap-3 border-b border-stone-100 px-5 py-4"><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-lg bg-lime-100 text-emerald-800"><Bird size={18}/></span><div><Link href={`/rearing/${origin.source_batch_id}`} className="font-semibold text-emerald-800 underline underline-offset-2">{origin.batch_code}<ArrowRight size={13} className="ml-1 inline"/></Link><p className="mt-1 text-sm text-stone-500">{formatFarmDate(origin.transfer_date)} · {Number(origin.quantity).toLocaleString()} birds · {origin.status}</p></div></div><div className="flex items-center gap-3">{financial&&origin.transferred_cost!=null&&<span className="text-sm font-semibold">{money(Number(origin.transferred_cost),context.farm.currency)}</span>}<Link href={`/rearing/transfers/${origin.transfer_id}`} className="text-sm font-semibold text-emerald-800">Transfer record ↗</Link></div></div>)}{!origins?.length&&<p className="p-5 text-sm text-stone-500">No rearing-batch transfers have been recorded into this flock.</p>}</Card>
    <Card className="mt-7 overflow-hidden"><div className="border-b border-stone-200 p-5"><h2 className="font-semibold">Target history</h2></div>{targets?.map(x => <div key={x.id} className="grid gap-3 border-b border-stone-100 px-5 py-4"><p className="font-medium">{x.target_percentage}% · {formatFarmDate(x.effective_from)} to {x.effective_to ? formatFarmDate(x.effective_to) : "ongoing"}</p></div>)}{!targets?.length && <p className="p-6 text-sm text-stone-500">No target history yet.</p>}</Card>
    <Card className="mt-7 overflow-hidden"><div className="border-b border-stone-200 p-5"><h2 className="font-semibold">Recent bird movements</h2></div>{movements?.map(m => <div key={m.id} className="grid grid-cols-[1fr_auto] gap-3 border-b border-stone-100 px-5 py-4"><div><p className="font-medium capitalize">{m.movement_type.replaceAll("_", " ")}</p><p className="text-sm text-stone-500">{formatFarmDate(m.movement_date)}{m.notes ? ` · ${m.notes}` : ""}</p></div><p className={`font-semibold ${m.direction === "IN" ? "text-emerald-700" : "text-red-700"}`}>{m.direction === "IN" ? "+" : "−"}{m.quantity}</p></div>)}{!movements?.length && <p className="p-6 text-sm text-stone-500">No movements after the initial population.</p>}</Card>
  </div>;
}
