import Link from "next/link";
import { requireRole } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { Card } from "@/components/ui/card";

const PAGE_SIZE=50;
export default async function AuditPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const context=await requireRole(["admin"]),params=await searchParams,supabase=await createClient(),page=Math.max(1,Number(params.page)||1),from=(page-1)*PAGE_SIZE;
  let query=supabase.from("audit_logs").select("id,event_time,actor_user_id,action,entity_type,entity_id,summary,metadata,profiles!audit_logs_actor_user_id_fkey(full_name)",{count:"exact"}).eq("farm_id",context.farm.id).order("event_time",{ascending:false}).order("id",{ascending:false}).range(from,from+PAGE_SIZE-1);
  if(params.from)query=query.gte("event_time",`${params.from}T00:00:00Z`);if(params.to)query=query.lte("event_time",`${params.to}T23:59:59.999Z`);if(params.actor)query=query.eq("actor_user_id",params.actor);if(params.action)query=query.ilike("action",`%${params.action}%`);if(params.entity)query=query.eq("entity_type",params.entity);
  const[{data,count},{data:actors}]=await Promise.all([query,supabase.from("farm_members").select("user_id,profiles!farm_members_user_id_fkey(full_name)").eq("farm_id",context.farm.id).eq("active",true)]),pages=Math.max(1,Math.ceil((count??0)/PAGE_SIZE));
  const href=(target:number)=>`/settings/audit?${new URLSearchParams({...Object.fromEntries(Object.entries(params).filter(([key,value])=>key!=="page"&&value)),page:String(target)}).toString()}`;
  return <div><h1 className="text-3xl font-bold">Audit trail</h1><p className="mt-2 text-stone-600">Append-only history of important farm mutations. Times are recorded in UTC.</p><form className="mt-6 grid gap-3 rounded-xl border bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><label className="text-sm">From<input type="date" name="from" defaultValue={params.from} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label><label className="text-sm">To<input type="date" name="to" defaultValue={params.to} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label><label className="text-sm">Actor<select name="actor" defaultValue={params.actor??""} className="mt-1 min-h-11 w-full rounded-lg border px-3"><option value="">All actors</option>{actors?.map(actor=>{const profile=Array.isArray(actor.profiles)?actor.profiles[0]:actor.profiles;return <option key={actor.user_id} value={actor.user_id}>{profile?.full_name??"Unknown user"}</option>})}</select></label><label className="text-sm">Action<input name="action" defaultValue={params.action} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label><button className="min-h-11 self-end rounded-lg bg-emerald-700 px-4 font-semibold text-white">Filter</button></form><Card className="mt-6 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-stone-100"><tr>{["Date/time","Actor","Action","Entity","Summary"].map(label=><th scope="col" className="p-3" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{data?.map(row=>{const profile=Array.isArray(row.profiles)?row.profiles[0]:row.profiles;return <tr key={row.id}><td className="p-3 whitespace-nowrap">{new Date(row.event_time).toISOString().replace("T"," ").slice(0,19)} UTC</td><td className="p-3">{profile?.full_name??"System"}</td><td className="p-3 font-medium">{row.action}</td><td className="p-3">{row.entity_type}</td><td className="p-3">{row.summary}</td></tr>})}</tbody></table></div>{!data?.length&&<p className="p-8 text-center text-stone-500">No audit events match these filters.</p>}</Card><nav aria-label="Audit pagination" className="mt-5 flex items-center justify-between"><Link aria-disabled={page===1} href={page===1?href(1):href(page-1)} className="rounded-lg border bg-white px-4 py-3 aria-disabled:opacity-50">Previous</Link><span className="text-sm">Page {page} of {pages}</span><Link aria-disabled={page>=pages} href={page>=pages?href(pages):href(page+1)} className="rounded-lg border bg-white px-4 py-3 aria-disabled:opacity-50">Next</Link></nav></div>
}
