import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { Card } from "@/components/ui/card";
import { money } from "@/lib/format";

type Subscription = { subscription_id: string; farm_name: string; owner_name: string; plan_name: string; currency: string; billing_cycle: string; subscription_status: string; account_status: string; current_period_start: string | null; current_period_end: string | null; next_billing_date: string | null; trial_ends_at: string | null; grace_ends_at: string | null; outstanding: number | string };

export default async function PlatformSubscriptions({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const query = await searchParams, supabase = await createClient();
  const { data } = await supabase.rpc("platform_get_subscription_summaries", { target_status: query.status || null, target_plan: null, target_cycle: query.cycle || null });
  const subscriptions = (data ?? []) as Subscription[];
  return <div><div><p className="text-sm font-semibold text-emerald-800">Commercial accounts</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Subscriptions</h1><p className="mt-2 text-stone-600">Billing status and platform obligations only. Farm operating records remain private.</p></div><form className="mt-6 flex flex-wrap gap-3 rounded-2xl border bg-white p-4"><label className="text-sm font-medium">Status<select name="status" defaultValue={query.status ?? ""} className="ml-2 min-h-10 rounded-lg border bg-white px-3"><option value="">All</option>{["trialing","active","past_due","grace_period","suspended","cancelled"].map((value) => <option key={value} value={value}>{value.replace("_", " ")}</option>)}</select></label><label className="text-sm font-medium">Cycle<select name="cycle" defaultValue={query.cycle ?? ""} className="ml-2 min-h-10 rounded-lg border bg-white px-3"><option value="">All</option><option value="monthly">Monthly</option><option value="annual">Annual</option></select></label><button className="min-h-10 rounded-lg border px-4 text-sm font-semibold">Apply</button></form><Card className="mt-6 overflow-hidden"><div className="hidden grid-cols-[1.35fr_1fr_.8fr_.9fr_.9fr] gap-4 border-b bg-stone-50 px-5 py-4 text-xs font-semibold uppercase tracking-wide text-stone-500 md:grid"><span>Farm</span><span>Plan</span><span>Status</span><span>Coverage</span><span>Outstanding</span></div>{subscriptions.map((subscription) => <Link key={subscription.subscription_id} href={`/platform/subscriptions/${subscription.subscription_id}`} className="grid gap-2 border-b px-5 py-4 transition hover:bg-lime-50 md:grid-cols-[1.35fr_1fr_.8fr_.9fr_.9fr] md:items-center md:gap-4"><div><p className="font-semibold">{subscription.farm_name}</p><p className="text-sm text-stone-500">{subscription.owner_name}</p></div><p className="text-sm">{subscription.plan_name} · <span className="capitalize">{subscription.billing_cycle}</span></p><div><p className="capitalize text-sm">{subscription.subscription_status.replace("_", " ")}</p><p className="text-xs text-stone-500 capitalize">Account: {subscription.account_status}</p></div><p className="text-sm text-stone-600">{subscription.current_period_start && subscription.current_period_end ? `${subscription.current_period_start} – ${subscription.current_period_end}` : subscription.trial_ends_at ? `Trial ends ${subscription.trial_ends_at}` : "Not initialized"}</p><p className="font-semibold">{money(subscription.outstanding, subscription.currency)}</p></Link>)}{!subscriptions.length && <p className="p-8 text-sm text-stone-600">No subscriptions match these filters.</p>}</Card></div>;
}
