/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { Factory, PackageCheck, Settings2 } from "lucide-react";
import { MakeFeedForm } from "@/components/forms/raw-material-forms";
import { Card } from "@/components/ui/card";
import { requireAppContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";

export default async function MakeFeed() {
  const context = await requireAppContext(); const supabase = await createClient(); const { data: feedData } = await supabase.from("feed_types").select("id,name").eq("farm_id", context.farm.id).eq("active", true).order("name"); const feeds = feedData ?? []; const defaultFeed = feeds[0]?.id;
  const { data: recipe } = defaultFeed ? await supabase.from("feed_recipes").select("id,feed_type_id,basis_kg,feed_recipe_items(material_id,quantity_kg,raw_materials(name))").eq("farm_id", context.farm.id).eq("feed_type_id", defaultFeed).eq("status", "active").order("effective_from", { ascending: false }).limit(1).maybeSingle() : { data: null };
  const items = (recipe as any)?.feed_recipe_items?.map((item: any) => ({ material_id: item.material_id, name: item.raw_materials?.name ?? "Material", quantity_kg: item.quantity_kg })) ?? []; const { data: balanceData } = await supabase.from("raw_material_inventory_balances").select("material_id,quantity_kg").eq("farm_id", context.farm.id); const balances = balanceData ?? []; const balanceMap = Object.fromEntries(balances.map((item: any) => [item.material_id, item.quantity_kg]));
  return <section className="mx-auto max-w-5xl" aria-labelledby="make-feed-heading"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-stone-200/90 pb-6"><div className="max-w-xl"><p className="text-sm font-semibold tracking-[0.08em] text-emerald-800">Feed operations</p><h1 id="make-feed-heading" className="mt-2 text-4xl font-bold tracking-[-0.04em] text-stone-900 sm:text-5xl">Make feed</h1><p className="mt-3 leading-7 text-stone-600">Turn raw materials in stock into finished feed through one traceable production batch.</p></div><Link href="/feed/setup" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900 hover:border-emerald-300 hover:bg-emerald-100"><Settings2 size={18}/>Feed Setup</Link></header>
    <div className="mt-6 grid gap-4 sm:grid-cols-2"><Card className="p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><Factory size={19}/></span><div><p className="font-bold">Recipe-guided production</p><p className="mt-1 text-sm text-stone-500">Planned quantities scale from the active recipe batch size.</p></div></div></Card><Card className="p-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-800"><PackageCheck size={19}/></span><div><p className="font-bold">Atomic inventory posting</p><p className="mt-1 text-sm text-stone-500">Materials leave stock only when finished feed is successfully recorded.</p></div></div></Card></div>
    <Card className="mt-7 p-5 sm:p-7"><MakeFeedForm feeds={feeds} recipe={recipe ? { id: (recipe as any).id, feed_type_id: (recipe as any).feed_type_id, basis_kg: Number((recipe as any).basis_kg), items } : null} balances={balanceMap} today={new Date().toISOString().slice(0, 10)}/></Card></section>;
}
