-- Egg grading, grade inventory, effective-dated pricing, and grade-aware sales.
create table public.egg_grades(
  id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,
  system_code text not null check(system_code~'^[a-z][a-z0-9_]*$'),name text not null check(char_length(trim(name))between 2 and 80),description text,
  is_unsorted boolean not null default false,is_active boolean not null default true,sort_order integer not null default 0,
  created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),updated_at timestamptz not null default now(),updated_by uuid references public.profiles(id),
  unique(farm_id,system_code),unique(farm_id,id),constraint egg_grades_unsorted_code check(is_unsorted=(system_code='unsorted'))
);
create unique index egg_grades_one_unsorted_idx on public.egg_grades(farm_id)where is_unsorted;
create index egg_grades_farm_active_idx on public.egg_grades(farm_id,is_active,sort_order);

create function public.provision_default_egg_grades(target_farm uuid,target_actor uuid)returns void language plpgsql security definer set search_path='' as $$
begin
  insert into public.egg_grades(farm_id,system_code,name,description,is_unsorted,sort_order,created_by)
  values(target_farm,'unsorted','Unsorted','Good eggs awaiting grading',true,0,target_actor),(target_farm,'small','Small',null,false,10,target_actor),(target_farm,'medium','Medium',null,false,20,target_actor),(target_farm,'large','Large',null,false,30,target_actor)
  on conflict(farm_id,system_code)do nothing;
end;$$;
do $$declare x record;begin for x in select f.id,(select fm.user_id from public.farm_members fm where fm.farm_id=f.id and fm.role='admin'order by fm.created_at limit 1)actor from public.farms f loop if x.actor is not null then perform public.provision_default_egg_grades(x.id,x.actor);end if;end loop;end$$;
create function public.farm_default_grades_trigger()returns trigger language plpgsql security definer set search_path='' as $$begin if new.role='admin'and new.active then perform public.provision_default_egg_grades(new.farm_id,new.user_id);end if;return new;end;$$;
create trigger farm_members_default_egg_grades after insert on public.farm_members for each row execute function public.farm_default_grades_trigger();

alter table public.egg_inventory_movements add column egg_grade_id uuid;
update public.egg_inventory_movements m set egg_grade_id=g.id from public.egg_grades g where g.farm_id=m.farm_id and g.system_code='unsorted';
alter table public.egg_inventory_movements alter column egg_grade_id set not null;
alter table public.egg_inventory_movements add constraint egg_movements_grade_farm_fk foreign key(farm_id,egg_grade_id)references public.egg_grades(farm_id,id)on delete restrict;
alter table public.sale_items add column egg_grade_id uuid;
alter table public.sale_items add column egg_grade_code_snapshot text;
alter table public.sale_items add column egg_grade_name_snapshot text;
update public.sale_items i set egg_grade_id=g.id,egg_grade_code_snapshot='unsorted',egg_grade_name_snapshot='Legacy Ungraded' from public.sales s join public.egg_grades g on g.farm_id=s.farm_id and g.system_code='unsorted'where s.id=i.sale_id;
alter table public.sale_items alter column egg_grade_id set not null;
alter table public.sale_items alter column egg_grade_code_snapshot set not null;
alter table public.sale_items alter column egg_grade_name_snapshot set not null;
alter table public.sale_items add constraint sale_items_grade_fk foreign key(egg_grade_id)references public.egg_grades(id)on delete restrict;
drop index if exists public.egg_generated_source_uidx;drop index if exists public.egg_sale_source_uidx;
create unique index egg_generated_source_grade_uidx on public.egg_inventory_movements(source_type,source_id,movement_type,egg_grade_id)where source_id is not null;
create index egg_movements_farm_grade_date_idx on public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,created_at,id);
create index sale_items_sale_grade_idx on public.sale_items(sale_id,egg_grade_id);

create function public.assign_default_egg_grade()returns trigger language plpgsql security definer set search_path='' as $$
declare f uuid;g public.egg_grades;
begin
  if tg_table_name='sale_items'then select s.farm_id into f from public.sales s where s.id=new.sale_id;else f:=new.farm_id;end if;
  if new.egg_grade_id is null then select*into g from public.egg_grades where farm_id=f and system_code='unsorted';new.egg_grade_id:=g.id;end if;
  if not exists(select 1 from public.egg_grades x where x.id=new.egg_grade_id and x.farm_id=f)then raise exception'Grade does not belong to this farm'using errcode='42501';end if;
  if tg_table_name='sale_items'then select*into g from public.egg_grades where id=new.egg_grade_id;new.egg_grade_code_snapshot:=coalesce(new.egg_grade_code_snapshot,g.system_code);new.egg_grade_name_snapshot:=coalesce(new.egg_grade_name_snapshot,case when g.system_code='unsorted'then'Legacy Ungraded'else g.name end);end if;
  return new;
end;$$;
create trigger egg_movements_default_grade before insert or update of egg_grade_id,farm_id on public.egg_inventory_movements for each row execute function public.assign_default_egg_grade();
create trigger sale_items_default_grade before insert or update of egg_grade_id,sale_id on public.sale_items for each row execute function public.assign_default_egg_grade();

create table public.daily_production_grade_allocations(
 id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,production_record_id uuid not null references public.daily_production_records(id)on delete cascade,
 egg_grade_id uuid not null references public.egg_grades(id)on delete restrict,quantity_eggs integer not null check(quantity_eggs>0),created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),
 unique(production_record_id,egg_grade_id),foreign key(farm_id,egg_grade_id)references public.egg_grades(farm_id,id)
);
create index production_grade_allocations_record_idx on public.daily_production_grade_allocations(production_record_id,egg_grade_id);

create table public.egg_grading_batches(
 id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,grading_date date not null,source_grade_id uuid not null references public.egg_grades(id)on delete restrict,input_quantity_eggs integer not null check(input_quantity_eggs>0),notes text,
 status text not null default'posted'check(status in('posted','voided')),voided_at timestamptz,voided_by uuid references public.profiles(id),void_reason text,created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),
 foreign key(farm_id,source_grade_id)references public.egg_grades(farm_id,id)
);
create table public.egg_grading_allocations(
 id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,grading_batch_id uuid not null references public.egg_grading_batches(id)on delete cascade,target_grade_id uuid not null references public.egg_grades(id)on delete restrict,quantity_eggs integer not null check(quantity_eggs>0),
 unique(grading_batch_id,target_grade_id),foreign key(farm_id,target_grade_id)references public.egg_grades(farm_id,id)
);
create index grading_batches_farm_date_idx on public.egg_grading_batches(farm_id,grading_date desc,id);

create table public.egg_grade_prices(
 id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,egg_grade_id uuid not null references public.egg_grades(id)on delete restrict,effective_from date not null,
 crate_price numeric(14,2),loose_egg_price numeric(14,2),notes text,created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),
 constraint egg_grade_prices_values check((crate_price is not null or loose_egg_price is not null)and coalesce(crate_price,0)>=0 and coalesce(loose_egg_price,0)>=0),unique(farm_id,egg_grade_id,effective_from),foreign key(farm_id,egg_grade_id)references public.egg_grades(farm_id,id)
);
create index egg_grade_prices_lookup_idx on public.egg_grade_prices(farm_id,egg_grade_id,effective_from desc,created_at desc);

alter table public.egg_inventory_movements drop constraint egg_inventory_movements_movement_type_check;
alter table public.egg_inventory_movements add constraint egg_inventory_movements_movement_type_check check(movement_type in('production','grading_out','grading_in','grading_void_out','grading_void_in','sale','sale_reversal','opening_stock','adjustment','breakage','spoilage','giveaway','internal_use'));
alter table public.egg_inventory_movements drop constraint valid_egg_movement_direction;
alter table public.egg_inventory_movements add constraint valid_egg_movement_direction check((movement_type in('production','grading_in','grading_void_in','sale_reversal','opening_stock')and direction='IN')or(movement_type in('grading_out','grading_void_out','sale')and direction='OUT')or movement_type in('adjustment','breakage','spoilage','giveaway','internal_use'));

create or replace view public.v_current_egg_inventory_by_grade with(security_invoker=true)as
select g.farm_id,g.id egg_grade_id,g.system_code grade_code,g.name grade_name,coalesce(sum(case when m.direction='IN'then m.quantity_eggs else-m.quantity_eggs end),0)::bigint total_eggs,
floor(coalesce(sum(case when m.direction='IN'then m.quantity_eggs else-m.quantity_eggs end),0)/f.crate_size)::bigint full_crates,mod(coalesce(sum(case when m.direction='IN'then m.quantity_eggs else-m.quantity_eggs end),0)::bigint,f.crate_size)loose_eggs,g.is_unsorted,g.is_active,g.sort_order
from public.egg_grades g join public.farms f on f.id=g.farm_id left join public.egg_inventory_movements m on m.egg_grade_id=g.id group by g.id,f.crate_size;
create view public.v_current_egg_grade_prices with(security_invoker=true)as select g.farm_id,g.id egg_grade_id,g.system_code grade_code,g.name grade_name,p.effective_from,p.crate_price,p.loose_egg_price,p.created_at,p.created_by from public.egg_grades g left join lateral(select x.*from public.egg_grade_prices x where x.egg_grade_id=g.id and x.effective_from<=(now()at time zone(select timezone from public.farms where id=g.farm_id))::date order by x.effective_from desc,x.created_at desc limit 1)p on true;

create function public.assert_nonnegative_egg_grade_history(target_farm uuid,target_grade uuid)returns void language plpgsql security definer set search_path='' as $$declare m bigint;begin select min(balance)into m from(select sum(day_delta)over(order by movement_date)balance from(select movement_date,sum(case when direction='IN'then quantity_eggs else-quantity_eggs end)day_delta from public.egg_inventory_movements where farm_id=target_farm and egg_grade_id=target_grade group by movement_date)d)x;if coalesce(m,0)<0 then raise exception'Only available eggs in the selected grade can be used'using errcode='23514';end if;end;$$;
create or replace function public.assert_nonnegative_egg_history(target_farm uuid)returns void language plpgsql security definer set search_path='' as $$declare g uuid;begin for g in select id from public.egg_grades where farm_id=target_farm loop perform public.assert_nonnegative_egg_grade_history(target_farm,g);end loop;end;$$;

create function public.create_daily_production_graded(target_flock_id uuid,production_date date,eggs_collected integer,cracked_eggs integer,deaths integer,culls integer,feed_consumed_kg numeric,feed_type_id uuid,transport_cost numeric,other_cost numeric,notes text,grade_allocations jsonb default null)returns public.daily_production_records language plpgsql security definer set search_path='' as $$
declare r public.daily_production_records;f uuid;good integer;total integer;u uuid;a record;
begin
 r:=public.create_daily_production(target_flock_id,production_date,eggs_collected,cracked_eggs,deaths,culls,feed_consumed_kg,feed_type_id,transport_cost,other_cost,notes);f:=r.farm_id;good:=eggs_collected-cracked_eggs;
 delete from public.egg_inventory_movements where source_type='daily_production'and source_id=r.id;
 if grade_allocations is null or jsonb_array_length(grade_allocations)=0 then select id into u from public.egg_grades where farm_id=f and system_code='unsorted';if good>0 then insert into public.daily_production_grade_allocations(farm_id,production_record_id,egg_grade_id,quantity_eggs,created_by)values(f,r.id,u,good,auth.uid());insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(f,u,production_date,'production','IN',good,'daily_production',r.id,auth.uid());end if;
 else select coalesce(sum((x->>'quantity_eggs')::integer),0)into total from jsonb_array_elements(grade_allocations)x;if total<>good then raise exception'Grade allocations must equal good eggs'using errcode='23514';end if;
  for a in select (x->>'egg_grade_id')::uuid grade_id,(x->>'quantity_eggs')::integer qty from jsonb_array_elements(grade_allocations)x loop if a.qty<=0 or not exists(select 1 from public.egg_grades g where g.id=a.grade_id and g.farm_id=f and g.is_active and not g.is_unsorted)then raise exception'Invalid production grade allocation'using errcode='23514';end if;insert into public.daily_production_grade_allocations(farm_id,production_record_id,egg_grade_id,quantity_eggs,created_by)values(f,r.id,a.grade_id,a.qty,auth.uid());insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(f,a.grade_id,production_date,'production','IN',a.qty,'daily_production',r.id,auth.uid());end loop;
 end if;return r;
end;$$;

create function public.update_daily_production_graded(target_production_id uuid,eggs_collected integer,cracked_eggs integer,deaths integer,culls integer,feed_consumed_kg numeric,feed_type_id uuid,transport_cost numeric,other_cost numeric,notes text,grade_allocations jsonb default null)returns public.daily_production_records language plpgsql security definer set search_path='' as $$
declare r public.daily_production_records;f uuid;d date;good integer;total integer;u uuid;a record;
begin
 select farm_id,production_date into f,d from public.daily_production_records where id=target_production_id;r:=public.update_daily_production(target_production_id,eggs_collected,cracked_eggs,deaths,culls,feed_consumed_kg,feed_type_id,transport_cost,other_cost,notes);good:=eggs_collected-cracked_eggs;
 delete from public.egg_inventory_movements where source_type='daily_production'and source_id=target_production_id;delete from public.daily_production_grade_allocations where production_record_id=target_production_id;
 if grade_allocations is null or jsonb_array_length(grade_allocations)=0 then select id into u from public.egg_grades where farm_id=f and system_code='unsorted';if good>0 then insert into public.daily_production_grade_allocations(farm_id,production_record_id,egg_grade_id,quantity_eggs,created_by)values(f,r.id,u,good,auth.uid());insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(f,u,d,'production','IN',good,'daily_production',r.id,auth.uid());end if;
 else select coalesce(sum((x->>'quantity_eggs')::integer),0)into total from jsonb_array_elements(grade_allocations)x;if total<>good then raise exception'Grade allocations must equal good eggs'using errcode='23514';end if;for a in select (x->>'egg_grade_id')::uuid grade_id,(x->>'quantity_eggs')::integer qty from jsonb_array_elements(grade_allocations)x loop if a.qty<=0 or not exists(select 1 from public.egg_grades g where g.id=a.grade_id and g.farm_id=f and g.is_active and not g.is_unsorted)then raise exception'Invalid production grade allocation'using errcode='23514';end if;insert into public.daily_production_grade_allocations(farm_id,production_record_id,egg_grade_id,quantity_eggs,created_by)values(f,r.id,a.grade_id,a.qty,auth.uid());insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(f,a.grade_id,d,'production','IN',a.qty,'daily_production',r.id,auth.uid());end loop;end if;
 perform public.assert_nonnegative_egg_history(f);return r;
end;$$;

create or replace function public.delete_daily_production(target_production_id uuid)returns void language plpgsql security definer set search_path='' as $$
declare e public.daily_production_records;t uuid;
begin
 select*into e from public.daily_production_records where id=target_production_id for update;if e.id is null or not public.has_farm_role(e.farm_id,array['admin'])then raise exception'Admin access required'using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended(e.farm_id::text,0));
 if exists(select 1 from public.expense_payments p join public.expenses x on x.id=p.expense_id where x.source_type='daily_production'and x.source_id=e.id and x.status='active'and p.voided_at is null)then raise exception'Active expense payments must be voided first'using errcode='23514';end if;
 update public.expenses set status='voided',voided_at=now(),voided_by=auth.uid(),void_reason='Production record deleted',updated_by=auth.uid()where source_type='daily_production'and source_id=e.id and status='active';t:=e.feed_type_id;
 delete from public.bird_movements where source_type='daily_production'and source_id=e.id;delete from public.egg_inventory_movements where source_type='daily_production'and source_id=e.id;delete from public.feed_inventory_movements where source_type='daily_production'and source_id=e.id;delete from public.daily_production_records where id=e.id;
 if t is not null then perform public.recalculate_feed_ledger(e.farm_id,t);end if;perform public.assert_nonnegative_egg_history(e.farm_id);
end;$$;

create function public.post_egg_grading(grading_date date,input_quantity_eggs integer,allocations jsonb,notes text default null)returns public.egg_grading_batches language plpgsql security definer set search_path='' as $$
declare f uuid;u uuid;r public.egg_grading_batches;t integer;a record;
begin select farm_id into f from public.farm_members where user_id=auth.uid()and active order by created_at limit 1;if f is null then raise exception'Grading access denied'using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended(f::text,0));select id into u from public.egg_grades where farm_id=f and system_code='unsorted';select coalesce(sum((x->>'quantity_eggs')::integer),0)into t from jsonb_array_elements(allocations)x;if input_quantity_eggs<=0 or t<>input_quantity_eggs then raise exception'Grading outputs must equal input quantity'using errcode='23514';end if;
 insert into public.egg_grading_batches(farm_id,grading_date,source_grade_id,input_quantity_eggs,notes,created_by)values(f,grading_date,u,input_quantity_eggs,nullif(trim(notes),''),auth.uid())returning*into r;insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(f,u,grading_date,'grading_out','OUT',input_quantity_eggs,'egg_grading',r.id,auth.uid());
 for a in select (x->>'egg_grade_id')::uuid grade_id,(x->>'quantity_eggs')::integer qty from jsonb_array_elements(allocations)x loop if a.qty<=0 or not exists(select 1 from public.egg_grades g where g.id=a.grade_id and g.farm_id=f and g.is_active and not g.is_unsorted)then raise exception'Invalid grading target'using errcode='23514';end if;insert into public.egg_grading_allocations(farm_id,grading_batch_id,target_grade_id,quantity_eggs)values(f,r.id,a.grade_id,a.qty);insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(f,a.grade_id,grading_date,'grading_in','IN',a.qty,'egg_grading',r.id,auth.uid());end loop;perform public.assert_nonnegative_egg_grade_history(f,u);return r;end;$$;

create function public.void_egg_grading(target_batch uuid,reason text)returns void language plpgsql security definer set search_path='' as $$declare b public.egg_grading_batches;a record;begin select*into b from public.egg_grading_batches where id=target_batch for update;if b.id is null or b.status<>'posted'or not public.has_farm_role(b.farm_id,array['admin'])or char_length(trim(coalesce(reason,'')))<3 then raise exception'Grading void denied'using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended(b.farm_id::text,0));for a in select target_grade_id,quantity_eggs from public.egg_grading_allocations where grading_batch_id=b.id loop insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(b.farm_id,a.target_grade_id,b.grading_date,'grading_void_out','OUT',a.quantity_eggs,'egg_grading_void',b.id,auth.uid());perform public.assert_nonnegative_egg_grade_history(b.farm_id,a.target_grade_id);end loop;insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(b.farm_id,b.source_grade_id,b.grading_date,'grading_void_in','IN',b.input_quantity_eggs,'egg_grading_void',b.id,auth.uid());update public.egg_grading_batches set status='voided',voided_at=now(),voided_by=auth.uid(),void_reason=trim(reason)where id=b.id;end;$$;

create function public.set_egg_grade_price(target_grade uuid,effective_from date,crate_price numeric,loose_egg_price numeric,notes text default null)returns public.egg_grade_prices language plpgsql security definer set search_path='' as $$declare g public.egg_grades;r public.egg_grade_prices;begin select*into g from public.egg_grades where id=target_grade;if g.id is null or g.is_unsorted or not g.is_active or not public.has_farm_role(g.farm_id,array['admin','manager'])then raise exception'Price access denied'using errcode='42501';end if;if(crate_price is null and loose_egg_price is null)or coalesce(crate_price,0)<0 or coalesce(loose_egg_price,0)<0 then raise exception'Invalid egg price'using errcode='23514';end if;insert into public.egg_grade_prices(farm_id,egg_grade_id,effective_from,crate_price,loose_egg_price,notes,created_by)values(g.farm_id,g.id,effective_from,crate_price,loose_egg_price,nullif(trim(notes),''),auth.uid())returning*into r;return r;end;$$;
create function public.get_egg_grade_prices_for_date(target_date date)returns table(egg_grade_id uuid,grade_code text,grade_name text,crate_price numeric,loose_egg_price numeric,effective_from date)language sql stable security invoker set search_path='' as $$select g.id,g.system_code,g.name,p.crate_price,p.loose_egg_price,p.effective_from from public.egg_grades g left join lateral(select x.*from public.egg_grade_prices x where x.egg_grade_id=g.id and x.effective_from<=target_date order by x.effective_from desc,x.created_at desc limit 1)p on true where public.is_farm_member(g.farm_id)and g.is_active and not g.is_unsorted order by g.sort_order$$;

create function public.set_opening_egg_stock(target_grade uuid,effective_date date,quantity_eggs integer,notes text)returns public.egg_inventory_movements language plpgsql security definer set search_path='' as $$declare g public.egg_grades;r public.egg_inventory_movements;begin select*into g from public.egg_grades where id=target_grade;if g.id is null or not public.has_farm_role(g.farm_id,array['admin'])or quantity_eggs<=0 or char_length(trim(coalesce(notes,'')))<3 then raise exception'Opening stock denied'using errcode='42501';end if;if exists(select 1 from public.egg_inventory_movements where farm_id=g.farm_id and egg_grade_id=g.id)then raise exception'Opening stock already initialized for this grade'using errcode='23514';end if;insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,notes,created_by)values(g.farm_id,g.id,effective_date,'opening_stock','IN',quantity_eggs,'opening_stock',gen_random_uuid(),trim(notes),auth.uid())returning*into r;return r;end;$$;

create function public.post_graded_egg_sale(customer_id uuid,sale_date date,items jsonb,discount numeric,amount_paid numeric,payment_method text,notes text default null,credit_days integer default null)returns public.sales language plpgsql security definer set search_path='' as $$
declare f uuid;crate_size integer;subtotal numeric:=0;total numeric;eggs integer:=0;r public.sales;sn text;due_date date;i record;g public.egg_grades;
begin select fm.farm_id,fa.crate_size into f,crate_size from public.farm_members fm join public.farms fa on fa.id=fm.farm_id where fm.user_id=auth.uid()and fm.active and fm.role in('admin','manager')order by fm.created_at limit 1;if f is null then raise exception'Commercial access denied'using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended(f::text,0));if customer_id is not null and not exists(select 1 from public.customers c where c.id=customer_id and c.farm_id=f and c.active)then raise exception'Customer does not belong to this farm'using errcode='42501';end if;if jsonb_array_length(items)=0 then raise exception'Add at least one sale item'using errcode='22023';end if;
 for i in select (x->>'egg_grade_id')::uuid grade_id,x->>'unit'unit,(x->>'quantity')::integer qty,(x->>'price_per_unit')::numeric price from jsonb_array_elements(items)x loop select*into g from public.egg_grades where id=i.grade_id and farm_id=f and is_active and not is_unsorted;if g.id is null or i.unit not in('crate','loose_egg')or i.qty<=0 or i.price<0 then raise exception'Invalid graded sale item'using errcode='23514';end if;eggs:=eggs+i.qty*case when i.unit='crate'then crate_size else 1 end;subtotal:=subtotal+round(i.qty*i.price,2);end loop;
 subtotal:=round(subtotal,2);total:=subtotal-discount;if discount<0 or discount>subtotal or amount_paid<0 or amount_paid>total then raise exception'Invalid sale total or payment'using errcode='23514';end if;if customer_id is null and amount_paid<>total then raise exception'A customer is required for unpaid or partially paid sales'using errcode='23514';end if;if amount_paid<total and(credit_days is null or credit_days not between 1 and 365)then raise exception'Credit terms are required for unpaid or partially paid sales'using errcode='23514';end if;if credit_days is not null then due_date:=sale_date+credit_days;end if;
 sn:='SALE-'||to_char(sale_date,'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));insert into public.sales(farm_id,sale_number,customer_id,sale_date,subtotal,discount,total_amount,notes,credit_days,payment_due_date,created_by)values(f,sn,customer_id,sale_date,subtotal,discount,total,nullif(trim(notes),''),credit_days,due_date,auth.uid())returning*into r;
 for i in select (x->>'egg_grade_id')::uuid grade_id,x->>'unit'unit,(x->>'quantity')::integer qty,(x->>'price_per_unit')::numeric price from jsonb_array_elements(items)x loop select*into g from public.egg_grades where id=i.grade_id;insert into public.sale_items(sale_id,egg_grade_id,egg_grade_code_snapshot,egg_grade_name_snapshot,item_type,quantity,eggs_per_unit,price_per_unit,total_eggs,line_total)values(r.id,g.id,g.system_code,g.name,i.unit,i.qty,case when i.unit='crate'then crate_size else 1 end,i.price,i.qty*case when i.unit='crate'then crate_size else 1 end,round(i.qty*i.price,2));insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(f,g.id,sale_date,'sale','OUT',i.qty*case when i.unit='crate'then crate_size else 1 end,'egg_sale',r.id,auth.uid())on conflict(source_type,source_id,movement_type,egg_grade_id)where source_id is not null do update set quantity_eggs=public.egg_inventory_movements.quantity_eggs+excluded.quantity_eggs;perform public.assert_nonnegative_egg_grade_history(f,g.id);end loop;
 if amount_paid>0 then insert into public.customer_payments(farm_id,customer_id,sale_id,payment_date,amount,payment_method,created_by)values(f,customer_id,r.id,sale_date,amount_paid,payment_method,auth.uid());end if;return r;end;$$;

create function public.update_graded_egg_sale(target_sale uuid,customer_id uuid,items jsonb,discount numeric,notes text default null,credit_days integer default null)returns public.sales language plpgsql security definer set search_path='' as $$
declare s public.sales;crate_size integer;subtotal numeric:=0;total numeric;paid numeric;r public.sales;i record;g public.egg_grades;new_credit integer;new_due date;
begin select*into s from public.sales where id=target_sale for update;if s.id is null or s.status<>'completed'or not public.has_farm_role(s.farm_id,array['admin','manager'])then raise exception'Sale edit denied'using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended(s.farm_id::text,0));select crate_size into crate_size from public.farms where id=s.farm_id;if customer_id is not null and not exists(select 1 from public.customers where id=customer_id and farm_id=s.farm_id and active)then raise exception'Invalid customer'using errcode='42501';end if;
 for i in select (x->>'egg_grade_id')::uuid grade_id,x->>'unit'unit,(x->>'quantity')::integer qty,(x->>'price_per_unit')::numeric price from jsonb_array_elements(items)x loop select*into g from public.egg_grades where id=i.grade_id and farm_id=s.farm_id and is_active and not is_unsorted;if g.id is null or i.unit not in('crate','loose_egg')or i.qty<=0 or i.price<0 then raise exception'Invalid graded sale item'using errcode='23514';end if;subtotal:=subtotal+round(i.qty*i.price,2);end loop;total:=round(subtotal,2)-discount;select coalesce(sum(amount),0)into paid from public.customer_payments where sale_id=s.id and voided_at is null;if total<paid or discount<0 or discount>subtotal then raise exception'Invalid sale edit or total below active payments'using errcode='23514';end if;new_credit:=coalesce(credit_days,s.credit_days);if total>paid and(new_credit is null or new_credit not between 1 and 365)then raise exception'Credit terms are required for unpaid or partially paid sales'using errcode='23514';end if;if new_credit is not null then new_due:=s.sale_date+new_credit;end if;
 delete from public.sale_items where sale_id=s.id;delete from public.egg_inventory_movements where source_type='egg_sale'and source_id=s.id and movement_type='sale';for i in select (x->>'egg_grade_id')::uuid grade_id,x->>'unit'unit,(x->>'quantity')::integer qty,(x->>'price_per_unit')::numeric price from jsonb_array_elements(items)x loop select*into g from public.egg_grades where id=i.grade_id;insert into public.sale_items(sale_id,egg_grade_id,egg_grade_code_snapshot,egg_grade_name_snapshot,item_type,quantity,eggs_per_unit,price_per_unit,total_eggs,line_total)values(s.id,g.id,g.system_code,g.name,i.unit,i.qty,case when i.unit='crate'then crate_size else 1 end,i.price,i.qty*case when i.unit='crate'then crate_size else 1 end,round(i.qty*i.price,2));insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(s.farm_id,g.id,s.sale_date,'sale','OUT',i.qty*case when i.unit='crate'then crate_size else 1 end,'egg_sale',s.id,auth.uid())on conflict(source_type,source_id,movement_type,egg_grade_id)where source_id is not null do update set quantity_eggs=public.egg_inventory_movements.quantity_eggs+excluded.quantity_eggs;perform public.assert_nonnegative_egg_grade_history(s.farm_id,g.id);end loop;update public.sales set customer_id=$2,subtotal=round(subtotal,2),discount=$4,total_amount=total,notes=nullif(trim($5),''),credit_days=new_credit,payment_due_date=new_due,updated_by=auth.uid()where id=s.id returning*into r;return r;end;$$;

create or replace function public.void_egg_sale(target_sale uuid,reason text)returns void language plpgsql security definer set search_path='' as $$declare s public.sales;i record;begin select*into s from public.sales where id=target_sale for update;if s.id is null or s.status<>'completed'or not public.has_farm_role(s.farm_id,array['admin'])or char_length(trim(reason))<3 then raise exception'Sale void denied'using errcode='42501';end if;if exists(select 1 from public.customer_payments where sale_id=s.id and voided_at is null)then raise exception'Active payments must be voided first'using errcode='23514';end if;perform pg_advisory_xact_lock(hashtextextended(s.farm_id::text,0));update public.sales set status='voided',voided_at=now(),voided_by=auth.uid(),void_reason=trim(reason),updated_by=auth.uid()where id=s.id;for i in select egg_grade_id,sum(total_eggs)::integer eggs from public.sale_items where sale_id=s.id group by egg_grade_id loop insert into public.egg_inventory_movements(farm_id,egg_grade_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(s.farm_id,i.egg_grade_id,s.sale_date,'sale_reversal','IN',i.eggs,'egg_sale_reversal',s.id,auth.uid());end loop;end;$$;

alter table public.egg_grades enable row level security;alter table public.egg_grade_prices enable row level security;alter table public.daily_production_grade_allocations enable row level security;alter table public.egg_grading_batches enable row level security;alter table public.egg_grading_allocations enable row level security;
create policy egg_grades_member_read on public.egg_grades for select to authenticated using(public.is_farm_member(farm_id));create policy egg_prices_commercial_read on public.egg_grade_prices for select to authenticated using(public.has_farm_role(farm_id,array['admin','manager']));create policy production_grades_member_read on public.daily_production_grade_allocations for select to authenticated using(public.is_farm_member(farm_id));create policy grading_batches_member_read on public.egg_grading_batches for select to authenticated using(public.is_farm_member(farm_id));create policy grading_allocations_member_read on public.egg_grading_allocations for select to authenticated using(public.is_farm_member(farm_id));
grant select on public.egg_grades,public.daily_production_grade_allocations,public.egg_grading_batches,public.egg_grading_allocations,public.v_current_egg_inventory_by_grade to authenticated;grant select on public.egg_grade_prices,public.v_current_egg_grade_prices to authenticated;grant all on public.egg_grades,public.egg_grade_prices,public.daily_production_grade_allocations,public.egg_grading_batches,public.egg_grading_allocations to service_role;grant select on public.v_current_egg_inventory_by_grade,public.v_current_egg_grade_prices to service_role;
create trigger egg_grades_updated_at before update on public.egg_grades for each row execute function public.set_updated_at();create trigger egg_grades_audit after insert or update or delete on public.egg_grades for each row execute function public.write_business_audit();create trigger egg_prices_audit after insert on public.egg_grade_prices for each row execute function public.write_business_audit();create trigger egg_grading_audit after insert or update on public.egg_grading_batches for each row execute function public.write_business_audit();

revoke all on function public.provision_default_egg_grades(uuid,uuid),public.farm_default_grades_trigger(),public.assign_default_egg_grade(),public.assert_nonnegative_egg_grade_history(uuid,uuid),public.create_daily_production_graded(uuid,date,integer,integer,integer,integer,numeric,uuid,numeric,numeric,text,jsonb),public.update_daily_production_graded(uuid,integer,integer,integer,integer,numeric,uuid,numeric,numeric,text,jsonb),public.post_egg_grading(date,integer,jsonb,text),public.void_egg_grading(uuid,text),public.set_egg_grade_price(uuid,date,numeric,numeric,text),public.get_egg_grade_prices_for_date(date),public.set_opening_egg_stock(uuid,date,integer,text),public.post_graded_egg_sale(uuid,date,jsonb,numeric,numeric,text,text,integer),public.update_graded_egg_sale(uuid,uuid,jsonb,numeric,text,integer)from public,anon;
grant execute on function public.create_daily_production_graded(uuid,date,integer,integer,integer,integer,numeric,uuid,numeric,numeric,text,jsonb),public.update_daily_production_graded(uuid,integer,integer,integer,integer,numeric,uuid,numeric,numeric,text,jsonb),public.post_egg_grading(date,integer,jsonb,text),public.void_egg_grading(uuid,text),public.set_egg_grade_price(uuid,date,numeric,numeric,text),public.get_egg_grade_prices_for_date(date),public.set_opening_egg_stock(uuid,date,integer,text),public.post_graded_egg_sale(uuid,date,jsonb,numeric,numeric,text,text,integer),public.update_graded_egg_sale(uuid,uuid,jsonb,numeric,text,integer)to authenticated;

create view public.v_sales_by_grade with(security_invoker=true)as select s.farm_id,s.id sale_id,s.sale_date,i.egg_grade_id,i.egg_grade_code_snapshot grade_code,i.egg_grade_name_snapshot grade_name,i.item_type,i.quantity,i.eggs_per_unit,i.total_eggs,i.price_per_unit,i.line_total from public.sales s join public.sale_items i on i.sale_id=s.id where s.status='completed';
create view public.v_production_by_grade with(security_invoker=true)as select p.farm_id,p.id production_record_id,p.production_date,a.egg_grade_id,g.system_code grade_code,g.name grade_name,a.quantity_eggs from public.daily_production_records p join public.daily_production_grade_allocations a on a.production_record_id=p.id join public.egg_grades g on g.id=a.egg_grade_id;
create view public.v_egg_inventory_ledger_by_grade with(security_invoker=true)as select m.farm_id,m.movement_date,m.egg_grade_id,g.system_code grade_code,g.name grade_name,m.movement_type,m.direction,m.quantity_eggs,m.source_type,m.source_id,m.notes,m.created_at from public.egg_inventory_movements m join public.egg_grades g on g.id=m.egg_grade_id;
grant select on public.v_sales_by_grade,public.v_production_by_grade,public.v_egg_inventory_ledger_by_grade to authenticated,service_role;
