alter table public.egg_inventory_movements drop constraint valid_production_egg_direction;
alter table public.egg_inventory_movements drop constraint egg_inventory_movements_movement_type_check;
alter table public.egg_inventory_movements add constraint egg_inventory_movements_movement_type_check check(movement_type in('production','sale','sale_reversal','adjustment','breakage','spoilage','giveaway','internal_use'));
alter table public.egg_inventory_movements add constraint valid_egg_movement_direction check((movement_type='production' and direction='IN')or(movement_type='sale' and direction='OUT')or(movement_type='sale_reversal' and direction='IN')or movement_type not in('production','sale','sale_reversal'));

create table public.customers(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,name text not null check(char_length(trim(name))between 2 and 120),phone text,email text,location text,customer_type text not null default'individual' check(customer_type in('retail','wholesale','distributor','individual','other')),notes text,active boolean not null default true,created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),updated_at timestamptz not null default now(),updated_by uuid references public.profiles(id));
create table public.sales(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,sale_number text not null,customer_id uuid references public.customers(id),sale_date date not null,subtotal numeric(14,2)not null check(subtotal>=0),discount numeric(14,2)not null default 0 check(discount>=0),total_amount numeric(14,2)not null check(total_amount>=0),notes text,status text not null default'completed' check(status in('completed','voided')),voided_at timestamptz,voided_by uuid references public.profiles(id),void_reason text,created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id),updated_at timestamptz not null default now(),updated_by uuid references public.profiles(id),unique(farm_id,sale_number),check(discount<=subtotal));
create table public.sale_items(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.sales(id)on delete cascade,item_type text not null check(item_type in('crate','loose_egg')),quantity numeric not null check(quantity>0),eggs_per_unit integer not null check(eggs_per_unit>0),price_per_unit numeric(14,2)not null check(price_per_unit>=0),total_eggs integer not null check(total_eggs>0),line_total numeric(14,2)not null check(line_total>=0),created_at timestamptz not null default now());
create table public.customer_payments(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,customer_id uuid references public.customers(id),sale_id uuid not null references public.sales(id),payment_date date not null,amount numeric(14,2)not null check(amount>0),payment_method text not null check(payment_method in('cash','momo','bank_transfer','other')),reference text,notes text,voided_at timestamptz,voided_by uuid references public.profiles(id),void_reason text,created_at timestamptz not null default now(),created_by uuid not null references public.profiles(id));
create index customers_farm_active_idx on public.customers(farm_id,active);create index sales_farm_date_idx on public.sales(farm_id,sale_date desc);create index sales_customer_date_idx on public.sales(customer_id,sale_date desc);create index sale_items_sale_idx on public.sale_items(sale_id);create index payments_farm_date_idx on public.customer_payments(farm_id,payment_date desc);create index payments_sale_idx on public.customer_payments(sale_id);
create trigger customers_updated_at before update on public.customers for each row execute function public.set_updated_at();create trigger sales_updated_at before update on public.sales for each row execute function public.set_updated_at();
create unique index egg_sale_source_uidx on public.egg_inventory_movements(source_type,source_id,movement_type)where source_type='egg_sale';

create function public.assert_nonnegative_egg_history(target_farm uuid)returns void language plpgsql security definer set search_path='' as $$declare m bigint;begin select min(balance)into m from(select sum(day_delta)over(order by movement_date)balance from(select movement_date,sum(case when direction='IN'then quantity_eggs else-quantity_eggs end)day_delta from public.egg_inventory_movements where farm_id=target_farm group by movement_date)d)x;if coalesce(m,0)<0 then raise exception'Only available eggs can be sold'using errcode='23514';end if;end;$$;
create function public.create_customer(name text,phone text,email text,location text,customer_type text,notes text)returns public.customers language plpgsql security definer set search_path='' as $$declare f uuid;r public.customers;begin select farm_id into f from public.farm_members where user_id=auth.uid()and active and role in('admin','manager')order by created_at limit 1;if f is null then raise exception'Commercial access denied'using errcode='42501';end if;insert into public.customers(farm_id,name,phone,email,location,customer_type,notes,created_by)values(f,trim(name),nullif(trim(phone),''),nullif(trim(email),''),nullif(trim(location),''),customer_type,nullif(trim(notes),''),auth.uid())returning*into r;return r;end;$$;
create function public.update_customer(target_customer uuid,name text,phone text,email text,location text,customer_type text,active boolean,notes text)returns public.customers language plpgsql security definer set search_path='' as $$declare f uuid;r public.customers;begin select farm_id into f from public.customers where id=target_customer for update;if f is null or not public.has_farm_role(f,array['admin','manager'])then raise exception'Customer access denied'using errcode='42501';end if;update public.customers set name=trim(update_customer.name),phone=nullif(trim(update_customer.phone),''),email=nullif(trim(update_customer.email),''),location=nullif(trim(update_customer.location),''),customer_type=update_customer.customer_type,active=update_customer.active,notes=nullif(trim(update_customer.notes),''),updated_by=auth.uid()where id=target_customer returning*into r;return r;end;$$;

create function public.post_egg_sale(customer_id uuid,sale_date date,crate_quantity integer,crate_price numeric,loose_quantity integer,loose_price numeric,discount numeric,amount_paid numeric,payment_method text,notes text default null)returns public.sales language plpgsql security definer set search_path='' as $$declare f uuid;crate_size integer;subtotal numeric(14,2);total numeric(14,2);eggs integer;available bigint;r public.sales;sn text;begin
select fm.farm_id,fa.crate_size into f,crate_size from public.farm_members fm join public.farms fa on fa.id=fm.farm_id where fm.user_id=auth.uid()and fm.active and fm.role in('admin','manager')order by fm.created_at limit 1;if f is null then raise exception'Commercial access denied'using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended(f::text,0));
if customer_id is not null and not exists(select 1 from public.customers c where c.id=customer_id and c.farm_id=f and c.active)then raise exception'Customer does not belong to this farm'using errcode='42501';end if;if coalesce(crate_quantity,0)<0 or coalesce(loose_quantity,0)<0 or(crate_quantity=0 and loose_quantity=0)or crate_price<0 or loose_price<0 then raise exception'Invalid sale items'using errcode='22023';end if;
eggs:=coalesce(crate_quantity,0)*crate_size+coalesce(loose_quantity,0);subtotal:=round(coalesce(crate_quantity,0)*crate_price+coalesce(loose_quantity,0)*loose_price,2);if discount<0 or discount>subtotal then raise exception'Invalid discount'using errcode='22023';end if;total:=subtotal-discount;if amount_paid<0 or amount_paid>total then raise exception'Payment exceeds sale total'using errcode='23514';end if;if customer_id is null and amount_paid<>total then raise exception'A customer is required for unpaid or partially paid sales'using errcode='23514';end if;
select coalesce(sum(case when direction='IN'then quantity_eggs else-quantity_eggs end),0)into available from public.egg_inventory_movements where farm_id=f;if eggs>available then raise exception'Only % eggs are currently available',available using errcode='23514';end if;sn:='SALE-'||to_char(sale_date,'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
insert into public.sales(farm_id,sale_number,customer_id,sale_date,subtotal,discount,total_amount,notes,created_by)values(f,sn,customer_id,sale_date,subtotal,discount,total,nullif(trim(notes),''),auth.uid())returning*into r;
if crate_quantity>0 then insert into public.sale_items(sale_id,item_type,quantity,eggs_per_unit,price_per_unit,total_eggs,line_total)values(r.id,'crate',crate_quantity,crate_size,crate_price,crate_quantity*crate_size,round(crate_quantity*crate_price,2));end if;if loose_quantity>0 then insert into public.sale_items(sale_id,item_type,quantity,eggs_per_unit,price_per_unit,total_eggs,line_total)values(r.id,'loose_egg',loose_quantity,1,loose_price,loose_quantity,round(loose_quantity*loose_price,2));end if;
insert into public.egg_inventory_movements(farm_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(f,sale_date,'sale','OUT',eggs,'egg_sale',r.id,auth.uid());perform public.assert_nonnegative_egg_history(f);
if amount_paid>0 then insert into public.customer_payments(farm_id,customer_id,sale_id,payment_date,amount,payment_method,created_by)values(f,customer_id,r.id,sale_date,amount_paid,payment_method,auth.uid());end if;return r;end;$$;

create function public.record_customer_payment(target_sale uuid,payment_date date,amount numeric,payment_method text,reference text default null,notes text default null)returns public.customer_payments language plpgsql security definer set search_path='' as $$declare s public.sales;paid numeric;r public.customer_payments;begin select*into s from public.sales where id=target_sale for update;if s.id is null or s.status<>'completed'or not public.has_farm_role(s.farm_id,array['admin','manager'])then raise exception'Payment access denied'using errcode='42501';end if;select coalesce(sum(p.amount),0)into paid from public.customer_payments p where p.sale_id=s.id and p.voided_at is null;if amount<=0 or paid+amount>s.total_amount then raise exception'The payment exceeds the remaining balance'using errcode='23514';end if;insert into public.customer_payments(farm_id,customer_id,sale_id,payment_date,amount,payment_method,reference,notes,created_by)values(s.farm_id,s.customer_id,s.id,payment_date,amount,payment_method,nullif(trim(reference),''),nullif(trim(notes),''),auth.uid())returning*into r;return r;end;$$;

create function public.update_egg_sale(target_sale uuid,customer_id uuid,crate_quantity integer,crate_price numeric,loose_quantity integer,loose_price numeric,discount numeric,notes text default null)returns public.sales language plpgsql security definer set search_path='' as $$declare s public.sales;crate_size integer;subtotal numeric;total numeric;eggs integer;paid numeric;r public.sales;begin select*into s from public.sales where id=target_sale for update;if s.id is null or s.status<>'completed'or not public.has_farm_role(s.farm_id,array['admin','manager'])then raise exception'Sale edit denied'using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended(s.farm_id::text,0));if customer_id is not null and not exists(select 1 from public.customers c where c.id=customer_id and c.farm_id=s.farm_id)then raise exception'Invalid customer'using errcode='42501';end if;select coalesce(max(eggs_per_unit)filter(where item_type='crate'),(select crate_size from public.farms where id=s.farm_id))into crate_size from public.sale_items where sale_id=s.id;eggs:=crate_quantity*crate_size+loose_quantity;subtotal:=round(crate_quantity*crate_price+loose_quantity*loose_price,2);total:=subtotal-discount;select coalesce(sum(amount),0)into paid from public.customer_payments where sale_id=s.id and voided_at is null;if eggs<=0 or discount<0 or discount>subtotal or total<paid then raise exception'Invalid sale edit or total below active payments'using errcode='23514';end if;delete from public.sale_items where sale_id=s.id;if crate_quantity>0 then insert into public.sale_items(sale_id,item_type,quantity,eggs_per_unit,price_per_unit,total_eggs,line_total)values(s.id,'crate',crate_quantity,crate_size,crate_price,crate_quantity*crate_size,round(crate_quantity*crate_price,2));end if;if loose_quantity>0 then insert into public.sale_items(sale_id,item_type,quantity,eggs_per_unit,price_per_unit,total_eggs,line_total)values(s.id,'loose_egg',loose_quantity,1,loose_price,loose_quantity,round(loose_quantity*loose_price,2));end if;update public.sales set customer_id=update_egg_sale.customer_id,subtotal=update_egg_sale.subtotal,discount=update_egg_sale.discount,total_amount=total,notes=nullif(trim(update_egg_sale.notes),''),updated_by=auth.uid()where id=s.id returning*into r;update public.egg_inventory_movements set quantity_eggs=eggs where source_type='egg_sale'and source_id=s.id and movement_type='sale';perform public.assert_nonnegative_egg_history(s.farm_id);return r;end;$$;

create function public.void_customer_payment(target_payment uuid,reason text)returns void language plpgsql security definer set search_path='' as $$declare f uuid;begin select farm_id into f from public.customer_payments where id=target_payment for update;if f is null or not public.has_farm_role(f,array['admin'])or char_length(trim(reason))<3 then raise exception'Payment void denied'using errcode='42501';end if;update public.customer_payments set voided_at=now(),voided_by=auth.uid(),void_reason=trim(reason)where id=target_payment and voided_at is null;end;$$;
create function public.void_egg_sale(target_sale uuid,reason text)returns void language plpgsql security definer set search_path='' as $$declare s public.sales;eggs integer;begin select*into s from public.sales where id=target_sale for update;if s.id is null or s.status<>'completed'or not public.has_farm_role(s.farm_id,array['admin'])or char_length(trim(reason))<3 then raise exception'Sale void denied'using errcode='42501';end if;if exists(select 1 from public.customer_payments where sale_id=s.id and voided_at is null)then raise exception'Active payments must be voided first'using errcode='23514';end if;perform pg_advisory_xact_lock(hashtextextended(s.farm_id::text,0));select sum(total_eggs)into eggs from public.sale_items where sale_id=s.id;update public.sales set status='voided',voided_at=now(),voided_by=auth.uid(),void_reason=trim(reason),updated_by=auth.uid()where id=s.id;insert into public.egg_inventory_movements(farm_id,movement_date,movement_type,direction,quantity_eggs,source_type,source_id,created_by)values(s.farm_id,s.sale_date,'sale_reversal','IN',eggs,'egg_sale',s.id,auth.uid());end;$$;

create view public.v_sales_receivables with(security_invoker=true)as select s.id sale_id,s.sale_number,s.farm_id,s.customer_id,s.sale_date,s.total_amount,coalesce(sum(p.amount)filter(where p.voided_at is null),0)::numeric(14,2)total_paid,(s.total_amount-coalesce(sum(p.amount)filter(where p.voided_at is null),0))::numeric(14,2)outstanding_balance,case when coalesce(sum(p.amount)filter(where p.voided_at is null),0)=0 then'unpaid'when coalesce(sum(p.amount)filter(where p.voided_at is null),0)<s.total_amount then'partial'else'paid'end payment_status,s.status from public.sales s left join public.customer_payments p on p.sale_id=s.id group by s.id;
create view public.v_customer_balances with(security_invoker=true)as select c.id customer_id,c.farm_id,coalesce(sum(distinct s.total_amount)filter(where s.status='completed'),0)::numeric(14,2)total_sales,coalesce((select sum(p.amount)from public.customer_payments p join public.sales x on x.id=p.sale_id where p.customer_id=c.id and p.voided_at is null and x.status='completed'),0)::numeric(14,2)total_payments,(coalesce(sum(distinct s.total_amount)filter(where s.status='completed'),0)-coalesce((select sum(p.amount)from public.customer_payments p join public.sales x on x.id=p.sale_id where p.customer_id=c.id and p.voided_at is null and x.status='completed'),0))::numeric(14,2)outstanding_balance from public.customers c left join public.sales s on s.customer_id=c.id group by c.id;
create view public.v_sales_summary with(security_invoker=true)as select s.farm_id,s.sale_date,count(*)filter(where s.status='completed')sales_count,coalesce(sum((select sum(i.total_eggs)from public.sale_items i where i.sale_id=s.id))filter(where s.status='completed'),0)eggs_sold,coalesce(sum(s.total_amount)filter(where s.status='completed'),0)::numeric(14,2)sales_value,coalesce((select sum(p.amount)from public.customer_payments p where p.farm_id=s.farm_id and p.payment_date=s.sale_date and p.voided_at is null),0)::numeric(14,2)payments_received from public.sales s group by s.farm_id,s.sale_date;

alter table public.customers enable row level security;alter table public.sales enable row level security;alter table public.sale_items enable row level security;alter table public.customer_payments enable row level security;
create policy customers_read_commercial on public.customers for select to authenticated using(public.has_farm_role(farm_id,array['admin','manager']));create policy sales_read_commercial on public.sales for select to authenticated using(public.has_farm_role(farm_id,array['admin','manager']));create policy items_read_commercial on public.sale_items for select to authenticated using(exists(select 1 from public.sales s where s.id=sale_id and public.has_farm_role(s.farm_id,array['admin','manager'])));create policy payments_read_commercial on public.customer_payments for select to authenticated using(public.has_farm_role(farm_id,array['admin','manager']));
grant select on public.customers,public.sales,public.sale_items,public.customer_payments,public.v_sales_receivables,public.v_customer_balances,public.v_sales_summary to authenticated;grant all on public.customers,public.sales,public.sale_items,public.customer_payments to service_role;grant select on public.v_sales_receivables,public.v_customer_balances,public.v_sales_summary to service_role;
revoke all on function public.assert_nonnegative_egg_history(uuid)from public;revoke all on function public.create_customer(text,text,text,text,text,text)from public;grant execute on function public.create_customer(text,text,text,text,text,text)to authenticated;revoke all on function public.update_customer(uuid,text,text,text,text,text,boolean,text)from public;grant execute on function public.update_customer(uuid,text,text,text,text,text,boolean,text)to authenticated;revoke all on function public.post_egg_sale(uuid,date,integer,numeric,integer,numeric,numeric,numeric,text,text)from public;grant execute on function public.post_egg_sale(uuid,date,integer,numeric,integer,numeric,numeric,numeric,text,text)to authenticated;revoke all on function public.record_customer_payment(uuid,date,numeric,text,text,text)from public;grant execute on function public.record_customer_payment(uuid,date,numeric,text,text,text)to authenticated;revoke all on function public.update_egg_sale(uuid,uuid,integer,numeric,integer,numeric,numeric,text)from public;grant execute on function public.update_egg_sale(uuid,uuid,integer,numeric,integer,numeric,numeric,text)to authenticated;revoke all on function public.void_customer_payment(uuid,text)from public;grant execute on function public.void_customer_payment(uuid,text)to authenticated;revoke all on function public.void_egg_sale(uuid,text)from public;grant execute on function public.void_egg_sale(uuid,text)to authenticated;
