"use server";
import{revalidatePath}from"next/cache";import{createClient}from"@/lib/supabase/server";import{requireRole}from"@/lib/auth/context";import{adjustmentSchema,feedPaymentSchema,feedTypeSchema,openingSchema,purchaseSchema,supplierSchema}from"@/lib/validation/feed";import type{ActionResult}from"./auth";
const fail=(e:{message:string}):ActionResult=>({ok:false,message:e.message});
export async function saveFeedTypeAction(id:string|undefined,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=feedTypeSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=id?await s.rpc("update_feed_type",{target_feed_type:id,name:d.name,default_bag_size_kg:d.defaultBagSizeKg,active:d.active,description:d.description}):await s.rpc("create_feed_type",{name:d.name,default_bag_size_kg:d.defaultBagSizeKg,description:d.description});if(error)return fail(error);revalidatePath("/feed");revalidatePath("/feed/types");return{ok:true,message:"Feed type saved."}}
export async function saveSupplierAction(id:string|undefined,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=supplierSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=id?await s.rpc("update_supplier",{target_supplier:id,name:d.name,phone:d.phone,email:d.email,location:d.location,active:d.active,notes:d.notes}):await s.rpc("create_supplier",{name:d.name,phone:d.phone,email:d.email,location:d.location,notes:d.notes});if(error)return fail(error);revalidatePath("/feed/suppliers");return{ok:true,message:"Supplier saved."}}
export async function postFeedPurchaseAction(input:unknown):Promise<ActionResult&{id?:string}>{await requireRole(["admin","manager"]);const p=purchaseSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{data,error}=await s.rpc("post_feed_purchase",{supplier_id:d.supplierId||null,feed_type_id:d.feedTypeId,purchase_date:d.purchaseDate,bags:d.bags,bag_size_kg:d.bagSizeKg,cost_per_bag:d.costPerBag,amount_paid:d.amountPaid,payment_method:d.paymentMethod,reference:d.reference,notes:d.notes});if(error)return fail(error);const r=Array.isArray(data)?data[0]:data;revalidatePath("/feed");return{ok:true,message:"Feed purchase posted.",id:r.id}}
export async function setOpeningStockAction(input:unknown):Promise<ActionResult>{await requireRole(["admin"]);const p=openingSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("set_opening_feed_stock",{feed_type_id:d.feedTypeId,effective_date:d.effectiveDate,bags:d.bags,bag_size_kg:d.bagSizeKg,cost_per_bag:d.costPerBag,notes:d.notes});if(error)return fail(error);revalidatePath("/feed");return{ok:true,message:"Opening feed stock set."}}
export async function createFeedAdjustmentAction(input:unknown):Promise<ActionResult>{await requireRole(["admin"]);const p=adjustmentSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("create_feed_adjustment",{feed_type_id:d.feedTypeId,movement_date:d.movementDate,movement_type:d.movementType,direction:d.direction,quantity_kg:d.quantityKg,unit_cost:d.unitCost===""?null:d.unitCost,reason:d.reason,notes:d.notes});if(error)return fail(error);revalidatePath("/feed");return{ok:true,message:"Feed adjustment recorded."}}
export async function recordFeedPaymentAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=feedPaymentSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("record_feed_purchase_payment",{target_purchase:id,payment_date:d.paymentDate,amount:d.amount,payment_method:d.paymentMethod,reference:d.reference,notes:d.notes});if(error)return fail(error);revalidatePath(`/feed/purchases/${id}`);return{ok:true,message:"Payment recorded."}}
export async function updateFeedPurchaseAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=purchaseSchema.omit({feedTypeId:true,amountPaid:true,paymentMethod:true,reference:true}).safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("update_feed_purchase",{target_purchase:id,supplier_id:d.supplierId||null,purchase_date:d.purchaseDate,bags:d.bags,bag_size_kg:d.bagSizeKg,cost_per_bag:d.costPerBag,notes:d.notes});if(error)return fail(error);revalidatePath(`/feed/purchases/${id}`);revalidatePath("/feed");return{ok:true,message:"Purchase updated."}}
export async function voidFeedPurchaseAction(id:string,reason:string):Promise<ActionResult>{await requireRole(["admin"]);const s=await createClient(),{error}=await s.rpc("void_feed_purchase",{target_purchase:id,reason});if(error)return fail(error);revalidatePath(`/feed/purchases/${id}`);revalidatePath("/feed");return{ok:true,message:"Purchase voided."}}
export async function voidFeedPaymentAction(id:string,purchaseId:string,reason:string):Promise<ActionResult>{await requireRole(["admin"]);const s=await createClient(),{error}=await s.rpc("void_feed_purchase_payment",{target_payment:id,reason});if(error)return fail(error);revalidatePath(`/feed/purchases/${purchaseId}`);return{ok:true,message:"Payment voided."}}
