"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { requireAppContext, requireRole } from "@/lib/auth/context";
import { birdMovementSchema, flockSchema, flockUpdateSchema, productionSchema, productionUpdateSchema } from "@/lib/validation/operations";
import type { ActionResult } from "./auth";
function message(error: { message: string }) { const m=error.message; if(m.includes("already exists")) return "A production record already exists for this flock on this date."; if(m.includes("negative")||m.includes("available live")) return "Deaths and culls cannot exceed the available live birds."; if(m.includes("closed")) return "This flock is closed and cannot receive new production records."; if(m.includes("access")||m.includes("permission")) return "You do not have permission to complete this action."; console.error("Operational database error",error); return "We couldn't save the record. Please try again."; }
export async function createFlockAction(input: unknown): Promise<ActionResult & { id?: string }> { await requireRole(["admin","manager"]); const p=flockSchema.safeParse(input); if(!p.success)return{ok:false,message:p.error.issues[0].message}; const d=p.data,s=await createClient(); const {data,error}=await s.rpc("create_flock",{flock_name:d.flockName,batch_reference:d.batchReference,breed:d.breed,house_pen:d.housePen,start_date:d.startDate,initial_birds:d.initialBirds,age_at_arrival_weeks:d.ageAtArrivalWeeks===""||d.ageAtArrivalWeeks===undefined?null:d.ageAtArrivalWeeks,source:d.source,notes:d.notes}); if(error)return{ok:false,message:message(error)}; const row=Array.isArray(data)?data[0]:data; return{ok:true,message:"Flock created.",id:row.id}; }
export async function updateFlockAction(id:string,input:unknown):Promise<ActionResult&{id?:string}>{await requireRole(["admin","manager"]);const p=flockUpdateSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient();const{error}=await s.rpc("update_flock",{target_flock_id:id,flock_name:d.flockName,batch_reference:d.batchReference,breed:d.breed,house_pen:d.housePen,start_date:d.startDate,age_at_arrival_weeks:d.ageAtArrivalWeeks===""||d.ageAtArrivalWeeks===undefined?null:d.ageAtArrivalWeeks,source:d.source,status:d.status,notes:d.notes});if(error)return{ok:false,message:message(error)};revalidatePath(`/flocks/${id}`);return{ok:true,message:"Flock updated."};}
export async function createBirdMovementAction(input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=birdMovementSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient();const{error}=await s.rpc("create_bird_movement",{target_flock_id:d.flockId,movement_date:d.movementDate,movement_type:d.movementType,quantity:d.quantity,direction:d.direction,notes:d.notes});if(error)return{ok:false,message:message(error)};revalidatePath(`/flocks/${d.flockId}`);return{ok:true,message:"Bird movement recorded."};}
export async function createProductionAction(input:unknown):Promise<ActionResult & {id?:string}>{await requireAppContext();const p=productionSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient();const{data,error}=await s.rpc("create_daily_production_graded",{target_flock_id:d.flockId,production_date:d.productionDate,eggs_collected:d.eggsCollected,cracked_eggs:d.crackedEggs,deaths:d.deaths,culls:d.culls,feed_consumed_kg:d.feedConsumedKg,feed_type_id:d.feedTypeId||null,transport_cost:d.transportCost,other_cost:d.otherCost,notes:d.notes,grade_allocations:d.gradeMode==="graded"?d.gradeAllocations.filter(x=>x.quantityEggs>0).map(x=>({egg_grade_id:x.eggGradeId,quantity_eggs:x.quantityEggs})):null});if(error)return{ok:false,message:message(error)};const row=Array.isArray(data)?data[0]:data;revalidatePath("/eggs");return{ok:true,message:"Today's production was recorded successfully.",id:row.id};}
export async function updateProductionAction(id:string,input:unknown):Promise<ActionResult&{id?:string}>{await requireRole(["admin","manager"]);const p=productionUpdateSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient();const{error}=await s.rpc("update_daily_production_graded",{target_production_id:id,eggs_collected:d.eggsCollected,cracked_eggs:d.crackedEggs,deaths:d.deaths,culls:d.culls,feed_consumed_kg:d.feedConsumedKg,feed_type_id:d.feedTypeId||null,transport_cost:d.transportCost,other_cost:d.otherCost,notes:d.notes,grade_allocations:d.gradeMode==="graded"?d.gradeAllocations.filter(x=>x.quantityEggs>0).map(x=>({egg_grade_id:x.eggGradeId,quantity_eggs:x.quantityEggs})):null});if(error)return{ok:false,message:message(error)};revalidatePath(`/production/${id}`);revalidatePath("/eggs");return{ok:true,message:"Production record updated."};}
export async function deleteProductionAction(id:string){await requireRole(["admin"]);const s=await createClient();const{error}=await s.rpc("delete_daily_production",{target_production_id:id});if(error)throw new Error(message(error));redirect("/production");}
