"use server";
import{revalidatePath}from"next/cache";import{requireRole}from"@/lib/auth/context";import{createClient}from"@/lib/supabase/server";import{creditTermsSchema,customerSchema,paymentSchema,saleEditSchema,saleSchema}from"@/lib/validation/sales";import type{ActionResult}from"./auth";
const msg=(e:{message:string})=>{if(e.message.includes("Only")||e.message.includes("Credit terms")||e.message.includes("Credit days")||e.message.includes("Change reason"))return e.message;if(e.message.includes("customer is required"))return"A customer is required for unpaid or partially paid sales.";if(e.message.includes("remaining")||e.message.includes("exceeds"))return"The payment exceeds the remaining balance.";if(e.message.includes("payments must"))return"Void active payments before voiding this sale.";console.error("Commercial error",e);return"We couldn't save this commercial transaction."};const credit=(v:string|number|undefined)=>v===""||v===undefined?null:Number(v);
export async function createCustomerAction(input:unknown):Promise<ActionResult&{id?:string}>{await requireRole(["admin","manager"]);const p=customerSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{data,error}=await s.rpc("create_customer",{name:d.name,phone:d.phone,email:d.email??"",location:d.location,customer_type:d.customerType,notes:d.notes,default_credit_days:credit(d.defaultCreditDays)});if(error)return{ok:false,message:msg(error)};const r=Array.isArray(data)?data[0]:data;return{ok:true,message:"Customer created.",id:r.id}}
export async function updateCustomerAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=customerSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("update_customer",{target_customer:id,name:d.name,phone:d.phone,email:d.email??"",location:d.location,customer_type:d.customerType,active:d.active,notes:d.notes,default_credit_days:credit(d.defaultCreditDays)});if(error)return{ok:false,message:msg(error)};revalidatePath(`/customers/${id}`);return{ok:true,message:"Customer updated."}}
export async function postSaleAction(input:unknown):Promise<ActionResult&{id?:string}>{await requireRole(["admin","manager"]);const p=saleSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{data,error}=await s.rpc("post_graded_egg_sale",{customer_id:d.customerId||null,sale_date:d.saleDate,items:d.items.map(x=>({egg_grade_id:x.eggGradeId,unit:x.unit,quantity:x.quantity,price_per_unit:x.pricePerUnit})),discount:d.discount,amount_paid:d.amountPaid,payment_method:d.paymentMethod,notes:d.notes,credit_days:credit(d.creditDays)});if(error)return{ok:false,message:msg(error)};const r=Array.isArray(data)?data[0]:data;revalidatePath("/dashboard");revalidatePath("/collections");revalidatePath("/eggs");return{ok:true,message:"Sale recorded successfully.",id:r.id}}
export async function updateSaleAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=saleEditSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("update_graded_egg_sale",{target_sale:id,customer_id:d.customerId||null,items:d.items.map(x=>({egg_grade_id:x.eggGradeId,unit:x.unit,quantity:x.quantity,price_per_unit:x.pricePerUnit})),discount:d.discount,notes:d.notes,credit_days:credit(d.creditDays)});if(error)return{ok:false,message:msg(error)};revalidatePath(`/sales/${id}`);revalidatePath("/collections");revalidatePath("/eggs");return{ok:true,message:"Sale updated."}}
export async function updateSaleCreditTermsAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=creditTermsSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const s=await createClient(),{error}=await s.rpc("update_sale_credit_terms",{target_sale:id,new_credit_days:p.data.creditDays,new_due_date:p.data.dueDate,change_reason:p.data.reason});if(error)return{ok:false,message:msg(error)};revalidatePath(`/sales/${id}`);revalidatePath("/collections");revalidatePath("/dashboard");return{ok:true,message:"Credit terms updated."}}
export async function recordPaymentAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=paymentSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("record_customer_payment",{target_sale:id,payment_date:d.paymentDate,amount:d.amount,payment_method:d.paymentMethod,reference:d.reference,notes:d.notes});if(error)return{ok:false,message:msg(error)};revalidatePath(`/sales/${id}`);revalidatePath("/collections");revalidatePath("/dashboard");return{ok:true,message:"Payment recorded."}}
export async function voidPaymentAction(id:string,reason:string):Promise<ActionResult>{await requireRole(["admin"]);const s=await createClient(),{error}=await s.rpc("void_customer_payment",{target_payment:id,reason});if(error)return{ok:false,message:msg(error)};revalidatePath("/sales");revalidatePath("/collections");return{ok:true,message:"Payment voided."}}
export async function voidSaleAction(id:string,reason:string):Promise<ActionResult>{await requireRole(["admin"]);const s=await createClient(),{error}=await s.rpc("void_egg_sale",{target_sale:id,reason});if(error)return{ok:false,message:msg(error)};revalidatePath(`/sales/${id}`);revalidatePath("/collections");return{ok:true,message:"Sale voided and inventory restored."}}
