"use server";
import{randomUUID}from"node:crypto";import{revalidatePath}from"next/cache";import{requireRole}from"@/lib/auth/context";import{createClient}from"@/lib/supabase/server";import{birdSaleSchema,creditTermsSchema,customerSchema,paymentSchema,saleEditSchema,saleSchema}from"@/lib/validation/sales";import type{ActionResult}from"./auth";
const salesErrorMessage=(error:{message:string;code?:string})=>{
  const raw=error.message??"";
  const text=raw.toLowerCase();
  const availableEggs=raw.match(/Only\s+(\d+)\s+eggs?\s+(?:are|is) currently available/i);
  if(availableEggs)return`Only ${availableEggs[1]} eggs are available for this grade. Reduce the quantity or check egg stock for the sale date.`;
  if(text.includes("only available eggs in the selected grade"))return"There isn’t enough stock in this egg grade for the quantity entered. Reduce the quantity or choose another grade.";
  if(text.includes("bird sale quantity exceeds birds available"))return"The flock doesn’t have that many birds recorded on the sale date. Reduce the quantity or check the flock and date.";
  if(text.includes("flock is not available for sale"))return"This flock isn’t available for sale on that date. Check that the flock is active and the sale date is correct.";
  if(text.includes("invalid bird sale values")||text.includes("invalid bird sale"))return"Check the bird quantity, price per bird, amount received, and sale date. Quantities and prices must be valid, and payment can’t exceed the sale total.";
  if(text.includes("invalid sale items")||text.includes("invalid egg sale item")||text.includes("add at least one sale item"))return"Add at least one valid egg sale line, with a grade, unit, quantity, and unit price.";
  if(text.includes("invalid sale total or payment"))return"The sale total or amount received is invalid. Check the quantities, prices, discount, and payment amount.";
  if(text.includes("invalid discount"))return"The discount must be zero or more and cannot exceed the sale total.";
  if(text.includes("payment exceeds sale total"))return"The amount received is greater than the sale total. Reduce the payment or check the sale lines and discount.";
  if(text.includes("exceeds the remaining balance")||text.includes("exceeds remaining"))return"That payment is greater than the amount still owed. Check the outstanding balance and enter a smaller payment.";
  if(text.includes("customer is required")||text.includes("a valid customer is required"))return"Choose a customer for a sale with an unpaid balance. Walk-in sales must be paid in full.";
  if(text.includes("customer does not belong to this farm")||text.includes("invalid customer")||text.includes("customer access denied"))return"That customer isn’t available for the selected farm. Choose an active customer from this farm, or check the farm selection.";
  if(text.includes("credit terms are required")||text.includes("credit terms must"))return"Enter valid credit terms for the unpaid balance, including a due period of 1–365 days.";
  if(text.includes("credit days must"))return"Credit days must be between 1 and 365.";
  if(text.includes("change reason is required"))return"Enter a reason for changing the credit terms.";
  if(text.includes("payments must be voided first")||text.includes("active payments must be voided first"))return"Void the sale’s active payments first, then try voiding the sale again.";
  if(text.includes("sale edit denied"))return"This sale can’t be edited in its current status or with your current access. Refresh the page and check the sale status.";
  if(text.includes("sale void denied")||text.includes("bird sale void denied"))return"This sale can’t be voided in its current status or with your current access. Refresh the page and check the sale status.";
  if(text.includes("commercial access denied")||text.includes("credit terms access denied")||text.includes("authentication required")||text.includes("selected farm access denied"))return"You don’t have permission to do this. Ask a farm admin to check your access.";
  if(text.includes("explicit farm selection is required")||text.includes("invalid selected farm"))return"Select the farm you’re working with, then try again.";
  if(text.includes("sale edit or total below active payments"))return"The edited sale total can’t be lower than payments already recorded. Adjust the sale lines or review the payments first.";
  if(text.includes("invalid customer")||text.includes("customer does not belong to this farm"))return"Choose an active customer belonging to this farm.";
  const reference=randomUUID().slice(0,8).toUpperCase();
  console.error("Sales action failed",{reference,code:error.code,message:raw});
  return`We couldn’t complete this request because of a system error. Please try again. If it continues, give support reference ${reference}.`;
};
const msg=salesErrorMessage;const credit=(v:string|number|undefined)=>v===""||v===undefined?null:Number(v);
export async function createCustomerAction(input:unknown):Promise<ActionResult&{id?:string}>{await requireRole(["admin","manager"]);const p=customerSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{data,error}=await s.rpc("create_customer",{name:d.name,phone:d.phone,email:d.email??"",location:d.location,customer_type:d.customerType,notes:d.notes,default_credit_days:credit(d.defaultCreditDays)});if(error)return{ok:false,message:msg(error)};const r=Array.isArray(data)?data[0]:data;return{ok:true,message:"Customer created.",id:r.id}}
export async function updateCustomerAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=customerSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("update_customer",{target_customer:id,name:d.name,phone:d.phone,email:d.email??"",location:d.location,customer_type:d.customerType,active:d.active,notes:d.notes,default_credit_days:credit(d.defaultCreditDays)});if(error)return{ok:false,message:msg(error)};revalidatePath(`/customers/${id}`);return{ok:true,message:"Customer updated."}}
export async function postSaleAction(input:unknown):Promise<ActionResult&{id?:string}>{await requireRole(["admin","manager"]);const p=saleSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{data,error}=await s.rpc("post_graded_egg_sale",{customer_id:d.customerId||null,sale_date:d.saleDate,items:d.items.map(x=>({egg_grade_id:x.eggGradeId,unit:x.unit,quantity:x.quantity,price_per_unit:x.pricePerUnit})),discount:d.discount,amount_paid:d.amountPaid,payment_method:d.paymentMethod,notes:d.notes,credit_days:credit(d.creditDays)});if(error)return{ok:false,message:msg(error)};const r=Array.isArray(data)?data[0]:data;revalidatePath("/dashboard");revalidatePath("/collections");revalidatePath("/eggs");return{ok:true,message:"Sale recorded successfully.",id:r.id}}
export async function postBirdSaleAction(input:unknown):Promise<ActionResult&{id?:string}>{await requireRole(["admin","manager"]);const p=birdSaleSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{data,error}=await s.rpc("post_bird_sale",{customer_id:d.customerId,target_flock_id:d.flockId,sale_date:d.saleDate,sale_category:d.category,quantity:d.quantity,price_per_bird:d.pricePerBird,amount_paid:d.amountPaid,payment_method:d.paymentMethod,credit_days:credit(d.creditDays),notes:d.notes});if(error)return{ok:false,message:msg(error)};const r=Array.isArray(data)?data[0]:data;["/dashboard","/sales","/collections","/flocks","/reports"].forEach(path=>revalidatePath(path));return{ok:true,message:"Bird sale recorded and flock population updated.",id:r.id}}
export async function updateSaleAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=saleEditSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("update_graded_egg_sale",{target_sale:id,customer_id:d.customerId||null,items:d.items.map(x=>({egg_grade_id:x.eggGradeId,unit:x.unit,quantity:x.quantity,price_per_unit:x.pricePerUnit})),discount:d.discount,notes:d.notes,credit_days:credit(d.creditDays)});if(error)return{ok:false,message:msg(error)};revalidatePath(`/sales/${id}`);revalidatePath("/collections");revalidatePath("/eggs");return{ok:true,message:"Sale updated."}}
export async function updateSaleCreditTermsAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=creditTermsSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const s=await createClient(),{error}=await s.rpc("update_sale_credit_terms",{target_sale:id,new_credit_days:p.data.creditDays,new_due_date:p.data.dueDate,change_reason:p.data.reason});if(error)return{ok:false,message:msg(error)};revalidatePath(`/sales/${id}`);revalidatePath("/collections");revalidatePath("/dashboard");return{ok:true,message:"Credit terms updated."}}
export async function recordPaymentAction(id:string,input:unknown):Promise<ActionResult>{await requireRole(["admin","manager"]);const p=paymentSchema.safeParse(input);if(!p.success)return{ok:false,message:p.error.issues[0].message};const d=p.data,s=await createClient(),{error}=await s.rpc("record_customer_payment",{target_sale:id,payment_date:d.paymentDate,amount:d.amount,payment_method:d.paymentMethod,reference:d.reference,notes:d.notes});if(error)return{ok:false,message:msg(error)};revalidatePath(`/sales/${id}`);revalidatePath("/collections");revalidatePath("/dashboard");return{ok:true,message:"Payment recorded."}}
export async function voidPaymentAction(id:string,reason:string):Promise<ActionResult>{await requireRole(["admin"]);const s=await createClient(),{error}=await s.rpc("void_customer_payment",{target_payment:id,reason});if(error)return{ok:false,message:msg(error)};revalidatePath("/sales");revalidatePath("/collections");return{ok:true,message:"Payment voided."}}
export async function voidSaleAction(id:string,reason:string):Promise<ActionResult>{await requireRole(["admin"]);const s=await createClient(),{error}=await s.rpc("void_egg_sale",{target_sale:id,reason});if(error)return{ok:false,message:msg(error)};revalidatePath(`/sales/${id}`);revalidatePath("/collections");return{ok:true,message:"Sale voided and inventory restored."}}
export async function voidBirdSaleAction(id:string,reason:string):Promise<ActionResult>{await requireRole(["admin"]);const s=await createClient(),{error}=await s.rpc("void_bird_sale",{target_sale:id,reason});if(error)return{ok:false,message:msg(error)};["/sales","/collections","/flocks","/dashboard","/reports"].forEach(path=>revalidatePath(path));return{ok:true,message:"Bird sale voided and flock population restored."}}
