import { createClient } from "@/lib/supabase/server";
import { Card } from "@/components/ui/card";
import { PlatformPlanEditor, PlatformPlanForm, type PlatformPlan } from "@/components/forms/platform-plan-form";

export default async function PlatformPlans() {
  const supabase = await createClient();
  const { data } = await supabase.from("subscription_plans").select("id,code,name,description,currency,monthly_price,annual_price,default_trial_days,default_grace_days,max_users,is_active").order("name");
  const plans = (data ?? []) as PlatformPlan[];
  return <div className="mx-auto max-w-6xl"><div><p className="text-sm font-semibold text-emerald-800">Commercial configuration</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Subscription plans</h1><p className="mt-2 max-w-2xl text-stone-600">Prices are entered by HabFarms when commercial terms are approved. Updating a plan never changes an existing billing-period price.</p></div><Card className="mt-7 p-5 sm:p-6"><h2 className="text-lg font-semibold">Create plan</h2><p className="mt-1 text-sm text-stone-600">Codes are permanent technical references. Use a clear code such as <span className="font-medium">STANDARD</span>.</p><div className="mt-5"><PlatformPlanForm /></div></Card><div className="mt-7 grid gap-4 lg:grid-cols-2">{plans.map((plan) => <Card key={plan.id} className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold tracking-[0.12em] text-emerald-800">{plan.code}</p><h2 className="mt-2 text-xl font-bold">{plan.name}</h2></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${plan.is_active ? "bg-emerald-50 text-emerald-800" : "bg-stone-100 text-stone-600"}`}>{plan.is_active ? "Active" : "Inactive"}</span></div><p className="mt-3 min-h-10 text-sm text-stone-600">{plan.description || "No description added."}</p><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-stone-500">Monthly</dt><dd className="mt-1 font-semibold">{plan.currency} {plan.monthly_price ?? "—"}</dd></div><div><dt className="text-stone-500">Annual</dt><dd className="mt-1 font-semibold">{plan.currency} {plan.annual_price ?? "—"}</dd></div><div><dt className="text-stone-500">Trial / grace</dt><dd className="mt-1 font-semibold">{plan.default_trial_days} / {plan.default_grace_days} days</dd></div><div><dt className="text-stone-500">Maximum users</dt><dd className="mt-1 font-semibold">{plan.max_users ?? "Unlimited"}</dd></div></dl><PlatformPlanEditor plan={plan} /></Card>)}{!plans.length && <Card className="p-8 text-center text-sm text-stone-600">No subscription plans are configured yet.</Card>}</div></div>;
}
