"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { ReceiptText } from "lucide-react";
import { postBirdSaleAction } from "@/app/actions/sales";
import { money } from "@/lib/format";
import { Button } from "@/components/ui/button";
import { ChickenIcon } from "@/components/ui/chicken-icon";
import { Input } from "@/components/ui/input";

type Customer = { id: string; name: string; default_credit_days: number | null };
type Flock = { id: string; name: string; live: number; age: string };
const labels = { live_bird: "Live Bird", spent_layer: "Spent Layer", cull_bird: "Cull Bird" };

export function BirdSaleForm({ customers, flocks, today, currency }: { customers: Customer[]; flocks: Flock[]; today: string; currency: string }) {
  const router = useRouter(); const [pending, start] = useTransition();
  const [message, setMessage] = useState<{ ok: boolean; text: string; id?: string } | null>(null);
  const [customerId, setCustomerId] = useState(customers[0]?.id ?? ""); const [flockId, setFlockId] = useState(flocks[0]?.id ?? "");
  const [quantity, setQuantity] = useState(1); const [price, setPrice] = useState(0); const [paid, setPaid] = useState(0);
  const [credit, setCredit] = useState<number | "">(customers[0]?.default_credit_days ?? "");
  const flock = flocks.find((item) => item.id === flockId); const total = useMemo(() => Math.max(0, quantity * price), [quantity, price]); const outstanding = Math.max(0, total - paid);
  if (message?.ok) return <div className="rounded-2xl border border-[#d8e8b8] bg-[#f7fbe9] p-6"><ReceiptText className="text-[#659d24]"/><h2 className="mt-4 text-lg font-bold">Bird sale recorded</h2><p className="mt-1 text-stone-600">{message.text}</p><Button className="mt-5" onClick={() => router.push(message.id ? `/sales/${message.id}` : "/sales")}>View sale</Button></div>;
  return <form className="space-y-7" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); start(async () => { const result = await postBirdSaleAction({ customerId, flockId, saleDate: form.get("saleDate"), category: form.get("category"), quantity, pricePerBird: price, amountPaid: paid, paymentMethod: form.get("paymentMethod"), creditDays: outstanding > 0 ? credit : "", notes: form.get("notes") }); setMessage({ ok: result.ok, text: result.message, id: result.id }); }); }}>
    <section className="grid gap-5 rounded-2xl border border-[#e3e8de] bg-[#fffefb] p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-bold">Sale information</h2><label className="text-sm font-semibold">Sale date<Input className="mt-2" name="saleDate" type="date" defaultValue={today}/></label><label className="text-sm font-semibold">Customer<select required className="mt-2 min-h-11 w-full rounded-xl border border-stone-300 bg-white px-3" value={customerId} onChange={(event) => { setCustomerId(event.target.value); setCredit(customers.find((customer) => customer.id === event.target.value)?.default_credit_days ?? ""); }}><option value="">Select customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label></section>
    <section className="grid gap-5 rounded-2xl border border-[#e3e8de] bg-[#fffefb] p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-bold">Birds</h2><label className="text-sm font-semibold">Flock<select required className="mt-2 min-h-11 w-full rounded-xl border border-stone-300 bg-white px-3" value={flockId} onChange={(event) => setFlockId(event.target.value)}><option value="">Select flock</option>{flocks.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.live} live birds</option>)}</select></label><label className="text-sm font-semibold">Sale category<select name="category" className="mt-2 min-h-11 w-full rounded-xl border border-stone-300 bg-white px-3">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="text-sm font-semibold">Quantity of birds<Input className="mt-2" required type="number" min="1" max={flock?.live ?? undefined} value={quantity} onChange={(event) => setQuantity(Number(event.target.value))}/>{flock && <span className="mt-1 block text-xs font-normal text-stone-500">Available: {flock.live.toLocaleString()} · {flock.age}</span>}</label><div className="rounded-xl bg-[#f2f8e5] p-4"><p className="text-sm text-stone-600">Flock after sale</p><p className="mt-1 text-2xl font-bold data-number">{Math.max(0, (flock?.live ?? 0) - quantity).toLocaleString()}</p><p className="mt-1 text-xs text-stone-500">Validated again by the database.</p></div></section>
    <section className="grid gap-5 rounded-2xl border border-[#e3e8de] bg-[#fffefb] p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-bold">Pricing & payment</h2><label className="text-sm font-semibold">Price per bird<Input className="mt-2" required type="number" min="0.01" step="0.01" value={price || ""} onChange={(event) => setPrice(Number(event.target.value))}/></label><div className="rounded-xl bg-stone-50 p-4"><p className="text-sm text-stone-600">Sale total</p><p className="mt-1 text-2xl font-bold data-number">{money(total, currency)}</p></div><label className="text-sm font-semibold">Amount received now<Input className="mt-2" required type="number" min="0" max={total} step="0.01" value={paid || ""} onChange={(event) => setPaid(Number(event.target.value))}/></label><label className="text-sm font-semibold">Payment method<select name="paymentMethod" className="mt-2 min-h-11 w-full rounded-xl border border-stone-300 bg-white px-3"><option value="cash">Cash</option><option value="momo">Mobile money</option><option value="bank_transfer">Bank transfer</option><option value="other">Other</option></select></label>{outstanding > 0 && <label className="text-sm font-semibold sm:col-span-2">Credit period (days)<Input className="mt-2 max-w-xs" required type="number" min="1" max="365" value={credit} onChange={(event) => setCredit(Number(event.target.value))}/><span className="mt-1 block text-xs font-normal text-stone-500">Outstanding: {money(outstanding, currency)}. A customer receivable will be created.</span></label>}</section>
    <label className="block text-sm font-semibold">Notes<textarea name="notes" className="mt-2 min-h-24 w-full rounded-xl border border-stone-300 p-3"/></label>{message && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{message.text}</p>}<Button disabled={pending || !flock}><ChickenIcon size={20}/>{pending ? "Posting…" : "Post Bird Sale"}</Button>
  </form>;
}
