"use client";
import { useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { useForm,type Resolver } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { createFlockAction,updateFlockAction } from "@/app/actions/operations";
import { flockSchema,flockUpdateSchema } from "@/lib/validation/operations";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input";
type Values={flockName:string;batchReference:string;breed:string;housePen:string;startDate:string;initialBirds:number|string;ageAtArrivalWeeks:number|string;source:string;notes:string;status:"active"|"closed"|"sold"|"culled"};
export function FlockForm({flock}:{flock?:Values&{id:string}}){const router=useRouter(),[pending,start]=useTransition(),[error,setError]=useState("");const schema=flock?flockUpdateSchema:flockSchema;const{register,handleSubmit,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema) as unknown as Resolver<Values>,defaultValues:flock??{status:"active",startDate:new Date().toISOString().slice(0,10),batchReference:"",breed:"",housePen:"",source:"",notes:"",ageAtArrivalWeeks:""}});const field=(name:keyof Values,label:string,props:React.InputHTMLAttributes<HTMLInputElement>={})=><label className="block text-sm font-medium">{label}<Input className="mt-2" {...props}{...register(name)}/>{errors[name]&&<span className="mt-1 block text-sm text-red-700">{String(errors[name]?.message)}</span>}</label>;return <form className="grid gap-5 sm:grid-cols-2" onSubmit={handleSubmit(v=>start(async()=>{const result=flock?await updateFlockAction(flock.id,v):await createFlockAction(v);if(!result.ok)setError(result.message);else if(!flock&&result.id)router.push(`/flocks/${result.id}`);else router.refresh();}))}>{field("flockName","Flock name *")}{field("batchReference","Batch reference")}{field("breed","Breed")}{field("housePen","House / pen")}{field("startDate","Start date *",{type:"date"})}{!flock&&field("initialBirds","Initial birds *",{type:"number",min:1,inputMode:"numeric"})}{field("ageAtArrivalWeeks","Age at arrival (weeks)",{type:"number",min:0,inputMode:"numeric"})}{field("source","Source")}{flock&&<label className="block text-sm font-medium">Status<select className="mt-2 min-h-11 w-full rounded-lg border border-stone-300 bg-white px-3" {...register("status")}><option value="active">Active</option><option value="closed">Closed</option><option value="sold">Sold</option><option value="culled">Culled</option></select></label>}<label className="block text-sm font-medium sm:col-span-2">Notes<textarea className="mt-2 min-h-28 w-full rounded-lg border border-stone-300 p-3" {...register("notes")}/></label>{error&&<p className="text-sm text-red-700 sm:col-span-2">{error}</p>}<div className="sm:col-span-2"><Button disabled={pending}>{pending?"Saving...":flock?"Save flock":"Create flock"}</Button></div></form>}
