"use client";

import { useState, useTransition } from "react";
import { createPlatformAccountNoteAction, retryPlatformCommunicationsAction, sendPlatformTestEmailAction, updatePlatformSettingsAction } from "@/app/actions/platform-operations";

export type PlatformSettingsValues = { company_name: string; support_name: string | null; support_email: string | null; support_phone: string | null; billing_contact_email: string | null; default_currency: string; default_trial_days: number; default_grace_days: number; trial_expiry_reminder_days: number; subscription_due_reminder_days: number; grace_ending_reminder_days: number; platform_timezone: string };

export function PlatformSettingsForm({ settings }: { settings: PlatformSettingsValues }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  return <form className="space-y-7" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { const result = await updatePlatformSettingsAction({ companyName: form.get("companyName"), supportName: form.get("supportName"), supportEmail: form.get("supportEmail"), supportPhone: form.get("supportPhone"), billingContactEmail: form.get("billingContactEmail"), defaultCurrency: form.get("defaultCurrency"), defaultTrialDays: form.get("defaultTrialDays"), defaultGraceDays: form.get("defaultGraceDays"), trialReminderDays: form.get("trialReminderDays"), dueReminderDays: form.get("dueReminderDays"), graceReminderDays: form.get("graceReminderDays"), timezone: form.get("timezone") }); setMessage(result.message); }) }}>
    <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-semibold">Business identity</legend><Field name="companyName" label="Company name" defaultValue={settings.company_name} /><Field name="defaultCurrency" label="Default currency" defaultValue={settings.default_currency} maxLength={3} /><Field name="timezone" label="Platform timezone" defaultValue={settings.platform_timezone} /></fieldset>
    <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-semibold">Customer support</legend><Field name="supportName" label="Support name" defaultValue={settings.support_name ?? ""} required={false} /><Field name="supportEmail" label="Support email" type="email" defaultValue={settings.support_email ?? ""} required={false} /><Field name="supportPhone" label="Support phone" defaultValue={settings.support_phone ?? ""} required={false} /><Field name="billingContactEmail" label="Billing contact email" type="email" defaultValue={settings.billing_contact_email ?? ""} required={false} /></fieldset>
    <fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-semibold">Commercial defaults</legend><NumberField name="defaultTrialDays" label="Default trial days" defaultValue={settings.default_trial_days} /><NumberField name="defaultGraceDays" label="Default grace days" defaultValue={settings.default_grace_days} /></fieldset>
    <fieldset className="grid gap-4 sm:grid-cols-3"><legend className="mb-3 font-semibold sm:col-span-3">Communication defaults</legend><NumberField name="trialReminderDays" label="Trial-expiry reminder days" defaultValue={settings.trial_expiry_reminder_days} /><NumberField name="dueReminderDays" label="Due reminder days" defaultValue={settings.subscription_due_reminder_days} /><NumberField name="graceReminderDays" label="Grace-ending reminder days" defaultValue={settings.grace_ending_reminder_days} /></fieldset>
    <p className="rounded-xl bg-stone-50 p-3 text-sm text-stone-600">These values guide future communication and account setup. They never rewrite existing plan, subscription, billing-period, trial, or grace snapshots.</p>{message && <p role="status" className="rounded-xl bg-lime-50 p-3 text-sm text-emerald-900">{message}</p>}<button disabled={pending} className="min-h-11 rounded-xl bg-emerald-800 px-4 font-semibold text-white disabled:opacity-60">{pending ? "Saving…" : "Save Platform settings"}</button>
  </form>;
}

export function PlatformAccountNoteForm({ farmId }: { farmId: string }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(""); const [value, setValue] = useState("");
  return <form className="mt-4" onSubmit={(event) => { event.preventDefault(); startTransition(async () => { const result = await createPlatformAccountNoteAction({ farmId, note: value }); setMessage(result.message); if (result.ok) setValue(""); }) }}><label className="text-sm font-medium">New internal note<textarea value={value} onChange={(event) => setValue(event.target.value)} required maxLength={2000} className="mt-2 min-h-24 w-full rounded-xl border p-3" placeholder="Visible to Platform Admins only." /></label>{message && <p role="status" className="mt-2 text-sm text-stone-600">{message}</p>}<button disabled={pending} className="mt-3 min-h-11 rounded-xl border px-4 text-sm font-semibold disabled:opacity-60">{pending ? "Saving…" : "Add note"}</button></form>;
}

export function PlatformCommunicationsRetry() {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  return <div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" disabled={pending} onClick={() => startTransition(async () => setMessage((await retryPlatformCommunicationsAction()).message))} className="min-h-10 rounded-xl border border-stone-300 bg-white px-3 text-sm font-semibold hover:bg-stone-50 disabled:opacity-60">{pending ? "Running…" : "Retry pending messages"}</button>{message && <p role="status" className="text-sm text-stone-600">{message}</p>}</div>;
}

export function PlatformEmailTest() {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  return <div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" disabled={pending} onClick={() => startTransition(async () => setMessage((await sendPlatformTestEmailAction()).message))} className="min-h-10 rounded-xl border border-emerald-800 px-3 text-sm font-semibold text-emerald-900 hover:bg-emerald-50 disabled:opacity-60">{pending ? "Sending one test…" : "Send one test email"}</button>{message && <p role="status" className="text-sm text-stone-600">{message}</p>}</div>;
}

function Field({ name, label, defaultValue, type = "text", required = true, maxLength }: { name: string; label: string; defaultValue: string; type?: string; required?: boolean; maxLength?: number }) { return <label className="text-sm font-medium">{label}<input name={name} type={type} defaultValue={defaultValue} required={required} maxLength={maxLength} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label>; }
function NumberField({ name, label, defaultValue }: { name: string; label: string; defaultValue: number }) { return <label className="text-sm font-medium">{label}<input name={name} type="number" min="0" max="365" defaultValue={defaultValue} required className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label>; }
