"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createPlatformFarmAction, resendPlatformOwnerInvitationAction, revokePlatformOwnerInvitationAction } from "@/app/actions/platform";

type Plan = { id: string; name: string; default_trial_days: number };
type Notice = { ok: boolean; message: string } | null;

export function PlatformFarmForm({ plans, today }: { plans: Plan[]; today: string }) {
  const router = useRouter(); const [notice, setNotice] = useState<Notice>(null), [pending, start] = useTransition();
  return <form className="grid gap-5" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); start(async () => { const r = await createPlatformFarmAction({ farmName: form.get("farmName"), ownerName: form.get("ownerName"), ownerEmail: form.get("ownerEmail"), ownerPhone: form.get("ownerPhone"), country: form.get("country"), internalNotes: form.get("internalNotes"), planId: form.get("planId"), trialEnabled: form.get("trialEnabled") === "on", trialDays: form.get("trialDays") || undefined, billingCycle: form.get("billingCycle"), startDate: form.get("startDate") }); setNotice(r); if (r.ok && r.id) router.push(`/platform/farms/${r.id}`); }); }}>
    <fieldset className="grid gap-4 rounded-2xl border border-stone-200 p-4 sm:grid-cols-2"><legend className="px-2 text-sm font-semibold">Customer</legend><label className="text-sm font-medium">Farm or business name<input required name="farmName" className="mt-2 min-h-11 w-full rounded-xl border px-3" placeholder="Green Acres Poultry" /></label><label className="text-sm font-medium">Owner full name<input required name="ownerName" className="mt-2 min-h-11 w-full rounded-xl border px-3" placeholder="Kwame Mensah" /></label><label className="text-sm font-medium">Owner email<input required type="email" name="ownerEmail" className="mt-2 min-h-11 w-full rounded-xl border px-3" placeholder="owner@example.com" /></label><label className="text-sm font-medium">Phone <span className="font-normal text-stone-500">optional</span><input name="ownerPhone" className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-medium">Country <span className="font-normal text-stone-500">optional</span><input name="country" className="mt-2 min-h-11 w-full rounded-xl border px-3" placeholder="Ghana" /></label><label className="text-sm font-medium">Internal notes <span className="font-normal text-stone-500">optional</span><input name="internalNotes" className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label></fieldset>
    <fieldset className="grid gap-4 rounded-2xl border border-stone-200 p-4 sm:grid-cols-2"><legend className="px-2 text-sm font-semibold">Initial commercial setup</legend><label className="text-sm font-medium">Plan<select required defaultValue="" name="planId" className="mt-2 min-h-11 w-full rounded-xl border bg-white px-3"><option value="" disabled>Select a plan</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label className="text-sm font-medium">Billing cycle<select name="billingCycle" defaultValue="monthly" className="mt-2 min-h-11 w-full rounded-xl border bg-white px-3"><option value="monthly">Monthly</option><option value="annual">Annual</option></select></label><label className="flex min-h-11 items-center gap-3 text-sm font-medium"><input name="trialEnabled" type="checkbox" defaultChecked />Start with a trial</label><label className="text-sm font-medium">Trial days<input name="trialDays" type="number" min="0" max="365" defaultValue="14" className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label className="text-sm font-medium">Subscription start date<input required name="startDate" type="date" defaultValue={today} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label></fieldset>
    {notice && <p role="status" className={`rounded-xl p-3 text-sm ${notice.ok ? "bg-emerald-50 text-emerald-900" : "bg-red-50 text-red-800"}`}>{notice.message}</p>}<button disabled={pending} className="min-h-11 rounded-xl bg-emerald-800 px-5 font-semibold text-white disabled:opacity-60">{pending ? "Creating customer farm…" : "Create farm and send owner invitation"}</button>
  </form>;
}

export function OwnerInvitationActions({ invitationId, canResend, canRevoke }: { invitationId: string; canResend: boolean; canRevoke: boolean }) {
  const [notice, setNotice] = useState<Notice>(null), [pending, start] = useTransition();
  if (!canResend && !canRevoke) return null;
  return <div className="mt-4 space-y-2"><div className="flex flex-wrap gap-2">{canResend && <button disabled={pending} onClick={() => start(async () => setNotice(await resendPlatformOwnerInvitationAction(invitationId)))} className="min-h-11 rounded-xl border px-4 text-sm font-semibold">Resend invitation</button>}{canRevoke && <button disabled={pending} onClick={() => { if (confirm("Revoke this owner invitation? The link will no longer work.")) start(async () => setNotice(await revokePlatformOwnerInvitationAction(invitationId))); }} className="min-h-11 rounded-xl border border-red-200 px-4 text-sm font-semibold text-red-700">Revoke invitation</button>}</div>{notice && <p role="status" className={`text-sm ${notice.ok ? "text-emerald-800" : "text-red-700"}`}>{notice.message}</p>}</div>;
}
