"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { completePlatformOnboardingAction, createPlatformOnboardingFlockAction, savePlatformOnboardingSettingsAction, skipPlatformOnboardingStepAction } from "@/app/actions/platform";

type Props = { farm: { name: string; currency: string; timezone: string; crate_size: number; feed_bag_size_kg: number; opening_cash_balance: number }; settings: { default_egg_price_per_crate: number; default_loose_egg_price: number; feed_alert_warning_days: number; feed_alert_critical_days: number; average_feed_days_window: number }; progress: { settings: boolean; flock: boolean; opening: boolean } };

export function PlatformOnboarding({ farm, settings, progress }: Props) {
  const router = useRouter();
  const [notice, setNotice] = useState("");
  const [pending, startTransition] = useTransition();
  const run = (work: () => Promise<{ ok: boolean; message: string }>, finish = false) => startTransition(async () => { const result = await work(); setNotice(result.message); if (result.ok) { if (finish) router.push("/dashboard"); else router.refresh(); } });
  return <main className="min-h-screen bg-[#edf2e7] px-4 py-8 sm:py-12"><div className="mx-auto max-w-3xl">
    <p className="text-sm font-semibold text-emerald-800">Welcome to HabFarms</p><h1 className="mt-2 text-3xl font-bold">Set up {farm.name}</h1><p className="mt-2 text-stone-600">Save the required farm settings first. Flocks and opening stock can be added now or later.</p>
    <div className="mt-6 grid gap-3 sm:grid-cols-4">{[["Account", true], ["Farm settings", progress.settings], ["First flock", progress.flock], ["Opening stock", progress.opening]].map(([label, complete]) => <div key={String(label)} className="rounded-xl border bg-white p-3 text-sm"><p className="font-medium">{label}</p><p className={complete ? "mt-1 text-emerald-800" : "mt-1 text-stone-500"}>{complete ? "Complete" : "Optional / next"}</p></div>)}</div>
    <section className="mt-6 rounded-2xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold">1. Farm settings <span className="text-red-700">required</span></h2><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => savePlatformOnboardingSettingsAction({ name: form.get("name"), currency: form.get("currency"), timezone: form.get("timezone"), crateSize: form.get("crateSize"), feedBagSizeKg: form.get("feedBagSizeKg"), openingCashBalance: form.get("openingCashBalance"), defaultEggPricePerCrate: settings.default_egg_price_per_crate, defaultLooseEggPrice: settings.default_loose_egg_price, feedAlertWarningDays: settings.feed_alert_warning_days, feedAlertCriticalDays: settings.feed_alert_critical_days, averageFeedDaysWindow: settings.average_feed_days_window })); }}>
      <label>Farm name<input required name="name" defaultValue={farm.name} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>Currency<input required name="currency" defaultValue={farm.currency} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>Timezone<input required name="timezone" defaultValue={farm.timezone} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>Eggs per crate<input required name="crateSize" type="number" min="1" defaultValue={farm.crate_size} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>Feed bag size (kg)<input required name="feedBagSizeKg" type="number" min="0.001" step="0.001" defaultValue={farm.feed_bag_size_kg} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>Opening cash balance<input required name="openingCashBalance" type="number" min="0" step="0.01" defaultValue={farm.opening_cash_balance} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><button disabled={pending} className="min-h-11 rounded-xl bg-emerald-800 px-4 font-semibold text-white sm:col-span-2">Save farm settings</button>
    </form></section>
    {progress.settings && <section className="mt-5 rounded-2xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold">2. First flock <span className="text-stone-500">optional</span></h2><p className="mt-2 text-sm text-stone-600">Create a real flock now, or continue and add one later.</p><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); run(() => createPlatformOnboardingFlockAction({ flockName: form.get("flockName"), batchReference: "", breed: form.get("breed"), housePen: form.get("housePen"), startDate: form.get("startDate"), initialBirds: form.get("initialBirds"), ageAtArrivalWeeks: "", source: "", notes: "" })); }}><label>Flock name<input required name="flockName" className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>Starting birds<input required name="initialBirds" type="number" min="1" className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>Breed<input name="breed" className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>House / pen<input name="housePen" className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><label>Start date<input required name="startDate" type="date" defaultValue={new Date().toISOString().slice(0, 10)} className="mt-2 min-h-11 w-full rounded-xl border px-3" /></label><div className="flex items-end gap-2"><button disabled={pending} className="min-h-11 rounded-xl border px-4 font-semibold">Create flock</button><button type="button" disabled={pending || progress.flock} onClick={() => run(() => skipPlatformOnboardingStepAction("first_flock"))} className="min-h-11 px-2 text-sm font-semibold text-emerald-800">Skip for now</button></div></form></section>}
    <section className="mt-5 rounded-2xl border bg-white p-5 sm:p-7"><h2 className="text-xl font-semibold">3. Opening stock <span className="text-stone-500">optional</span></h2><p className="mt-2 text-sm text-stone-600">Use the existing ledger-backed opening-stock tools after setup. Skip this when the farm starts with no stock.</p><button type="button" disabled={pending || progress.opening} onClick={() => run(() => skipPlatformOnboardingStepAction("opening_stock"))} className="mt-4 min-h-11 rounded-xl border px-4 text-sm font-semibold">Skip opening stock for now</button></section>
    {progress.settings && <section className="mt-5 rounded-2xl bg-emerald-900 p-5 text-white sm:p-7"><h2 className="text-xl font-semibold">Finish onboarding</h2><p className="mt-2 text-sm text-emerald-50">Your required settings are saved. You can add operational records from the workspace whenever you are ready.</p><button disabled={pending} onClick={() => run(completePlatformOnboardingAction, true)} className="mt-4 min-h-11 rounded-xl bg-lime-400 px-4 font-semibold text-stone-950">Finish and open dashboard</button></section>}
    {notice && <p role="status" className="mt-4 rounded-xl bg-white p-3 text-sm text-stone-700">{notice}</p>}
  </div></main>;
}
