"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createFeedProductionAction, createRawMaterialAction, postMaterialPurchaseAction, saveFeedRecipeAction, setMaterialOpeningStockAction } from "@/app/actions/feed";

type Option = { id: string; name: string };
function Notice({ message }: { message: string }) { return message ? <p role="status" className="rounded-lg bg-stone-100 p-3 text-sm">{message}</p> : null; }

export function MaterialForm() {
  const router = useRouter(), [message, setMessage] = useState(""), [pending, start] = useTransition();
  return <form className="space-y-5" onSubmit={(e) => { e.preventDefault(); const f = new FormData(e.currentTarget); start(async () => { const result = await createRawMaterialAction({ name: f.get("name"), description: f.get("description") }); setMessage(result.message); if (result.ok) setTimeout(() => router.push("/feed/materials"), 450); }); }}><label className="block text-sm font-medium">Material name<Input name="name" required className="mt-2" placeholder="e.g. Maize" /></label><label className="block text-sm font-medium">Description (optional)<textarea name="description" className="mt-2 min-h-24 w-full rounded-lg border p-3" /></label><Notice message={message}/><Button disabled={pending}>{pending ? "Saving…" : "Save material"}</Button></form>;
}
export function MaterialOpeningForm({ materials, today }: { materials: Option[]; today: string }) {
  const router = useRouter(), [message, setMessage] = useState(""), [pending, start] = useTransition();
  return <form className="space-y-5" onSubmit={(e) => {e.preventDefault();const f=new FormData(e.currentTarget);start(async()=>{const r=await setMaterialOpeningStockAction({materialId:f.get("material"),effectiveDate:f.get("date"),quantityKg:f.get("quantity"),unitCost:f.get("cost"),notes:f.get("notes")});setMessage(r.message);if(r.ok)setTimeout(()=>router.push("/feed/materials"),450)})}}><div className="grid gap-5 sm:grid-cols-2"><label>Material<select name="material" required className="mt-2 min-h-11 w-full rounded-lg border px-3">{materials.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Date<Input name="date" type="date" defaultValue={today} className="mt-2"/></label><label>Quantity (kg)<Input name="quantity" type="number" min="0.001" step="0.001" required className="mt-2"/></label><label>Opening cost per kg<Input name="cost" type="number" min="0" step="0.0001" required className="mt-2"/></label></div><label className="block">Notes<textarea name="notes" className="mt-2 min-h-24 w-full rounded-lg border p-3"/></label><Notice message={message}/><Button disabled={pending}>{pending?"Saving…":"Set opening stock"}</Button></form>;
}
export function MaterialPurchaseForm({ materials, suppliers, today }: { materials: Option[]; suppliers: Option[]; today: string }) {
  const router=useRouter(),[message,setMessage]=useState(""),[pending,start]=useTransition();
  return <form className="space-y-5" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);start(async()=>{const r=await postMaterialPurchaseAction({materialId:f.get("material"),supplierId:f.get("supplier"),purchaseDate:f.get("date"),quantityKg:f.get("quantity"),unitCost:f.get("cost"),amountPaid:f.get("paid"),notes:f.get("notes")});setMessage(r.message);if(r.ok)setTimeout(()=>router.push("/feed/materials"),450)})}}><div className="grid gap-5 sm:grid-cols-2"><label>Material<select name="material" required className="mt-2 min-h-11 w-full rounded-lg border px-3">{materials.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Supplier<select name="supplier" className="mt-2 min-h-11 w-full rounded-lg border px-3"><option value="">No supplier</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Date<Input name="date" type="date" defaultValue={today} className="mt-2"/></label><label>Quantity (kg)<Input name="quantity" type="number" min="0.001" step="0.001" required className="mt-2"/></label><label>Unit cost<Input name="cost" type="number" min="0" step="0.0001" required className="mt-2"/></label><label>Amount paid now<Input name="paid" type="number" min="0" step="0.01" defaultValue="0" required className="mt-2"/></label></div><label className="block">Notes<textarea name="notes" className="mt-2 min-h-24 w-full rounded-lg border p-3"/></label><Notice message={message}/><Button disabled={pending}>{pending?"Posting…":"Post material purchase"}</Button></form>;
}
export function FeedRecipeForm({ feeds, materials, today }: { feeds: Option[]; materials: Option[]; today: string }) {
  const router=useRouter(),[message,setMessage]=useState(""),[pending,start]=useTransition();
  return <form className="space-y-5" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const items=materials.map(x=>({materialId:x.id,quantityKg:f.get(`qty-${x.id}`)})).filter(x=>Number(x.quantityKg)>0);start(async()=>{const r=await saveFeedRecipeAction({feedTypeId:f.get("feed"),effectiveFrom:f.get("date"),notes:f.get("notes"),items});setMessage(r.message);if(r.ok)setTimeout(()=>router.push("/feed/setup"),450)})}}><div className="grid gap-5 sm:grid-cols-2"><label>Finished feed<select name="feed" required className="mt-2 min-h-11 w-full rounded-lg border px-3">{feeds.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Effective from<Input name="date" type="date" defaultValue={today} className="mt-2"/></label></div><fieldset><legend className="font-semibold">Recipe ingredients — 100kg basis</legend><p className="mt-1 text-sm text-stone-500">Enter each material once. The selected quantities must total exactly 100kg.</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{materials.map(x=><label key={x.id}>{x.name}<Input name={`qty-${x.id}`} type="number" min="0" step="0.001" defaultValue="0" className="mt-2"/></label>)}</div></fieldset><label className="block">Notes<textarea name="notes" className="mt-2 min-h-24 w-full rounded-lg border p-3"/></label><Notice message={message}/><Button disabled={pending}>{pending?"Saving…":"Save Feed Setup"}</Button></form>;
}
export function MakeFeedForm({ feeds, recipe, balances, today }: { feeds: Option[]; recipe: { feed_type_id: string; id: string; items: { material_id: string; name: string; quantity_kg: number }[] } | null; balances: Record<string, number>; today: string }) {
  const router=useRouter(),[feed,setFeed]=useState(feeds[0]?.id??""),[planned,setPlanned]=useState("100"),[message,setMessage]=useState(""),[pending,start]=useTransition(),scale=Number(planned||0)/100;
  if(!recipe) return <div className="rounded-xl border bg-white p-6"><label>Finished feed<select value={feed} onChange={e=>setFeed(e.target.value)} className="mt-2 min-h-11 w-full rounded-lg border px-3">{feeds.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><p className="mt-5 text-stone-600">No Feed Setup exists for this finished feed.</p><Button className="mt-4" onClick={()=>router.push(`/feed/setup?feed=${feed}`)}>Create Feed Setup</Button></div>;
  return <form className="space-y-5" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const items=recipe.items.map(x=>({materialId:x.material_id,quantityKg:f.get(`actual-${x.material_id}`)}));start(async()=>{const r=await createFeedProductionAction({feedTypeId:recipe.feed_type_id,productionDate:f.get("date"),plannedOutputKg:f.get("planned"),actualOutputKg:f.get("actualOutput"),notes:f.get("notes"),items});setMessage(r.message);if(r.ok)setTimeout(()=>router.push("/feed/production-history"),450)})}}><div className="grid gap-5 sm:grid-cols-2"><label>Finished feed<select disabled className="mt-2 min-h-11 w-full rounded-lg border px-3"><option>{feeds.find(x=>x.id===recipe.feed_type_id)?.name}</option></select></label><label>Date<Input name="date" type="date" defaultValue={today} className="mt-2"/></label><label>Planned output (kg)<Input name="planned" value={planned} onChange={e=>setPlanned(e.target.value)} type="number" min="0.001" step="0.001" required className="mt-2"/></label><label>Actual finished output (kg)<Input name="actualOutput" type="number" min="0.001" step="0.001" required className="mt-2"/></label></div><fieldset><legend className="font-semibold">Materials used</legend><div className="mt-4 space-y-3">{recipe.items.map(x=>{const guide=(x.quantity_kg*scale).toFixed(3),available=balances[x.material_id]??0;return <div key={x.material_id} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-4"><b>{x.name}</b><span className="text-sm text-stone-600">Recipe: {guide}kg</span><span className="text-sm text-stone-600">Available: {available}kg</span><Input name={`actual-${x.material_id}`} type="number" min="0.001" step="0.001" defaultValue={guide}/></div>})}</div></fieldset><label className="block">Notes<textarea name="notes" className="mt-2 min-h-24 w-full rounded-lg border p-3"/></label><Notice message={message}/><Button disabled={pending}>{pending?"Posting…":"Make feed"}</Button></form>;
}
